### ISSUE TITLE
Attaching Screenshot in Report

### ISSUE THREAD

**Issue by buvaneshj** [extent-framework/extentreports-java#102]
HI @anshooarora , 
I am implementing Extent report for my test framework using Cucumber. For some reason, the screenshot is not attached or appearing in the report. I am having the screenshots in a separate folder. I have tried using MediaEntityModelProvider too. I have used Extent Report 3 and 2 and addScreenCapture method is not available for end user in version 4. Please have a look and respond. Is it something that as associated with node creation.

        public ExtentReports extentReport;
	public ExtentTest feature;
	public ExtentTest scenario;
	public ExtentTest steps;

feature = extentReport.createTest(testName);
scenario = feature.createNode(testName);
steps = scenario.createNode(moduleName);

public void log(Status status, String details) throws Exception {
		Log.info(details);
		switch(status) {
			case FAIL:
				steps.log(status, details);
				if(driver!=null) {
					Log.error("Taking screenshot");
					attachScreenshot();
				}
				break;
			default:
				steps.log(status, details);
				break;
		}
	}

public void attachScreenshot() throws Exception {
	  steps.addScreenCaptureFromPath(takeScreenshot());
	}

	 public String takeScreenshot() throws Exception {
	  	File file =  ((TakesScreenshot)BaseSetup.getDriver()).getScreenshotAs(OutputType.FILE);
	  	String fileName = System.getProperty("user.dir")+"/Reports/screenshots/"+System.currentTimeMillis()+".jpg";
	  	File target = new File(fileName);
	  	FileUtils.copyFile(file,target);
	  	return target.getPath()	
	  }

**Comment by buvaneshj** [comment]
This is the HTML content for the screenshots that was present in the report. From this, it is clear that the image got attached but is not displaying. Here, the value of the style tag is  "display:none;". Please have a look.


<ul class="screenshots">
					<li><img class="r-img" onerror="this.style.display=&quot;none&quot;" data-featherlight="/Users/buvanesh.kg/GDSP_Phase2/gdscp/Reports/screenshots/1574416346872.png" src="/Users/buvanesh.kg/GDSP_Phase2/gdscp/Reports/screenshots/1574416346872.png" data-src="/Users/buvanesh.kg/GDSP_Phase2/gdscp/Reports/screenshots/1574416346872.png" style="display: none;"></li>
				</ul>

**Comment by anshooarora** [comment]
@buvaneshj Can you please tell me what version/name of adapter you are using?

**Comment by buvaneshj** [comment]
PFB the adapter and extent report versions.
<dependency>
   		 <groupId>com.aventstack</groupId>
   		 <artifactId>extentreports-cucumber4-adapter</artifactId>
  		  <version>1.0.7</version>
	</dependency>
	
	<dependency>
   		 <groupId>com.aventstack</groupId>
   		 <artifactId>extentreports</artifactId>
   		 <version>4.0.9</version>
	</dependency>

**Comment by anshooarora** [comment]
This question is pertaining to the adapter, not the core API.  You must use the embed hook to achieve this using either:

```
@After
public void after(Scenario scenario) {
    scenario.embed(extractBytes("img.png"), "image/png");
}

@AfterStep
public void afterStep(Scenario scenario) {
    scenario.embed(extractBytes("img.png"), "image/png");
}
```
