### ISSUE TITLE
Append Extent Report to existing report in v4.0.6

### ISSUE THREAD

**Issue by chiragbhakar89** [extent-framework/extentreports-java#103]
Hi, i am trying to append the extent report generated from current execution with an existing extent report from previous execution. Is it possible to do this in v 4.0.6?

**Comment by anshooarora** [comment]
@chiragbhakar89 appendExisting was removed in version 4 but it will be available starting version 5.

**Comment by anshooarora** [comment]
Planned for `4.10`

**Comment by anshooarora** [comment]
This is now available starting `4.10.0-SNAPSHOT` release.  The feature is in experimental stage, and preliminary use is a little crude:

```
// JsonFormatter is required to created a json file
JsonFormatter json = new JsonFormatter("target/test.json");
extent.attachReporter(json);
```

Appending to an existing json file:

```
TestModelReportBuilder modelBuilder = new TestModelReportBuilder();
modelBuilder.recreateModelFromJson(extent, new File("target/test.json"));
```

Complete example:

```
ExtentReports extent = new ExtentReports();
TestModelReportBuilder modelBuilder = new TestModelReportBuilder();
modelBuilder.recreateModelFromJson(extent, new File("target/spark/test.json"));
ExtentSparkReporter spark = new ExtentSparkReporter("target/spark/");
JsonFormatter json = new JsonFormatter("target/spark/test.json");
extent.attachReporter(spark,json);
```

**Comment by anshooarora** [comment]
Closing as this being included in milestone release 4.10.0.

**Comment by cacciaf** [comment]
Is it possible for html reports?
Thank you

**Comment by anshooarora** [comment]
Possible in version 5:

```
ExtentSparkReporter spark = new ExtentSparkReporter("spark.html");
JsonFormatter json = new JsonFormatter("extent.json");
ExtentReports extent = new ExtentReports();
extent.createDomainFromJsonArchive("extent.json");
extent.attachReporter(json, spark);
```

**Comment by cacciaf** [comment]
> Possible in version 5:
> 
> ```
> ExtentSparkReporter spark = new ExtentSparkReporter("spark.html");
> JsonFormatter json = new JsonFormatter("extent.json");
> ExtentReports extent = new ExtentReports();
> extent.createDomainFromJsonArchive("extent.json");
> extent.attachReporter(json, spark);
> ```

It seems to be working (thank you!) however now base64 screenshots are not clickable, it is shown a small preview (which is very good) but if you click the image nothing happens. 
I am just executing some random scripts and noticed this.

**Comment by anshooarora** [comment]
Thanks for checking,  I am marking this as a bug.

**Comment by cacciaf** [comment]
> Thanks for checking, I am marking this as a bug.

Thank for your amazin job.
I'll be running a few tests these days, can I report to you possible issues?

**Comment by anshooarora** [comment]
I would greatly appreciate it :)

**Comment by cacciaf** [comment]
I would like to suggest two points, if possible:

1. Tests should be sortable by execution date (start), or at least they should be appended with the latest on top.
At the moment the latest execution is appended to the bottom. If i have a large number of tests I will have to scroll down each time to look for my most recent report
![2020-07-24_21h34_21](https://user-images.githubusercontent.com/51408752/88428912-094e5980-cdf6-11ea-941a-6a0f60b445c8.png)

2. When taking a screenshot the status is set to "info", I think there should be a way (method) to set the status as pass, info, failed. Some managers do not like to see other than pass or fail.

Again, thank you very much for your effort and have a nice day.

**Comment by anshooarora** [comment]
Thanks.

1.  There is already an enhancement request https://github.com/extent-framework/extentreports-java/issues/136
2.  It is possible to attach a screenshot under any status, below shows 3 possible ways with `fail`, but the same signatures are available for all other status.

```
test.fail(Media media);
test.fail(String details, Media media);
test.fail(Throwable t, Media media);
```

**Comment by abhijeetexcel** [comment]
i have tries above code mentioned to merge my 2 spark reports. But its still generating the 2 different json files and 2 different reports. Can you please clarify how to do this during runtime ?

like i have 2 reports generated as below:

UAT1_Scenario_1_09_11_2020_03_23_50.html
UAT1_Scenario_2_09_11_2020_03_23_50.html

how to merge these two ?
