### ISSUE TITLE
Mark the first test run status as Retry when Retry analyzer is used

### ISSUE THREAD

**Issue by NallaSandeep** [extent-framework/extentreports-java#104]
In the latest version of TestNG i.e., 7.0.0, new method is provided to identify if the test was retried.
**boolean wasRetried();**

Using this method, can you mark the test as Retry in extent report?

Ref: https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/ITestResult.java

**Comment by anshooarora** [comment]
@NallaSandeep I would suggest adding a "retry" tag to such tests using `assignCategory`.  Other than marking it as a tag, there is no concept of retry available in the API which can be used.
