### ISSUE TITLE
Skipped Tests are not displayed on ExtentReports V 3.1.5

### ISSUE THREAD

**Issue by chetanJTH** [extent-framework/extentreports-java#105]
Skipped test are not displayed on extent reports.

I am using dependsonmethods and as per method extent report should display test case with log skip. But it print skip log on previous test case.

[   @Test(priority = 12)
void UndoRedo() {
    undoRedoCase.UndoRedoTest();
}

@Test(priority = 13)
void LockUnlock() {
    lockUnlockElement.LockUnlockCase();
}

@Test(priority = 14)
void FrameLayer() {
    layerFrame.FrameLayerCase();
}

@Test(priority = 15)
void AddImage() {
    addimage.AddImageCase();
}

@Test(priority = 16,dependsOnMethods = {"AddImage"})
void EraseImage() {
    imageErase.ImageEraseCase();
}]
Please check image image of test execution.

Image of console 5 test case,failed 1, skipped 1
![Untitled](https://user-images.githubusercontent.com/48850556/70137907-1545a980-16b5-11ea-8979-e8269645e519.png)

Extent report result.
![Untitled1](https://user-images.githubusercontent.com/48850556/70137931-255d8900-16b5-11ea-8bcb-b0162ca24e1f.png)

Skipped test case log printed on previous test case logs
![Untitled12](https://user-images.githubusercontent.com/48850556/70137951-31e1e180-16b5-11ea-9caf-3fc87cf4920a.png)

Skipped test case is not printing in extent report.

**Comment by sebinjqburst** [comment]
https://github.com/extent-framework/extentreports-java/issues/8

**Comment by chetanJTH** [comment]
@sebinjqburst @anshooarora : 
![Untitled101](https://user-images.githubusercontent.com/48850556/70613870-70384d00-1c2f-11ea-877a-c1f858b7cc05.png)
Some field is empty in v 4 and different than v 3. can you explain? i want to add timeline but don't know how in v 4.

**Comment by anshooarora** [comment]
@chetanJTH Are you using version 3 or 4?   Please note: version 3 is no longer supported.

**Comment by chetanJTH** [comment]
i'm using v 3.1.5
