### ISSUE TITLE
Updating from 3.X to 4.X breaks

### ISSUE THREAD

**Issue by SElab2019** [extent-framework/extentreports-java#111]
When I try to upgrade ExtentReports from 3.X to version 4.X. The following code breaks.
```
private static ExtentReports createInstance() {
	ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter(htmlReportPath+htmlFileName);
	htmlReporter.loadXMLConfig(new File(extentConfigFilePath));
	extent = new ExtentReports();
	extent.attachReporter(htmlReporter); 
	return extent;
}
```

The code should pass, but it throws an error:
```
Demo.java:[4,44] incompatible types: java.io.File cannot be converted to java.lang.String
```

**Comment by casalribeiro** [comment]
When you load the xml, that method no longer accepts only a File as parameter.
Try `new File extentConfigFilePath().getPath()` or pass a second parameter as `false`

Note: it only accepts:
`public void loadXMLConfig(String filePath)` 
or
`public void loadXMLConfig(File file, Boolean silent)`

**Comment by SElab2019** [comment]
Thanks for your quick helping. It could solve my problem. Would it be better to add a breaking announcement in the release note? Then all other developers who use ExtentReports can know it.

**Comment by anshooarora** [comment]
Thank you, adding this for backward compatibility.  This should not have been removed.

**Comment by SElab2019** [comment]
You are welcome. Thanks for your confirmation and quick fix.
