### ISSUE TITLE
v4.0.7+ tags tab lost a display number of warnings

### ISSUE THREAD

**Issue by waterwarrior** [extent-framework/extentreports-java#112]
v4.0.7+ behavior
![image](https://user-images.githubusercontent.com/59670558/72022989-e0390200-32c5-11ea-8b2c-68c2fee9e802.png)
in v4.0.6 it works correctly
![image](https://user-images.githubusercontent.com/59670558/72022910-af58cd00-32c5-11ea-975e-edd5a808084c.png)

**Comment by anshooarora** [comment]
Fixed for `ExtentSparkReporter`.  It now supports the SPA-style view like the V3HtmlReporter you've shared a screenshot for.  Available as snapshot release:

```
<groupId>com.aventstack</groupId>
<artifactId>extentreports</artifactId>
<version>4.1.2-SNAPSHOT</version>
```
