### ISSUE TITLE
v4.1.1  tags tab lost a display of a full name of test

### ISSUE THREAD

**Issue by waterwarrior** [extent-framework/extentreports-java#114]
before v4.1.1 on a tags tab we had a full hierarchical name of a test, for example v4.0.9 behavior
![image](https://user-images.githubusercontent.com/59670558/72104905-821d2500-3380-11ea-8395-c83c9028865b.png)
v4.1.1 displays only a name of a test instead of full hierarchical name
![image](https://user-images.githubusercontent.com/59670558/72105051-dd4f1780-3380-11ea-841a-bbffe886b4fb.png)

code example
```
            ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter("extent.html");
            htmlReporter.config().setTheme(Theme.DARK);
            ExtentReports mainReport = new ExtentReports();

            mainReport.attachReporter(htmlReporter);
            ExtentTest test = mainReport.createTest("Test").assignCategory("test category");
            ExtentTest node = test.createNode("Node").assignCategory("node category");
            node.createNode("step").pass("pass");
            htmlReporter.config().setReportName("report");
            mainReport.flush();
```

**Comment by anshooarora** [comment]
This was removed from the hierarchy and was to be added via tooltip/badge but was missed in the release. Will add it, and release in the next version.

**Comment by waterwarrior** [comment]
Will it be possible to enable it by default via htmlReporter.config() for example?
my reports without hierarchical name looks so weird on this tab
![image](https://user-images.githubusercontent.com/59670558/72123188-8cf1ad00-33b4-11ea-8574-bf26f773a6f7.png)

**Comment by anshooarora** [comment]
This will have to be added to the template, no other way.

**Comment by anshooarora** [comment]
What behavior do you see with ExtentSparkReporter? It should show the parent name, but not the entire hierarchy.

**Comment by waterwarrior** [comment]
ExtentSparkReporter displays a parent name under a node name
![image](https://user-images.githubusercontent.com/59670558/72225821-f3a5df00-35dd-11ea-8531-be4f1019d356.png)

**Comment by anshooarora** [comment]
closing this as per https://github.com/extent-framework/extentreports-java/commit/63495e0b378e946b4f519a075cb734eaad9319cc
