### ISSUE TITLE
TestName and Category Name both display under category.

### ISSUE THREAD

**Issue by chetanJTH** [extent-framework/extentreports-java#116]
testName and category name both display under category tab in extent report.

![extent](https://user-images.githubusercontent.com/48850556/72133641-fa4b1100-33a7-11ea-8998-c42ab078f1fe.png)

@anshooarora : any suggestion bro.

**Comment by chetanJTH** [comment]
@anshooarora  : any solution please.

**Comment by chetanJTH** [comment]
got it solved.

**Comment by anshooarora** [comment]
@chetanJTH thanks,  this would generally happen when you have invalid markup somewhere in the report.

**Comment by chetanJTH** [comment]
@anshooarora : was using set category in report and under test method too. so it was setting category twice.
