### ISSUE TITLE
ExtentReport for Maven tests run as bat cmd in parallel is not getting appended

### ISSUE THREAD

**Issue by rahgir** [extent-framework/extentreports-java#118]
Hi Anshoo,
Could you please help me with below problem ?

<dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>3.1.5</version>
        </dependency>

Class TestBase
{

 1. BeforeSuite: Initialise the Klov & ExtentHtmlReporter
 2. ExtentHtmlReporter htmlreporter  = new ExtentHtmlReporter("\\target\\report.html")
	htmlreporter.setAppendExisting(true);
 
 3. generic code to mark any test as pass or fail
 4. In AfterClass, extent.flush()
}

@Test(group=group1)
class testngTests1
{
	@Test
	public void test1()
	{
	}
	
	@Test
	public void test2()
	{
	}
}

@Test(group=group2)
class testngTests2
{
	@Test
	public void test1()
	{
	}
	
	@Test
	public void test2()
	{
	}
}

Now, in jenkin pipeline my tests are executed in parallel and few powershell scripts are executed inbetween them to bring the application DB in desired state as 

parallel (

	powershell script to restore application DB
	bat mvn test  -B -s C:/Tetris//modules/G3/Maven/integration.xml -Dextent.test.report.enabled=true -Dextent.klov.reporting.url=http://localhost:8081/ -Dmongodb.host=localhost -Dmongodb.port=27017 <multiple -D options> -Dgroups=group1
	
	powershell script to restore application DB
	bat mvn test  -B -s C:/Tetris//modules/G3/Maven/integration.xml -Dextent.test.report.enabled=true -Dextent.klov.reporting.url=http://localhost:8081/ -Dmongodb.host=localhost -Dmongodb.port=27017 <multiple -D options> -Dgroups=group2
)

Now I see that the report is generated perfectly as expected, but the one which finishes last overwrite the earlier one. Could you please help me with a solution to merge all reports together without any getting overwritten ?

@anshooarora

**Comment by anshooarora** [comment]
Do you want both reports saved?  I see that the name of the report is hard-coded in the HtmlReporter instantiation.  You can either use increment strategy or use timestamp so both reports are saved.

**Comment by gyandevshukla** [comment]
hey @anshooarora : what you mean by  'increment strategy' . I need something similar .I am using 3.1.5 version
