### ISSUE TITLE
Why i'm getting screenshot thumbnail blank in V 4.1.1?

### ISSUE THREAD

**Issue by chetanJTH** [extent-framework/extentreports-java#119]
I just updated my extent report v 3.1.5 to 4.1.1.
Now i'm not getting screenshot perfectly on report > v4.
I'm using > ExtentSparkreporter

ScreenShot of V3.1.5
![3 1 5](https://user-images.githubusercontent.com/48850556/73248899-ce1df580-41d9-11ea-824f-7e07bff8ab99.png)

ScreenShot of V4.1.1
![4 1 1](https://user-images.githubusercontent.com/48850556/73248972-f3126880-41d9-11ea-8705-7e1e7c0286d4.png)

I need to click each screenshot to check images.

code for capturing image as below

```
public static String Screenshot(String imageName)  {
        try {
            File scrFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
            String pathName = Utils.createDir(Utils.getReportDir() + "/Images");
            File Dest = new File(pathName, System.currentTimeMillis() + ".png");
            FileUtils.copyFile(scrFile, Dest);
            String[] relativePath = Dest.toString().split("reports");
            screenshotPath = "../" + relativePath[1];
        } catch (IOException e) {
            e.printStackTrace();
        }
        return screenshotPath;
    }

```
code for add image in log

```
public static void captureScreenShot(){
        String screenShotPath = Screenshot("");
        try {
            test.addScreenCaptureFromPath(screenShotPath);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

help to resolve issue.

**Comment by anshooarora** [comment]
Does the screenshot not open when you click the 0KB thumbnail?

**Comment by chetanJTH** [comment]
@anshooarora : yes it open when i click that 0kb thumbnail.

**Comment by anshooarora** [comment]
Yes..  that's how Spark shows the image as of now.  I will change it to show the image instead of the thumbnail in the next release.

**Comment by chetanJTH** [comment]
@anshooarora : thanks for response. let this ticket open so i can get notification when you update this change.

**Comment by chetanJTH** [comment]
@anshooarora : how i can resolve my issue?

**Comment by chetanJTH** [comment]
@anshooarora : still it doesn't feet so well, smaller and vertical list of thumbnail.
![report](https://user-images.githubusercontent.com/48850556/74509145-ce7ef600-4f26-11ea-8f53-1cc97d4e17f3.png)
