### ISSUE TITLE
Pie chart in Extent report doesn't show test failure of Cucumber Feature correctly

### ISSUE THREAD

**Issue by FrankBergemann** [extent-framework/extentreports-java#121]
I created automated Selenium tests with Java 11, Selenium, Cucumber an ExtentReport 4.1.1, see pom.xml. I created 1 single feature file containing 2 scenarios and used the HTML-3-version of ExtentReport interface. The test result of the feature has been 1 scenario paasing, the other failing. The text section of the Extent report page properly shows the Feature to fail, but the pie chart above incorrectly displays the feature as passed (all freen colour), see screenshot.
Can someone help? Please let me know if you need futher information.
-- Frank Bergemann
P.S. The fact I'm using Java 11 instead of Java 8, shouldn't matter in my point of view.

![2020-02-01_17h48_05](https://user-images.githubusercontent.com/54316676/73595865-66d7ac80-451d-11ea-8409-6460225b762a.png)

![pom.xml.txt](https://github.com/extent-framework/extentreports-java/files/4142817/pom.xml.txt)

**Comment by anshooarora** [comment]
@FrankBergemann Will look into this. Can you check if the SparkReporter has the same issue? That is the default version 4 reporter.

**Comment by FrankBergemann** [comment]
@anshooarora : I checked with the SparkReporter. It also has similar issues: the result shown on the Tests-tab is correct but on the Dashboard-tab not, see these 2 sceenshots:

![2020-02-01_18h46_56](https://user-images.githubusercontent.com/54316676/73596575-70641300-4523-11ea-8e12-96d5012f12d3.png)

![2020-02-01_18h46_32](https://user-images.githubusercontent.com/54316676/73596581-8a055a80-4523-11ea-84ce-ce516763a1f7.png)
