### ISSUE TITLE
ExtentSparkReporter : When 1 cucumber step failed rest steps after failed step coming as Pass instead of Skip

### ISSUE THREAD

**Issue by LearningPur** [extent-framework/extentreports-java#126]
Hi @anshooarora  I have integrated ExtentSparkReporter and after the execution i found when 1 cucumber step failed rest steps after failed step coming as Pass instead of should have been SKIPPED. 

PFB screenshot of it

![Screen Shot 2020-02-13 at 3 51 22 PM](https://user-images.githubusercontent.com/57417403/74481896-1d6e5200-4e79-11ea-8e02-cc58302a1f39.png)

**Comment by anshooarora** [comment]
You are using this with the Cucumber4 adapter, correct?

**Comment by LearningPur** [comment]
Yes i do

<dependency>
      <groupId>com.aventstack</groupId>
      <artifactId>extentreports-cucumber4-adapter</artifactId>
      <version>1.0.10</version>
      <scope>compile</scope>
    </dependency>

**Comment by LearningPur** [comment]
Hi @anshooarora any update on this ?

**Comment by LearningPur** [comment]
Hi @anshooarora Any update on this ? Is that because i am using cucumber4-adapter version or it is something else ?

Thanks
Victor

**Comment by anshooarora** [comment]
This is a required fix for the adapter, closing this.

See https://github.com/extent-framework/extentreports-cucumber4-adapter/issues/47
