### ISSUE TITLE
ExtentSparkReporter : Can we default display cucumber scenarios groupped 

### ISSUE THREAD

**Issue by LearningPur** [extent-framework/extentreports-java#127]
Hi @anshooarora Can we make it default to display cucumber scenario groupped. The way it currently display it looks bulky and too much scroll involve to reach the last scenario instead if we would have groupped the scenario we could click on any and expand it.

PFB screenshot 

![Screen Shot 2020-02-13 at 3 58 39 PM](https://user-images.githubusercontent.com/57417403/74483518-46dcad00-4e7c-11ea-8b58-9440abda8cf7.png)

**Comment by LearningPur** [comment]
Hi @anshooarora Just curious to know when will this change be available in upcoming version ?

Thanks
Victor

**Comment by anshooarora** [comment]
I have made a few improvements, currently available via `4.1.4-SNAPSHOT`.  Also, what I am seeing from your snapshot is custom behavior.  Are you not using the Cucumber adapter?

**Comment by LearningPur** [comment]
Yes @anshooarora  I been using Cucumber adapter but recently have been replaced with below. Based on what you have mentioned in your comment above you made some changes to 4.1.4-SNAPSHOT version. Since i am using your library thru another third party library "Courgette-JVM" he has currently "4.1.3" version. May i know when will the 4.1.4 version you will release so i can have that guy upgrade his library with "4.1.4" version

  <dependency>
      <groupId>com.aventstack</groupId>
      <artifactId>extentreports</artifactId>
      <version>4.1.3</version>
      <scope>compile</scope>
    </dependency>

**Comment by anshooarora** [comment]
`4.1.4` has already been released.

**Comment by LearningPur** [comment]
@anshooarora  With this 4.1.4 version can grouping possible ? I mean list of scenarios how it currently display can it be grouped so user can expand only those scenario which are failed instead of looking at all other scenarios ?

Thanks
Vinit

**Comment by anshooarora** [comment]
Its be default.  But as I mentioned earlier, I am not sure how you are getting the existing according/toggle like structure for steps.  This is what I am seeing as the output from adapter:

![image](https://user-images.githubusercontent.com/4107384/79165457-04f6b700-7d98-11ea-8dc6-8b0b77f66de1.png)
