### ISSUE TITLE
Parallel test runs sometimes write over a node

### ISSUE THREAD

**Issue by casalribeiro** [extent-framework/extentreports-java#130]
Sometimes when running parallel test methods, if a node is created at the same time only one will be displayed in the report. the method `com.aventstack.extentreports.ExtentTest#createNode(java.lang.String)` is not sync like the method `com.aventstack.extentreports.ReportObservable#saveTest`

I've created the PR #129 with some changes. I've ran some dozen of tests and report came out fine with that fix.

**Comment by waterwarrior** [comment]
I had same issue when tried to use 4.1.1 version(I have lots parallel tests), unfortunately I had not enough time to find a source of this problem and resolved it via rollback to v4.0.5. We need this PR. v4.0.5 had a synchronized createNode methods

**Comment by anshooarora** [comment]
@casalribeiro @waterwarrior 

Please check with the latest build:  `4.1.5-SNAPSHOT`.
