### ISSUE TITLE
Merging two html extent Reports works but Category view gets overwritten.

### ISSUE THREAD

**Issue by rahgir** [extent-framework/extentreports-java#131]
Hi Anshoo,
I wanted to thank you for this awesome framework developed. I am using the community version 3.1.5 in my Project and quite impressed by the work done. :) 
Though, I also observe few very common issues and below is quite critical which will be really helpful if you fix at earliest.

[integration-report.zip](https://github.com/extent-framework/extentreports-java/files/4262397/integration-report.zip)

Same issue found with authors as well...

_Originally posted by @anilchander1 in https://github.com/anshooarora/extentreports-java/issues/877#issuecomment-301302709_

**Comment by anshooarora** [comment]
Version 3 is no longer supported but this feature is also available in the latest with:

https://github.com/extent-framework/extentreports-java/commit/4537cb63f74ea45dccddccc7992c714d2a3c88f8

**Comment by rahgir** [comment]
Thanks for the quick response. I upgraded to next version 4.0.9(even tried 4.1.3) which solved this porblem but now I face another problem in merging two html reports which used to work in 3.1.5 using setAppendExisting(true).  Now I am not able to find this method neither I am able to see the class 'ExtentV3HtmlReporter' in the downloaded extentreport.jar. I cannot keep single object for my whole suite. Could you please guide ? I request to provide this feature in community version 4 as well as it is very important for basic functionality.

**Comment by finndesolace** [comment]
I've also been looking for a solution for the missing setAppendExisting(true) option.
As for now i'm creating seperate reports for each run, but that doesn't result in a nice overview.
I'm considering using version 3.

**Comment by finndesolace** [comment]
I ended up using the newest version in combination with klov

**Comment by rahgir** [comment]
@anshooarora : Not sure if you got a chance to look at this issue. I am really impressed by using this great tool but quite disappointed by the versioning used to distribute the features. So, just a suggesstion.
1. Since version 3(latest 3.1.5) is no longer supported(like the test count for each modules individually under Categrories Section etc), some critical issues cannot be addressed if I still use 3.1.5
2. Now, if I upgrade to version 4 (4.0.1 till 4.1.3) I see that category issue is fixed but now I cannot merge two HTML reports which used to work in 3.1.5.
3. If setAppendExisting(true) is present in professional edition, please provide a trial version of this software so that people can showcase the power of ExtentReport in Organisations as no Organisation approves to buy the license on just theorotical basis.
4. Also, 'ExtentV3HtmlReporter' which is mentioned to work like Version 3 in Version 4 is not at all present blocking us to use setAppendExisting in Extent Report 4.
I see many people has posted the same question so many time. I request you to please continue the 'setAppendExisting' feature in Extent Report 4 Community Version as well.
Thanks !

**Comment by rahgir** [comment]
> I ended up using the newest version in combination with klov

Is it solving your need fully ?

**Comment by finndesolace** [comment]
@rahgir 
Well,
htmlreporter is deprecated in the newest version.
transition to klovreporter is easy.
The readme explicitly refers to klov, which does historical reporting.

I"m quite on my own for doing test automation.
It just needs to be freeware.

klov seems to me like jira in an earlier phase, but grown from a different perspective.

I got to a point where i wanted my tests to be consultable per "software version under test".
Seems like tags are for the Pro edition, but I found some other parameter to filter on it.

In the end, I just use this for test reporting / issue monitoring on test automation.

Depending size, type of the organization and means of the project, klov will suffice.
And it'll probably improve and grow.

For now it solves my needs for today.  But maybe not tomorrow ;)
The data is the most important.  The tools can change.

**Comment by anshooarora** [comment]
@rahgir AppendExisting is available in version 4.1.x and will be fully supported in version 5 onwards. I am in the process of migrating this code to v5.x. 

This shows what's new and what will soon be included:  https://github.com/extent-framework/extentreports-java/tree/v5.0.x

**Comment by rahgir** [comment]
Thanks @anshooarora . Appreciate you for the awesome work you are doing and active responses.
One improvement I would like to highlight you is even though the existing documentation is good and helpful, It doesn’t looks complete. The feature which  I was asking for merging is already available via Spark Reporter through JSON which I could understand only when I went through change logs multiple times.

**Comment by anshooarora** [comment]
Github wiki will be used for documentation moving forward, I madr an initial commit here: https://github.com/extent-framework/extentreports-java/wiki

This would also give everyone the ability to contribute and improve the docs as more features get added.
