### ISSUE TITLE
TestNG package execution, current test is marked as failure if @BeforeClass of next test class fails

### ISSUE THREAD

**Issue by equazi** [extent-framework/extentreports-java#133]
Extent Report Version: 4.0.9
Issue: During testng package execution, if @BeforeClass of next test class has failure then current test is marked as failure.  Is it designed to behave like this? Any help will be appreciated, thank you. Below code snipped for publishing test results to Extent Reports:

    public void afterMethodGetResults(ITestResult result) {
		switch(result.getStatus()) {
			case ITestResult.SUCCESS :
				reporter.reportStep(StepStatus.PASS, "Finish with success");
				break;
			case ITestResult.FAILURE :
				if (result.getThrowable() != null) {
					reporter.reportStep(StepStatus.FAIL, ("Failed test case", reporter.getScreenCapture());
				}
				break;
			case ITestResult.SKIP :
				if (result.getThrowable() != null) {
					reporter.reportStep(StepStatus.SKIPPED, ("Skipped test case", reporter.getScreenCapture());
				} else {
					reporter.reportStep(StepStatus.SKIPPED, "Skipped test case", reporter.getScreenCapture());
				}
				break;
			default :
				reporter.reportStep(StepStatus.ERROR, "Ignored test case", reporter.getScreenCapture());
		}
           extent.getInstance().flush();
	}

**Comment by equazi** [comment]
![ExtentIssue](https://user-images.githubusercontent.com/33493771/76317394-85665b80-62b2-11ea-86cc-cf09e84aed59.PNG)

**Comment by anshooarora** [comment]
@equazi No..  are you using the [testng adapter](https://github.com/extent-framework/extentreports-testng-adapter)?

**Comment by equazi** [comment]
Yes, I have included the listener but the result still displays same issue. When I run all tests of multiple classes in multiple packages from Jenkins, test fails if "@after class" method of previous class or "@before class" method of next class fails. As shown above screen shot.

Here are the code snippets:

@Listeners({TestResultListener.class, ExtentITestListenerClassAdapter.class})
public abstract class BaseTest {
    public static ExtentTest extentTest;

    @AfterMethod(alwaysRun = true)
    public void afterMethodGetResults(ITestResult result) throws Exception {
        try {
			String reason;
			String stackTrace;
			switch(result.getStatus()) {
			case 1:
				reporter.reportStep(StepStatus.PASS, "Finish test case [" + result.getName() + "] with success");
				break;
			case 2:
				if (result.getThrowable() != null) {
					reason = result.getThrowable().toString();
					stackTrace = reporter.getFormatStack(result.getThrowable());
					reporter.reportStep(StepStatus.FAIL, "Failed test case [" + result.getName() + "]: ", stackTrace, reporter.getScreenCapture());
				}
				break;
			case 3:
				if (result.getThrowable() != null) {
					reason = result.getThrowable().toString();
					stackTrace = reporter.getFormatStack(result.getThrowable());
					reporter.reportStep(StepStatus.SKIPPED, "Skipped test case [" + result.getName() + "]: ", stackTrace, reporter.getScreenCapture());
				} else {
					reporter.reportStep(StepStatus.SKIPPED, "Skipped test case [" + result.getName() + "] : ", stackTrace, reporter.getScreenCapture());
				}
				break;
			default:
				reporter.reportStep(StepStatus.ERROR, "Ignored test case [" + result.getName() + "] : ", reporter.getScreenCapture());
			}

            reporter.endTest();
        } catch (Exception var5) {
            reason = "Error, after test method failed";
            Log.info(reason);
            throw new Exception(reason, var5);
        }
    }
}

**Comment by anshooarora** [comment]
Would you be able to create a small project and share the repo so I can investigate?

**Comment by equazi** [comment]
Thank you for your help Anshoo.  Please find test sample code below where I have BaseTest class, reporting class and test listener class.

//---Sample code---
package com.Demo.module.report;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.MediaEntityBuilder;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import com.aventstack.extentreports.reporter.configuration.Theme;
import com.aventstack.extentreports.Status;
import com.Demo.module.common.Global;
import com.Demo.module.common.HTTPRequest;
import com.Demo.module.exception.CommonException;
import com.Demo.module.filemanagement.MDir;
import com.Demo.module.common.Log;
import com.Demo.module.testng.Browser;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;


public class Reporter {

    private static ExtentTest extentTest;
    private static ExtentReports extentReports;

    private static final String BREAK_LINE = "</br>";
    private static final String HTTP_INFO_STYLE = "<span style=\"font: bold 12px/30px Georgia, serif;margin-right:5px\" >";
    private static final String HTTP_PLAIN_STYLE = "<span style=\"font: 12px/30px Georgia, serif;margin-right:5px\" >";


    public static ExtentReports getInstance() {
        if (extentReports == null)
            createInstance();
        return extentReports;
    }

    public static ExtentReports createInstance() {
        // create report directory if doesn't exist
        createReportPath(Global.REPORT_DIR);
        // Remove old screenshots
        String scFolderPath = Global.REPORT_DIR + "sc";
        MDir.deleteDirectoryAndContent(scFolderPath);
        // Instantiate ExtentHtmlReporter
        ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter(Global.REPORT_PATH);
        htmlReporter.config().setTheme(Theme.STANDARD);
        htmlReporter.config().setDocumentTitle(Global.PROJECT_NAME);
        htmlReporter.config().setEncoding("utf-8");
        htmlReporter.config().setReportName(Global.PROJECT_NAME + " UI Test Automation Report");
        extentReports = new ExtentReports();
        extentReports.attachReporter(htmlReporter);
        return extentReports;
    }

    //Create the report path if it does not exist
    private static void createReportPath (String path) {
        File testDirectory = new File(path);
        if (!testDirectory.exists()) {
            if (testDirectory.mkdir()) {
                System.out.println("Directory: " + path + " is created!" );
            } else {
                System.out.println("Failed to create directory: " + path);
            }
        } else {
            System.out.println("Directory already exists: " + path);
        }
    }

    /**
     * Initializes extent report
     *
     * @param paramsMap
     *            :HashMap
     */
    
    public void initializeReport(Map<String, String> paramsMap) throws CommonException {
        try {
            String canonicalHostName="NA";
            String testEnvironment="";
            String appVersion="";
            String projectName="";

            // Get test environment
            if (paramsMap.containsKey("GBL_URL"))
                testEnvironment = (String) paramsMap.get("GBL_URL");

            // Get project name
            if(paramsMap.containsKey("GBL_PROJECT_NAME"))
                projectName = (String) paramsMap.get("GBL_PROJECT_NAME");

            // Get App Version
            if(paramsMap.containsKey("GBL_PROJECT_NAME")) {
                if(paramsMap.get("GBL_PROJECT_NAME").contains("Ambiance") || paramsMap.get("GBL_PROJECT_NAME").contains("Community")) {
                    if (paramsMap.containsKey("GBL_URL")) {
                        String url = paramsMap.get("GBL_URL");
                        appVersion = getAppVersion(url);
                    }
                }
            }

            //setup environment variables
            InetAddress iAddress = null;
            try {
                iAddress = InetAddress.getLocalHost();
                Log.info("Host Name: " + iAddress.getHostName()+ " Address: " + iAddress.getHostAddress());
            } catch (UnknownHostException e) {
                String message = "Failed to get local host " ;
                Log.error(message, e);
            }
            if(iAddress != null) {
                canonicalHostName = iAddress.getCanonicalHostName();
            }

            // Publish report with information
            extentReports = Reporter.createInstance();
            extentReports.setSystemInfo("Host Name", canonicalHostName);
            extentReports.setSystemInfo("Test Environment", testEnvironment);
            if(appVersion != null || !appVersion.isEmpty()) {
                extentReports.setSystemInfo("Project Name", projectName + "  version: " + appVersion);
            } else {
                extentReports.setSystemInfo("Project Name", projectName);
            }
            Log.info("Initialization of reporting success. ");
        } catch (Exception e) {
            String message = "Initialization of reporting failed: ";
            Log.error(message, e);
            throw new CommonException(message, e);
        }
    }

    
    public void addSystemInfo(String key, String value) {
        extentReports.setSystemInfo(key, value);
    }

    public synchronized ExtentTest getTest() {
        return extentTest;
    }

    public synchronized static ExtentTest startTest(String testName, String desc) {
        extentTest = extentReports.createTest(testName, desc);
        return extentTest;
    }

    
    public void endReport() {
        try {
            extentReports.flush();
            Log.info("Extent Report closed successfully.");
        } catch (Exception e) {
            Browser.quitDriver();
            String message = "Error, closing extent report.";
            Log.error(message);
        }
    }

    public synchronized void endTest() {
        try {
            this.getInstance().flush();
        } catch (Exception e) {
            Browser.quitDriver();
            String message = "Error, flushing extent report at the end of test.";
            Log.error(message);
        }
    }

    public synchronized void reportStep(String stepName, boolean... toBold) {
        boolean plain = toBold.length == 0 ? false : true;
        if(!plain) {
            if (getTest() != null)
                getTest().log(Status.INFO, HTTP_PLAIN_STYLE + stepName + "</span>");
        }else if(plain) {
            if (getTest() != null)
                getTest().log(Status.INFO, HTTP_INFO_STYLE +stepName+ "</span>");
        }
    }

    /**
     * writes the status of a step in extent report with LogStatus as INFO
     *
     * @param stepName
     *            :String
     */
    
    public void reportStep(String stepName) {
        if (getTest() != null)
            getTest().log(Status.INFO, HTTP_PLAIN_STYLE +stepName+ "</span>");
    }

    /**
     * writes the status of a step in extent report
     *
     * @param status
     *            :StepStatus
     * @param stepName
     *            :String
     */
    
    public void reportStep(StepStatus status, String stepName) {
        getTest().log(getLogStatus(status), "<span>" +stepName+ "</span>");
    }

    /**
     * Writes the status of a step in extent report
     * with detail message.
     *
     * @param status
     *            :StepStatus
     * @param stepName
     *            :String
     * @param details
     *            :String
     */
    
    public void reportStep(StepStatus status, String stepName, String details) {
        if (getTest() != null)
            getTest().log(getLogStatus(status), "<span>" +stepName + BREAK_LINE + details+ "</span>");
    }

    /**
     * Writes the status of a step in extent report
     * with message of exception.
     *
     * @param status
     *            :StepStatus
     * @param stepName
     *            :stepName
     * @param t
     *            :Throwable
     */
    
    public void reportStep(StepStatus status, String stepName, Throwable t) {
        if (getTest() != null)
            getTest().log(getLogStatus(status),
                    stepName + BREAK_LINE + t.getMessage() + BREAK_LINE + getFormatStack(t));

    }

    /**
     * writes the status of a step in extent report. Adds screenshot file to it.
     *
     * @param status
     *            :StepStatus
     * @param message
     *            : String
     * @param file
     *            : File
     */
    
    public void reportStep(StepStatus status, String message, File file) {
        if(getTest() != null){
            reportStep(status, message + getScreenShotPath(file));
        }
    }

    /**
     * writes the status of a step in extent report. Adds screenshot file to it.
     *
     * @param message
     *            :StepStatus
     * @param ex
     *            :Throwable
     */
    
    public void reportStep(String message, String ex) {
        try {
            if (getTest() != null) {
                getTest().fail(message+BREAK_LINE+ex, MediaEntityBuilder.createScreenCaptureFromPath(getLogScreenShotPath()).build());
            }
        }catch (Exception e) {
            Log.error("Error, fail to report step information."+e);
        }
    }

    /**
     * Format the stack message and return first 5 lines
     *
     *
     * @param e
     *            : Throwable object
     * @return string
     *           : String
     */
    public String getFormatStack(Throwable e) {
        StringBuilder sb = new StringBuilder();
        int nline = 1;
        if (e != null)
            for (StackTraceElement element : e.getStackTrace()) {
                if (nline <= 5 && element != null)
                    sb.append(element.toString() + "\n");
                else
                    break;
                nline++;
            }
        return sb.toString();
    }

    
    public String generateTestCaseInformation(String description, String[] groups, String packageLocation){
        String groupString = "";
        for(String g:groups){
            if (!groupString.equals(""))
                groupString = groupString + ", ";
            groupString = groupString + g;
        }
        return "<div>Groups: <span style=\"font: italic bold 12px/30px Georgia, serif;\">"
                + groupString + "</span>"
                + "</div><div>"
                + "Location: <span style=\"font: italic bold 12px/30px Georgia, serif;\">"
                + packageLocation + "</span>"
                + "</div>"
                + "Description: " + description;
    }

    
    public File getScreenCapture() {
        TakesScreenshot ts = (TakesScreenshot) Browser.getDriver();
        File file = ts.getScreenshotAs(OutputType.FILE);
        return file;
    }

    
    public String getScreenShotPath(File file) {
        String htmlTagPath = "";
        String imagePath = "";
        if (file != null) {
            try {
                String SCREEN_SHOT = new SimpleDateFormat("HHmmssSSS").format(new Date());
                String imageName = SCREEN_SHOT + ".png";
                imagePath = Global.REPORT_DIR + "sc/" + imageName;
                FileUtils.copyFile(file, new File(imagePath));
                if(Global.REMOTE_EXECUTION) {
                    if(System.getenv("REPORT_IMG") != null && !System.getenv("REPORT_IMG").isEmpty()) {
                        imagePath = System.getenv("REPORT_IMG");
                        imagePath = imagePath.replace('\\', '/') + imageName;
                    }else {
                        String errMsg = "Error, missing Jenkins global variable: REPORT_IMG=$BUILD_URL/HTML_20Report/sc/";
                        throw new CommonException(errMsg); // Add Global variable REPORT_IMG = $BUILD_URL/HTML_20Report/sc/
                    }
                }
                htmlTagPath = "</br>" + getTest().addScreenCaptureFromPath(imagePath);
            } catch (IOException e) {
                String errMsg = "Error, failed to copy file";
                Log.error(errMsg, e);
            } catch (CommonException e) {
                e.printStackTrace();
            }
        } else {
            String errMsg = " Fail: Screenshot file is null, cannot add screenshot";
            Log.error(errMsg);
        }
        return htmlTagPath;
    }

    
    public String getLogScreenShotPath() {
        String htmlTagPath = "";
        String imagePath = "";
            try {
                String SCREEN_SHOT = new SimpleDateFormat("HHmmssSSS").format(new Date());
                String imageName = SCREEN_SHOT + ".png";
                imagePath = Global.REPORT_DIR + "sc/" + imageName;
                File file = getScreenCapture();
                if(file != null) {
                    FileUtils.copyFile(file, new File(imagePath));
                }
                if(Global.REMOTE_EXECUTION) {
                    if(System.getenv("REPORT_IMG") != null && !System.getenv("REPORT_IMG").isEmpty()) {
                        imagePath = System.getenv("REPORT_IMG");
                        imagePath = imagePath.replace('\\', '/') + imageName;
                    }else {
                        String errMsg = "Error, missing Jenkins global variable: REPORT_IMG=$BUILD_URL/HTML_20Report/sc/";
                        throw new CommonException(errMsg); // Add Global variable REPORT_IMG = $BUILD_URL/HTML_20Report/sc/
                    }
                }
                htmlTagPath = imagePath;
            } catch (CommonException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
        return htmlTagPath;
    }

    /**
     * Return corresponding ExtentReport LogStatus for incoming StepStatus
     *
     * @param status
     *            : StepStatus
     * @return status
     * 				: LogStatus
     */
    public Status getLogStatus(StepStatus status) {
        switch (status) {
            case PASS:
                return Status.PASS;
            case FAIL:
                return Status.FAIL;
            case ERROR:
                return Status.ERROR;
            case SKIPPED:
                return Status.SKIP;
            default:
                return Status.INFO;
        }
    }
}

//------------------------------
package com.Demo.module.listeners;

import com.Demo.module.common.Log;
import com.Demo.module.report.Reporter;
import com.Demo.module.report.StepStatus;
import com.Demo.module.testng.BaseTest;
import org.testng.*;
import org.testng.annotations.ITestAnnotation;

import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.Set;


public class TestResultListener implements ITestListener, IAnnotationTransformer {

    private static Reporter reporter = new Reporter();

    @Override
    public synchronized void onStart(ITestContext context) {
        String groupToTest = System.getenv("GROUP_TO_TEST");
        if (groupToTest!= null){
            System.out.println("+========= Executing Group =========");
            System.out.println(String.format("             %s           ", groupToTest));
            System.out.println("+===================================");
        }
    }

    @Override
    public synchronized void onFinish(ITestContext context) {
        /**
         * Won't implement
         */
    }

	@Override
	public synchronized void onTestStart(ITestResult result) {
        Log.info("==============================================");
        Log.info("Started test: "+result.getName());
        Log.info("==============================================");
	}

	@Override
	public synchronized void onTestSuccess(ITestResult result) {
        /**
         * Won't implement
         */
    }

	@Override
	public synchronized void onTestFailure(ITestResult result){
        /**
         * Won't implement
         */
	}

	@Override
	public synchronized void onTestSkipped(ITestResult result) {
        TestRetryAnalyzer retryAnalyzer = new TestRetryAnalyzer();
        if (retryAnalyzer.isRetryable()) {
            reporter.getInstance().removeTest(BaseTest.extentTest);
        }
	}

    @Override
    public void onTestFailedButWithinSuccessPercentage(ITestResult result) {
        /**
         * Won't implement
         */
    }

    @Override
    public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) {
        IRetryAnalyzer retry = annotation.getRetryAnalyzer();
        if (retry == null) {
            annotation.setRetryAnalyzer(TestRetryAnalyzer.class);
        }
    }
}

//-----------------------------------------------
public enum StepStatus {
    INFO,
    PASS,
    FAIL,
    ERROR,
    SKIPPED
}

//-----------------------------------------------------
package com.Demo.module.testng;

import com.aventstack.extentreports.testng.listener.ExtentITestListenerClassAdapter;
import com.aventstack.extentreports.ExtentTest;
import com.Demo.module.exception.CommonException;
import com.Demo.module.common.Global;
import com.Demo.module.common.Log;
import com.Demo.module.listeners.TestConfigurationListener;
import com.Demo.module.listeners.TestResultListener;
import com.Demo.module.report.StepStatus;
import com.Demo.module.xml.Reader;
import org.openqa.selenium.Capabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.annotations.*;
import com.Demo.module.report.Reporter;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Map;


@Listeners({TestResultListener.class, ExtentITestListenerClassAdapter.class})
public abstract class BaseTest {

    public static ExtentTest extentTest;
    public static Reporter reporter = new Reporter();

    @BeforeSuite(alwaysRun = true)
    public void beforeSuite(ITestContext context) throws CommonException {
        try {
				Map<String,String> params = Reader.readTestngFile(Global.TESTNG_FILE);
				reporter.initializeReport(params);
				Capabilities options = ((RemoteWebDriver) Browser.getDriver()).getCapabilities();
        } catch (Exception e) {
            Browser.quitDriver();
            String errorMsg = "Error, execution before suite fail. Enter BROWSER_VERSION matching with current chrome browser";
            Log.info(errorMsg);
            throw new CommonException(errorMsg,e);
        }
    }

    @BeforeMethod(alwaysRun = true)
    public void beforeMethodBaseTest(Method m, Object[] data) throws CommonException {
        String description ="";
        try {
            if(data.length > 0) {
                description = m.getAnnotation(Test.class).description() + " ["+ data[0] + "]";
            }else {
                description = m.getAnnotation(Test.class).description();
            }
            Log.info("Start test case [" + m.getName() + "]");
            extentTest = reporter.startTest(m.getName(),
                            reporter.generateTestCaseInformation(description,
                            m.getAnnotation(Test.class).groups(),
                            m.getDeclaringClass().toString()));
        } catch (Exception e) {
            String errorMsg ="Error, execute before test method fails";
            Log.info(errorMsg);
            throw new CommonException(errorMsg, e);
        }
    }

@AfterMethod(alwaysRun = true)
public void afterMethodGetResults(ITestResult result) throws Exception {
    try {
		String reason;
		String stackTrace;
		switch(result.getStatus()) {
		case 1:
			reporter.reportStep(StepStatus.PASS, "Finish test case [" + result.getName() + "] with success");
			break;
		case 2:
			if (result.getThrowable() != null) {
				reason = result.getThrowable().toString();
				stackTrace = reporter.getFormatStack(result.getThrowable());
				reporter.reportStep(StepStatus.FAIL, "Failed test case [" + result.getName() + "]: ", stackTrace, reporter.getScreenCapture());
			}
			break;
		case 3:
			if (result.getThrowable() != null) {
				reason = result.getThrowable().toString();
				stackTrace = reporter.getFormatStack(result.getThrowable());
				reporter.reportStep(StepStatus.SKIPPED, "Skipped test case [" + result.getName() + "]: ", stackTrace, reporter.getScreenCapture());
			} else {
				reporter.reportStep(StepStatus.SKIPPED, "Skipped test case [" + result.getName() + "] : ", stackTrace, reporter.getScreenCapture());
			}
			break;
		default:
			reporter.reportStep(StepStatus.ERROR, "Ignored test case [" + result.getName() + "] : ", reporter.getScreenCapture());
		}

        reporter.endTest();
    } catch (Exception var5) {
        reason = "Error, after test method failed";
        Log.info(reason);
        throw new Exception(reason, var5);
    }
}

    @AfterClass(alwaysRun = true)
    public void afterClassBaseTest() throws CommonException {
        try {
            Browser.quitDriver();
			Browser.sleep(5000);
        } catch (Exception e) {
            Browser.quitDriver();
            String errorMsg = "Error, execution of after class failed";
            Log.info(errorMsg);
            throw new CommonException(errorMsg, e);
        }
    }

    @AfterSuite(alwaysRun=true)
    public void afterSuite(ITestContext context){
        try {
            if (context.getAllTestMethods().length > 0) {
                reporter.endReport();
                Browser.quitDriver();
            } else {
                Log.info("No test was found.");
                reporter.endReport();
                Browser.quitDriver();
            }
        }catch (Exception e){
            Log.error("Exceptions thrown during execution: ", e);
            Browser.quitDriver();
        }
    }
}

**Comment by anshooarora** [comment]
@equazi Please create a repository with your project,  its easier to clone and push any changes if required.
