### ISSUE TITLE
Not able to update the status of Test using getModel().setStatus(Status.PASS)

### ISSUE THREAD

**Issue by rshidling** [extent-framework/extentreports-java#134]
I am trying the below code to update the status of parent test based on the status child node of test as below.
```
if (childTest.getStatus().toString().equalsIgnoreCase("Pass")) {
	System.out.println(parentTest.getStatus().toString());
	parentTest.getModel().setStatus(Status.PASS);
	System.out.println(parentTest.getStatus().toString());
	report.flush();
} else {
	parentTest.getModel().setStatus(Status.FAIL);
	report.flush();
}
System.out.println("After Flush :: " + parentTest.getStatus().toString());

```

The console ouput is as below.

```
fail
pass
After Flush :: fail
```
After flush the status of parent test is not updated.
ExtentReport jar : extentreports-4.0.9.jar

![ExtentTestReport](https://user-images.githubusercontent.com/8448089/76882231-5d718c00-68a0-11ea-9c9f-ce0a8b9c70df.jpg)

**Comment by anshooarora** [comment]
@rshidling It is still marked as fail as there 2 steps in FAIL status.  Even if you override the status, if there are any failing events, the final status would still be FAIL.  This will change if you override each event status to PASS.
