### ISSUE TITLE
Unable to interact with the generated extent report. Error in Chrome Console:  extent.js:2 Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by lorena-iancu** [extent-framework/extentreports-java#137]
I am using extent report version 4.0.0
This is the maven dependency that I am using:
<dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>4.0.0</version>
        </dependency>

And I am creating an instance of  ExtentHtmlReporter.

I am not able to interact with the generated HTML report anymore.
Error from Chrome Console: extent.js:2 Uncaught SyntaxError: Unexpected end of input

**Comment by anshooarora** [comment]
@lorena-iancu You may be adding some events or logs that are breaking the markup.  Please check what you have logged, the following 2 tags `<` or `>` if used incorrectly would break your HTML.
