### ISSUE TITLE
Expand/collapse issue with screenshots added using addScreenCaptureFromPath().

### ISSUE THREAD

**Issue by akshayamaldhure** [extent-framework/extentreports-java#141]
For the screenshots added using the `addScreenCaptureFromPath()` method, I see that expanding or collapsing the screenshot by clicking on the `message` text does not work unless I come back to the test from some other test.

For example, let's assume I have two tests `verifyTest1()` and `verifyTest2()`. I have called `addScreenCaptureFromPath("path/to/screenshot", "log message")` in my `verifyTest1()`. In the report, if I click on the `log message` link in `verifyTest1()`, nothing happens. I need to click on `verifyTest2()` in the report and then back on `verifyTest1()` to see the screenshot expanded. Similar observation for collapsing the screenshot.

**Comment by anshooarora** [comment]
Please share a sample report.  I do not see this behavior on my end.

**Comment by akshayamaldhure** [comment]
For some reason, I'm unable to replicate this at my end now.
