### ISSUE TITLE
long node text corrupts the report

### ISSUE THREAD

**Issue by mmajcherczyk** [extent-framework/extentreports-java#143]
v.4.1.4
<img width="1680" alt="Zrzut ekranu 2020-04-13 o 19 46 51" src="https://user-images.githubusercontent.com/6592592/79145294-b14c9380-7dc0-11ea-9a6d-a5d6accdc950.png">

**Comment by shrutikhungar** [comment]
@anshooarora 

I still see this issue when i enter some text bigger than than the screensize. Is this fixed?
extentReport.pass(MarkupHelper.createLabel("Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font Test font ", ExtentColor.AMBER));

**Comment by shrutikhungar** [comment]
![image](https://user-images.githubusercontent.com/37937699/80286969-40a46000-874c-11ea-8637-22b21df14094.png)

**Comment by anshooarora** [comment]
These 2 issues are unrelated.

You have used a badge with a sentence causing the layout to break.  Generally badges are used for small text elements as also shown here https://getbootstrap.com/docs/4.4/components/badge/.

> Documentation and examples for badges, our small count and labeling component.

A quick fix is to use the below css:

```css
.detail-body .badge {
    max-width: 75%;
    overflow-x: auto;
}
```

Note: the above will result in an ugly scrollbar to appear.

**Comment by shrutikhungar** [comment]
Thanks I will try this. Meanwhile, could you also help me whether color text can be introduced in CreateTable(data)?
![image](https://user-images.githubusercontent.com/37937699/80315738-22effd00-8817-11ea-94ca-135e9f958131.png)

**Comment by mmajcherczyk** [comment]
problem still exists  
<img width="1676" alt="obraz" src="https://user-images.githubusercontent.com/6592592/86106305-b0bec180-bac0-11ea-8d06-a958c1557cec.png">

version 4.1.7

**Comment by anshooarora** [comment]
This is fixed in version `5.0.0-SNAPSHOT`. 

4.1.x - will update soon.

**Comment by anshooarora** [comment]
Note: this is a CSS fix:

```
.node { max-width: 90%; }
```

which can be done in the interim via `config`.

**Comment by mmajcherczyk** [comment]
`htmlReporter.config().setCSS(".node {width: 90%;}");`
don't work

but 
`htmlReporter.config().setJS("var elems = document.querySelectorAll('.node');" +
                                    "var index = 0, length = elems.length;" +
                                    "for ( ; index < length; index++) {" +
                                    "elems[index].style.width = '90%';}");`
works correctly

thx

**Comment by anshooarora** [comment]
Release `5.0` is now available and contains this fix.

**Comment by mchundi** [comment]
is this issue fixed for ExtentSparkReporter too. I am using 5.0.1 and I see the text going out of the frame
<img width="1340" alt="Screen Shot 2020-08-10 at 13 07 13" src="https://user-images.githubusercontent.com/12151944/89826147-9f7ac300-db0a-11ea-90a8-ba96ee145441.png">

**Comment by anshooarora** [comment]
@mchundi Please see my reply [here](https://github.com/extent-framework/extentreports-java/issues/143#issuecomment-619467898).
