### ISSUE TITLE
Can we assign the test status manually basically (in progress)

### ISSUE THREAD

**Issue by AdarshBP** [extent-framework/extentreports-java#146]
Hi @anshooarora can we assign the test status as PENDING or INPROGRESS at @beforemethod and later assign as pass or fail in @aftermethod.

The issue is when I do parallel testing and give extent.flush () , it adds the logs of the test case which is not yet completed by other threads  but the status of that test case will be PASS by default.

**Comment by anshooarora** [comment]
@AdarshBP This is not possible.. Each time you call flush,  the most up-to-date status for each test will be computed and applied to the template.  All tests are passed until an event occurs resulting in a change of status. 

However, you can reduce the number of times you call flush() and only do it once after your entire session is complete.
