### ISSUE TITLE
 MarkupHelper.createCodeBlock(json,CodeLanguage.JSON); is not displaying json properly

### ISSUE THREAD

**Issue by vijayatmauto** [extent-framework/extentreports-java#147]
I have used the code from the official website.
http://extentreports.com/docs/versions/4/java/#markup-helpers-codeblock

`String json = "{'foo' : 'bar', 'foos' : ['b','a','r'], 'bar' : {'foo':'bar', 'bar':false,'foobar':1234}}";
		Markup m1 = MarkupHelper.createCodeBlock(json,CodeLanguage.JSON);
		testextent.pass(m1);`

The report generated using this code is not displaying properly. 
Please find the screenshot
![Screenshot (159)](https://user-images.githubusercontent.com/63591694/79779146-841b5a80-8357-11ea-81f6-3ec295eec61c.png)

**Comment by anshooarora** [comment]
API version and reporter used?

**Comment by vijayatmauto** [comment]
API > extentreports 4.1.5
Reporter > ExtentHtmlReporter.

**Comment by anshooarora** [comment]
HtmlReporter is deprecated, please use ExtentSparkReporter.

**Comment by vijayatmauto** [comment]
Thank you, I will check ExtentSparkReporter

**Comment by vijayatmauto** [comment]
Hi Anshoo, Thanks for your quick response before. 
As you suggested, I have used ExtentSparkReporter to generate the report. But I still face the same issue.

Report config > 
`ExtentSparkReporter sparkReporter = new ExtentSparkReporter(reportPath);
sparkReporter.config().setDocumentTitle("Sample Automation");
sparkReporter.config().setReportName("Automation Run");
sparkReporter.config().setTheme(Theme.DARK);
sparkReporter.config().setEncoding("utf-8");		
extent = new ExtentReports();
extent.attachReporter(sparkReporter);`

Test > 
`testextent = extent.createTest("Code");
String json = "{'foo' : 'bar', 'foos' : ['b','a','r'], 'bar' : {'foo':'bar', 'bar':false,'foobar':1234}}";
testextent.pass(MarkupHelper.createCodeBlock(json, CodeLanguage.JSON));
testextent.log(Status.INFO,MarkupHelper.createCodeBlock(json, CodeLanguage.JSON) );`

Have attached the screenshot of the report.


![Screenshot (163)](https://user-images.githubusercontent.com/63591694/79875614-850bc500-8407-11ea-9f98-26be51e18b2e.png)

**Comment by anshooarora** [comment]
This is fixed in 5.0.0-SNAPSHOT.

However, not all features are available yet. More here: https://github.com/extent-framework/extentreports-java/tree/v5.0.x?files=1
