### ISSUE TITLE
setAppend version 4.1.5

### ISSUE THREAD

**Issue by arquimedesjr** [extent-framework/extentreports-java#148]
How do I setAppent (true) in version 4.1.5? Because I want to make several executions through .jar and I just want it to have an html.

**Comment by anshooarora** [comment]
In the latest, you can use `JsonFormatter`: https://github.com/extent-framework/extentreports-java/blob/master/CHANGELOG.md#improvements-3

Still an experimental feature though, an open defect:  https://github.com/extent-framework/extentreports-java/issues/161
