### ISSUE TITLE
Skipped count is not displaying in authors tag and category tag

### ISSUE THREAD

**Issue by qatestingravi** [extent-framework/extentreports-java#149]
I found below issue in Dashboard is this expected or a defect?

Steps to reproduce:
1. Run any test case which results to skipped

Expected:
Skipped test case count should be displayed under others section in authors tag and category tag
Note: Skipped count is displaying correctly in tests and event logs section

Actual:
Skipped test cases count is not displaying under others section in authors tag and category tag
<img width="931" alt="extentreport-skipped-test-not-dispalyaing" src="https://user-images.githubusercontent.com/38858602/80283046-8eac6a00-8732-11ea-8479-85dd3f7c9fda.png">

**Comment by anshooarora** [comment]
Version?

**Comment by qatestingravi** [comment]
I have used following versions,
1. testng - 6.14.3
2. Selenium java -  3.141.59
3. extentreports  - 4.1.5
4. Java 1.8 version
8. Chrome version 81

**Comment by qatestingravi** [comment]
@anshooarora Is there any update on this?
