### ISSUE TITLE
Unable to view Author section on dashboard

### ISSUE THREAD

**Issue by hbansal32** [extent-framework/extentreports-java#152]
I hav enabled Author's view in config file and report is showing author's view in left navigation list. But author section is not showing in dashboard. PFB screenshot.

![image](https://user-images.githubusercontent.com/56592467/80448128-ea484480-8938-11ea-8f70-7954daeca5b6.png)

I am using the version : 4.0.9
It was mentioned in [https://github.com/anshooarora/extentreports-java/pull/850](url) that, author view will work same as category view.

Can you suggest what I am missing?

`@Test(groups = {"t: smoke","a: himanshu"})
	public void AdminTest() {
		Assertion.sAssertTrue(true, "detail 4");
	}
`

**Comment by hbansal32** [comment]
I can see in v3-html-dashboard-view.ftl file that authors section is missing, 

![image](https://user-images.githubusercontent.com/56592467/80448757-ef0df800-893a-11ea-8102-7d758bab459f.png)

**Comment by hbansal32** [comment]
Can someone update on this ticket?

**Comment by anshooarora** [comment]
@hbansal32 Author's views are unavailable currently in all community reporters.  Raising enhancement to add them conditionally, to maintain the current behavior.

**Comment by anshooarora** [comment]
This feature is now included starting v5.0.0-SNAPSHOT.
