### ISSUE TITLE
Unable to view devices on left-nav and dashboard

### ISSUE THREAD

**Issue by hbansal32** [extent-framework/extentreports-java#153]
Unable to view devices on left-nav and dashboard, even I had assigned the device to my test.

Version: 4.0.9

`@Test(groups = {"d: chrome","a: himanshu"})
	public void AdminTest() {
		Assert.AssertTrue(true, "detail 4");
	}
`
![image](https://user-images.githubusercontent.com/56592467/80449153-fe417580-893b-11ea-9be7-3cb592582a02.png)

**Comment by hbansal32** [comment]
Can someone update on this ticket?

**Comment by anshooarora** [comment]
This is the same issue as your other ticket regarding authors - devices/authors are currently unavailable.  Marking as enhancement.

**Comment by hbansal32** [comment]
Hi @anshooarora , As authors are available in the left-navigation bar, devices are not available (left arrow). Where can I see devices list if not here ? 
How this can be sorted out?

**Comment by anshooarora** [comment]
This feature is now included starting v5.0.0-SNAPSHOT.
