### ISSUE TITLE
How to log test steps when using TestNG and POM? 

### ISSUE THREAD

**Issue by QAthulhu** [extent-framework/extentreports-java#154]
I'm trying to implement reporting to my test automation. I've succeeded in creating a report that shows my test results and takes a screenshot on failure, however, I would like to be able to generate a report that also logs the test steps.

I'm using a custom ExtentManager where I set up my SparkReporter. I call this class using an ExtentTestManager class which I just copied from extentreports-testng-adapter. Finally I have an ITestListener which I also based off of the one in extentreports-testng-adapter. I also have a custom Log class that uses slf4j-log4j2 which I call within my PageObjects when doing various actions.

To add the test steps to my reports, I decided to modify the Log.info() method to include a call to ExtentTestManager.log(). This way whenever my page objects use info(), it will also be added to the ExtentReport. However, upon running the tests, I received a NullPointerException because of the calls to Log.info() in the BeforeMethod of my tests. The Listener creates the test onTestStart(), which is the @Test method; meaning that when Log.info() tries to call ExtentTestManager.log(), it received an exception because no tests have been started.

Since I'm using POM, my test classes will contain similar actions among them, which I then put in my @BeforeMethod. This approach to test design is a part of the framework so I would prefer to keep; it also helps make the tests look relatively short.

Any possible workarounds for this? Is there a way to trigger the test creation during BeforeMethod?

**Comment by gorbysbm** [comment]
You should be creating the initial reporter in the @BeforeSuite method then it will be available at any step down the line

**Comment by QAthulhu** [comment]
The reporter is being created as part of the ITestListener, and the class doesn't have any methods to have it trigger on @BeforeSuite sadly

**Comment by gorbysbm** [comment]
Try creating a base class that does the set up and have your Test classes extend it.  In the base class add a method similar to this:
```
@BeforeSuite(alwaysRun = true)
	public void beforeSuite(ITestContext ctx) throws Exception {
		ctx.getSuite().getXmlSuite().setName(ctx.getSuite().getName()
				+" :: "+ StringUtilities.getFormattedDate(ctx.getStartDate().getTime(),"yyyy-MM-dd HH:mm:ss z"));
		/*********** Init Html reporter *************************/
		FilePaths.initReportFolder();
		HtmlReporter.setReporter(FilePaths.getReportFilePath(), AnalysisStrategy.CLASS, ctx);

	}
```
