### ISSUE TITLE
Cannot copy text -- reloads to a blank page

### ISSUE THREAD

**Issue by gorbysbm** [extent-framework/extentreports-java#155]
Basically The same steps as this bug: https://github.com/anshooarora/extentreports-java/issues/886
Select some text and try to copy it (Cmd +C) on Chrome  81 OSX 10.13.6

Actual result: page reloads and shows a blank page

**Comment by anshooarora** [comment]
Version?  Reporter?

**Comment by gorbysbm** [comment]
<version>4.1.5</version>
ExtentSparkReporter
