### ISSUE TITLE
Step wise test.log() not captured in extent report during parallel execution

### ISSUE THREAD

**Issue by Shantha93** [extent-framework/extentreports-java#156]
I  am using Extent 4.1.5 and have handled the reporter in thread safe way. This is a selenium testng based framework for automation. 
The parallel execution when triggered with testng is triggering a extent report with all @test methods logged correctly in the extent report. However some of the test.log() steps to be present inside the @test in extent report are not there, randomly
. This is predominantly happening with parallel execution when each thread runs more than 100 @test methods(testcases).
This is a blocker due to which we r unbale to perform parallel execution with extent in our framework. Please help me find a resolution on this, so all steps r logged properly.

**Comment by Shantha93** [comment]
Any insights on this will very helpful, as i am completely blocked on this issue! @anshooarora

**Comment by praveendvd** [comment]
> Any insights on this will very helpful, as i am completely blocked on this issue! @anshooarora
is your "test" variable thread safe ?

**Comment by anshooarora** [comment]
@Shantha93 can you share the ExtentReports code? Are you using it in a thread-safe manner though?

See here for a [similar issue](https://github.com/extent-framework/extentreports-java/issues/88).
