### ISSUE TITLE
Is "TestRunner Logs" tab removed for ExtentSparkReporter?

### ISSUE THREAD

**Issue by skunti** [extent-framework/extentreports-java#157]
Hi,

First of all thank you for the great product and helping the community. 

Recently we migrated from 

- version 4.0.9 to 4.1.5
- ExtentHtmlReporter  to ExtentSparkReporter

But after the migration, we are not seeing the **TestRunner Logs** in the extent report. Is it removed from the new version? How to add the console log to the extent report?

Thanks,
Shyam

<img width="175" alt="Screen Shot 2020-05-08 at 2 05 31 AM" src="https://user-images.githubusercontent.com/1689453/81390509-6f1d2600-90d0-11ea-86c4-a1a7d727d751.png">

**Comment by anshooarora** [comment]
This feature is now included starting v5.0.0-SNAPSHOT.
