### ISSUE TITLE
Cannot find in Versions > 4.0 ? method setAppendExisting(boolean)

### ISSUE THREAD

**Issue by awang101** [extent-framework/extentreports-java#158]
Hi,

We have a suite that runs multiple <packages> under the same <test> in our testNG ENV. For older versions we had the opportunity to append a html reporter using setAppendExisting, what is the process of appending multiple <tests> with multiple packages?

Thank you

**Comment by anshooarora** [comment]
You can use the experimental `JsonFormatter` as shown [here](https://github.com/extent-framework/extentreports-java/blob/207fa2384fedb7b041505486802b606d09041512/CHANGELOG.md#410).
