### ISSUE TITLE
Merging ExtentSpark 4.1.5 Reports causing the existing base64 image removed

### ISSUE THREAD

**Issue by rahgir** [extent-framework/extentreports-java#161]
Hi ,

I am using ExtentSparkReporter Version: 4.1.5 along with JsonFormatter , but when I execute my same failed test twice, I see that the base64 image which was attached for the first run gets removed automatically (Attaching the report for your reference 
[Index.zip](https://github.com/extent-framework/extentreports-java/files/4640610/Index.zip)

).

Could you please help ?

Regards,
Rahul

**Comment by chik145** [comment]
Hi @anshooarora 
in 4.1.5 ExtentHtmlReporter is depricated. what shall we use in this updated version ?

**Comment by awang101** [comment]
@chik145 You should use Spark Reporter, the UI has been updated and looks great http://extentreports.com/docs/versions/4/java/spark-reporter.html
