### ISSUE TITLE
Minor Issue While Table Creation

### ISSUE THREAD

**Issue by chik145** [extent-framework/extentreports-java#164]
Hi @anshooarora 
As you can see in the screenshot: "Validation" And "Expected"

These texts are not coming in one line. 
if you can fix this then it will be good. 

![image](https://user-images.githubusercontent.com/26041357/82674604-31d49e80-9c61-11ea-9bc4-09b998233c52.png)

Thanks

**Comment by anshooarora** [comment]
Can you share the code? It seems the array isnt created cortectly.

**Comment by anshooarora** [comment]
Starting version 5, you can now create tables like mentioned here:  https://github.com/extent-framework/extentreports-java/tree/v5.0.x#whats-new

I am closing this for now, please feel free to reopen it in case you are still having this issue.
