### ISSUE TITLE
Issue in DashBoard display for Tes "Steps"

### ISSUE THREAD

**Issue by subhaKiruba** [extent-framework/extentreports-java#165]
![image](https://user-images.githubusercontent.com/33080037/82910538-5e055d80-9f88-11ea-8137-1e6d1218fd59.png)

In the above screen shot u can see the status as "5 steps passed"
"1 scenario failed" = this should be "1 step failed"
this error was introduced in package 4.1.0 and it is in 4.1.5 as well.

Bug in fileName : v3-html-test-view-charts.ftl

Highlighting the error - line#54 in the file

<div class='col ${ sizeLarge } np-h'>
            <div class='card-panel nm-v'>
                <div class='left panel-name'>${ grandChildViewChartsHeading }</div>
                <div class='chart-box' style="max-height:${chartBoxHeight}px;">
                    <canvas id='grandchild-analysis' width='${chartWidth}' height='${chartHeight}'></canvas>
                </div>
                <div class='block text-small'>
                    <span class='tooltipped' data-position='top' data-tooltip='${report.reportStatusStats.grandChildPercentagePass}%'><span class='strong'>${ report.reportStatusStats.grandChildCountPass }</span> ${grandChildLabel} passed</span>
                </div>
                <div class='block text-small'>
                    <span class='strong tooltipped' data-position='top' data-tooltip='${report.reportStatusStats.grandChildPercentageFail}%'>${ report.reportStatusStats.grandChildCountFail + report.reportStatusStats.grandChildCountFatal }</span> **${childLabel}** failed, 
                    <span class='strong tooltipped' data-position='top' data-tooltip='${report.reportStatusStats.grandChildPercentageSkip}%'>${report.reportStatusStats.grandChildCountSkip}</span> skipped, 
                    <span class='strong tooltipped' data-position='top' data-tooltip='${report.reportStatusStats.grandChildPercentageOthers}%'>${ report.reportStatusStats.grandChildCountError + report.reportStatusStats.grandChildCountWarning + report.reportStatusStats.grandChildCountInfo }</span> others
                </div>
            </div>

**Comment by anshooarora** [comment]
Please use `ExtentSparkReporter`, `ExtentHtmlReporter` is deprecated.

**Comment by subhaKiruba** [comment]
Thanks
