### ISSUE TITLE
Clicking Extent Logo on top-left navigating to 404 error page in case using customized name for report instead of index.html

### ISSUE THREAD

**Issue by smaity91** [extent-framework/extentreports-java#167]
This is happening probably because the base code is written using index.html.  The logo link is static and referring to index.html which causes the error when report file name is customized.

**Comment by smaity91** [comment]
Also wanted to know if there is any toggle theme(DARK<->STANDARD) button present in v4.x? Otherwise my suggestion will be using this Extent logo to do the same as I don't see any other feature of this like navigating link to same report!

**Comment by anshooarora** [comment]
To toggle theme, hit the "L" key.

**Comment by smaity91** [comment]
@anshooarora Yes the toggle theme I got later. Thanks for confirming though.

Are you fixing the logo link issue? Not something severe but good if fixed.
