### ISSUE TITLE
Link to navigate to a specific Test on Tests tab from Tags or Exception tab is not present in ExtentSparkReporter of Extent Report 4

### ISSUE THREAD

**Issue by smaity91** [extent-framework/extentreports-java#168]
Previously the links were present for v3 HTMLReporter. Now after upgrading to 4.1.5 and changing to SparkReporter(as HTMLReporter is deprecated); the links are not coming. Below adding the link for your sample report only where you can see the same thing:

http://extentreports.com/docs/versions/4/java/files/spark/index.html

**Comment by smaity91** [comment]
@anshooarora is there any chance to prioritize this as the same feature was available in Extent Report v2 and v3? It's hugely beneficial to navigate from Category and Exception tab to Test tab and see details of any test. It's kind of missing an already available important feature.

**Comment by anshooarora** [comment]
This feature is now available starting version 5.0.0-SNAPSHOT onwards.
