### ISSUE TITLE
Shortcuts not working :: SparkReporter Extent Report v4

### ISSUE THREAD

**Issue by smaity91** [extent-framework/extentreports-java#169]
**Issue 1:** '**Views**' shortcuts are not working when report generated using default Dark theme.

**Issue 2:** '**Filters**' shortcuts causing blank left panel on Tags tab and Exception tab for both Dark and Standard theme.

For 1st issue: Generate a spark report using default dark theme
For 2nd issue: http://extentreports.com/docs/versions/4/java/files/spark/index.html

**Comment by anshooarora** [comment]
Shortcuts have been re-introduced starting version 5.0.0-SNAPSHOT.

https://github.com/extent-framework/extentreports-java/tree/v5.0.x#whats-new
