### ISSUE TITLE
Test Step diagram missing

### ISSUE THREAD

**Issue by performrumpf** [extent-framework/extentreports-java#17]
In version 4.0.6 the diagram for test steps is missing (was available in 3.1.5). Concerns test view and dashboard view.

![tests_view_4 0 6](https://user-images.githubusercontent.com/39511399/50293673-6b094d80-0474-11e9-9b41-b6a59adc7598.png)

**Comment by anshooarora** [comment]
@performrumpf is this the same as #18?
