### ISSUE TITLE
Test Level Start time and end time are not getting calculated automatically in SPARK for Extent v4.1.5

### ISSUE THREAD

**Issue by smaity91** [extent-framework/extentreports-java#170]
#6 Now StartTime=EndTime for all my passed TCs. Also failed one not showing correct time.
In V3 this was getting calculated automatically without any additional code for HTMLReporter. Is there anything I need to include additionally?

**Comment by anshooarora** [comment]
How are you generating the report? If time needs to be calculated dynamically in version 4, you need to use the below setting:

```
extent.setReportUsesManualConfiguration(true);
```

**Comment by smaity91** [comment]
I am generating report using implementing testNG's ITestListener without doing much customization. I have tried this extent.setReportUsesManualConfiguration(true) but it didn't help. Otherwise I dont have any code explicitly that'll do the time set or calculation.

**Comment by anshooarora** [comment]
Its not possible to know where its going wrong without looking at your usage.  Why don't you use the adapter directly: https://github.com/extent-framework/extentreports-testng-adapter or use the relevant parts?

See the adapter's ITestListener implementation [here](https://github.com/extent-framework/extentreports-testng-adapter/blob/master/src/main/java/com/aventstack/extentreports/testng/listener/ExtentITestListenerAdapter.java)

**Comment by smaity91** [comment]
Ok yes I got that it's difficult without seeing the code. However I will try out the adapter you have mentioned.

Thanks for such beautiful as well as widely customized report though.

**Comment by grasshopper7** [comment]
Is there anyway to override the default behavior of `reportStartDate` and `reportEndDate` being setup by comparison as in this method below?

https://github.com/extent-framework/extentreports-java/blob/ca7b138bc2879a9c9c46a42412df0305f7048180/src/main/java/com/aventstack/extentreports/ReportObservable.java#L472

Setting the `setReportUsesManualConfiguration` works for the custom start time but the custom end time gets overwritten by the method. The custom end time is before the 'now current time' setup by this line.

https://github.com/extent-framework/extentreports-java/blob/ca7b138bc2879a9c9c46a42412df0305f7048180/src/main/java/com/aventstack/extentreports/ReportObservable.java#L437

Can the default setting up of the `reportStartTime` and `reportEndTime` be done based on the `ReportUsesManualConfiguration`? Or is there any other way? Thanks.

**Comment by anshooarora** [comment]
@grasshopper7 this will be configurable directly via the model starting version 5. 

Here is the new entity:  https://github.com/extent-framework/extentreports-java/blob/v5.0.x/src/main/java/com/aventstack/extentreports/model/Report.java

Here is the processor that receives from ExtentReports and uses a publisher to send messages downstream to reporters:  https://github.com/extent-framework/extentreports-java/blob/v5.0.x/src/main/java/com/aventstack/extentreports/AbstractProcessor.java#L86

In a future release, the above will only apply if manualOverrides are disabled. Unless manually set, none of the entities would update `ending time` after creation, with default behavior resulting in duration of ~0 milliseconds regardless of how long the run session takes. 

The idea is to implement this for starting and ending timestamps, and extend it to other use cases on an as needed basis.
