### ISSUE TITLE
Device filter is not working as expected in extentreport.html

### ISSUE THREAD

**Issue by ankitvashistha2901** [extent-framework/extentreports-java#172]
- Execute test suite on devices ie. iPhoneXSMax, iPhoneXS
- Select Tests from left side
- Select Device from filter (iPhoneXS)

Actual behavior/Issue: After selecting filter, it is displaying the test cases that was executed on iPhoneXS, iPhoneXSMax both.

Expected behavior: After selecting filter, it should display the test cases that was executed on iPhoneXS only.

**Comment by anshooarora** [comment]
More details about the setup would help. Are there nested tests for each device?
