### ISSUE TITLE
Time Line starting from -200 and tooltip of timeline showing width

### ISSUE THREAD

**Issue by ankitgupta9289** [extent-framework/extentreports-java#178]
TimeLine starting from -200 and tooltip of timeline showing width.

PFA Screenshot

![image](https://user-images.githubusercontent.com/52029195/83716169-c4efda00-a64c-11ea-9272-b69086acce0b.png)

**Comment by anshooarora** [comment]
Also unable to reproduce this. I would need the output file to understand the cause.

**Comment by ankitgupta9289** [comment]
this error is coming frequently sometimes it works perfectly other time -200 comes in timeline

**Comment by anshooarora** [comment]
This one is a little tough to reproduce without seeing this behavior in action..  My suspicion is it may happen due to some meta characters in your test name, which might break the correct rendering.  Do any of your tests have any meta characters other than the standard numbers/letters?
