### ISSUE TITLE
Environment section should be on the top as people store critical information.

### ISSUE THREAD

**Issue by ankitgupta9289** [extent-framework/extentreports-java#180]
Environment Section should be on the top of the Tags section as people store critical information about the execution like BuildVersion, Environment, Groups Executed, Device Details and Execution details

![image](https://user-images.githubusercontent.com/52029195/83718365-8a893b80-a652-11ea-87e9-e91f14f3d6cb.png)

**Comment by anshooarora** [comment]
Important would be subjective, as most users prefer having their attributes show up at the top.  So, this won't be the default setting.  However, you can customize this view using JS/jQuery for it to appear before any of the other boxes.
