### ISSUE TITLE
Dashboard: Under Tags, OTHERS are not accounting for skipped test cases

### ISSUE THREAD

**Issue by ankitvashistha2901** [extent-framework/extentreports-java#181]
- Select Dashboard from left side
- Under Tags, OTHERS are not displaying skipped test cases count. It is showing 0 test cases under the same.

**Comment by anshooarora** [comment]
Version and reporter?

**Comment by ankitvashistha2901** [comment]
ExtentReport version : 4.1.5

**Comment by ankitvashistha2901** [comment]
We are using this dependency as part of our framework:

<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>4.1.5</version>
</dependency>

**Comment by anshooarora** [comment]
You can now update to 4.1.6. This was one of the fixes. #149
