### ISSUE TITLE
Add Feature to count ChildTests as a part of MainTests

### ISSUE THREAD

**Issue by ankitgupta9289** [extent-framework/extentreports-java#182]
Add Feature to count ChildTests as a part of MainTests

Suppose my tests are - 100
And child tests are - 20 

Total It Should Show - 120 instead of 100

**Comment by anshooarora** [comment]
This is a very specific use case and can only be supported with a custom implementation.  The default setting is to count the leaf tests only, or to be configured in counting all levels separately as its done with `AnalysisStrategy.CLASS`, `AnalysisStrategy.SUITE` or a report that defaults as `BDD`.
