### ISSUE TITLE
extent.js URL is returning a 404

### ISSUE THREAD

**Issue by tsnajera** [extent-framework/extentreports-java#183]
Hi,

The extent.js URL that both new and existing reports use is returning a 404 so all my Extent reports are not showing correctly.
https://cdn.rawgit.com/extent-framework/extent-github-cdn/master/v3html/js/extent.js

Can someone please look into this?

Thanks,
Troy

**Comment by anshooarora** [comment]
Can you refresh your report now and check?

**Comment by tsnajera** [comment]
It is working now. I really appreciate your quick response.

Thank you so much!
