### ISSUE TITLE
Authors category is not displaying in left section

### ISSUE THREAD

**Issue by qatestingravi** [extent-framework/extentreports-java#187]
Description: create any test and assign author

Expected:
Authors category should be displayed in left section

Actual:
Authors category is not displaying in left section

Verified in below versions
4.0.9 : its working
4.1.9 : its not working

++++++++++++++++++++++++++++++++ Used below code for 4.0.9 version 

		String resultFileName = System.getProperty("user.dir") + "/reports/" +    System.currentTimeMillis() + ".html";
		ExtentHtmlReporter reporter = new ExtentHtmlReporter(resultFileName);
		ExtentReports extent = new ExtentReports();
		extent.attachReporter(reporter);
		System.out.println("resultFileName: " + resultFileName);
		extent.setSystemInfo("OS", "windows");
	
		spark.config().setDocumentTitle("Automation");
		ExtentTest test = extent.createTest("MyFirstTest");
		test.assignAuthor("ravi");
		test.pass("fist step details");
		extent.flush();

+++++++++++++++++++++++++++++ Used below code for 4.1.6 version

		String resultFileName = System.getProperty("user.dir") + "/reports/" + System.currentTimeMillis() + ".html";
		ExtentSparkReporter spark = new ExtentSparkReporter(resultFileName);
		ExtentReports extent = new ExtentReports();
		extent.attachReporter(spark);
		System.out.println("resultFileName: " + resultFileName);
		extent.setSystemInfo("OS", "windows");
	
		spark.config().setDocumentTitle("Automation");
		ExtentTest test = extent.createTest("MyFirstTest");
		test.assignAuthor("ravi");
		test.pass("fist step details");
		extent.flush();

++++++++++++++
<img width="657" alt="Author_4 0 9_version working" src="https://user-images.githubusercontent.com/38858602/84287471-9480d200-ab5d-11ea-8317-d7ef2bebe1e9.png">
<img width="614" alt="Author_4 1 6_version_not working" src="https://user-images.githubusercontent.com/38858602/84287476-95196880-ab5d-11ea-9e93-76e17c52a411.png">

**Comment by anshooarora** [comment]
This has been addressed in https://github.com/extent-framework/extentreports-java/issues/152 and will be part of 5.0.0 release.
