### ISSUE TITLE
[Poll] New Community Template

### ISSUE THREAD

**Issue by anshooarora** [extent-framework/extentreports-java#19]
Hello all,

I have been working on the replacement for the current view created by `ExtentHtmlReporter` and wanted to hear your views whether the updated template can serve as a viable alternative.

Kindly see the demo below and let me know using :thumbsup: or :thumbsdown:, or share your views, feedback, comments, or concerns with the replacement.  

If there is enough support, the new template will be used as a replacement or else we will continue with and maintain the existing template.  I would like to set 50 :thumbsup: or positive comments as the target number.

#### Demo
See [here](http://extentreports.com/docs/versions/4/samples/experimental/v4-html/index.html)

#### Screenshots

![test](https://user-images.githubusercontent.com/4107384/50380462-03026500-0636-11e9-83e3-a7b7bc713946.png)

![dashboard](https://user-images.githubusercontent.com/4107384/50380463-04cc2880-0636-11e9-976d-8cc146b30d3c.png)

**Comment by mmajcherczyk** [comment]
in my opinion, it's better to stick to one color for status
instead of this
![extent framework - mozilla firefox 2019-01-08 22 20 36](https://user-images.githubusercontent.com/6592592/50859789-98bb2580-1394-11e9-869e-1e8f57f06678.png)

something like that
![extent framework - mozilla firefox 2019-01-08 22 20 09](https://user-images.githubusercontent.com/6592592/50859791-9c4eac80-1394-11e9-8118-ca2d3f3e8a13.png)

**Comment by foursyth** [comment]
@mmajcherczyk 

Good points, noted.

**Comment by rajikuchana** [comment]
Good Design ,we require this one for Community Version

**Comment by anshooarora** [comment]
Yeah, I am also leaning towards not replacing the default reporter after feedback from the .net users. Will launch it under its codename, will post updates soon.

**Comment by anshooarora** [comment]
I am closing this poll.  Due to the changes in this reporter and the 4 files created instead of 1, I feel replacing the default reporter may not be the right thing to do.  This change may break existing pipeline args, or post-build scripts.

Please use `ExtentSparkReporter` starting version `4.0.7` onwards.

Thank you everyone!
