### ISSUE TITLE
Controlling Timezone for the reports - ExtentSparkReporter

### ISSUE THREAD

**Issue by dileepguntamadugu** [extent-framework/extentreports-java#192]
Is there a way to control the Timezone to be used in the ExtentSparkReporter?
The problem is due to the cloud instance being hosted in a different location where the scripts and reports are generated which are taking the machine time zone.

The team resides in a very far away timezone and the timestamp in the report doesn't make sense.

Tried setting the system property **user.timezone** during run time but that doesn't do any help.

**Comment by anshooarora** [comment]
This can be done without any changes to the API, by using the timezone offset like so:

```
TimeZone.setDefault(TimeZone.getTimeZone("Asia/Kolkata"));
```

where "Asia/Kolkata" is the TimeZone.ID, see [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).
