### ISSUE TITLE
Getting error java.lang.NoClassDefFoundError: com/aventstack/extentreports/reporter/ConfigurableReporter

### ISSUE THREAD

**Issue by far11ven** [extent-framework/extentreports-java#195]
I'm using cucumber 5.5, with extent framework extentreports-5.0.0-20200624.065652-1.jar version from Sonatype
along with Grasshopper's adapter: extentreports-cucumber5-adapter v1.3.2

Still, I'm getting following error:

[INFO] Running com.kushal.testRunner.CucumberTestRunnerReporter
Jun 24, 2020 12:38:03 PM io.cucumber.testng.TestNGCucumberRunner
WARNING: By default Cucumber is running in --non-strict mode.
This default will change to --strict and --non-strict will be removed.
You can use --strict or @CucumberOptions(strict = true) to suppress this warning
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 1.106 s <<< FAILURE! - in com.kushal.testRunner.CucumberTestRunnerReporter
[ERROR] setUpClass(com.kushal.testRunner.CucumberTestRunnerReporter) Time elapsed: 0.756 s <<< FAILURE!
io.cucumber.core.exception.CucumberException: java.lang.NoClassDefFoundError: com/aventstack/extentreports/reporter/ConfigurableReporter
Caused by: java.lang.NoClassDefFoundError: com/aventstack/extentreports/reporter/ConfigurableReporter
Caused by: java.lang.ClassNotFoundException: com.aventstack.extentreports.reporter.ConfigurableReporter

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR] CucumberTestRunnerReporter>AbstractTestNGCucumberTests.setUpClass:22 » Cucumber
[INFO]
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2

**Comment by anshooarora** [comment]
Looks like this was created by mistake. Question has been answered here https://github.com/extent-framework/extentreports-java/issues/194#issuecomment-648647149
