### ISSUE TITLE
Getting a lot of console logs of freemarker.cache

### ISSUE THREAD

**Issue by manasi-rk** [extent-framework/extentreports-java#196]
Hi,

I am using extent-report version 4.1.6. i have recently migrated from version 2. All the necessary changes have been made, and the report works great. But i have been receiving a lot of console log DEBUG messages and they are generated whenever flush is called. So they are crowding my console and would like to get rid of it. Am i missing something here? 

16:22:07.747 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "spark/spark.spa.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:07.749 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/spark.spa_en_IN.ftl"): Not found
16:22:07.751 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/spark.spa_en.ftl"): Not found
16:22:07.752 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/spark.spa.ftl"): Found
16:22:07.752 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "spark/spark.spa.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/spark/spark.spa.ftl"
16:22:07.913 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "commons/commons-variables.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:07.913 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("commons/commons-variables_en_IN.ftl"): Not found
16:22:07.914 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("commons/commons-variables_en.ftl"): Not found
16:22:07.914 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("commons/commons-variables.ftl"): Found
16:22:07.914 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "commons/commons-variables.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/commons/commons-variables.ftl"
16:22:08.027 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "commons/commons-macros.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:08.027 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("commons/commons-macros_en_IN.ftl"): Not found
16:22:08.028 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("commons/commons-macros_en.ftl"): Not found
16:22:08.029 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("commons/commons-macros.ftl"): Found
16:22:08.029 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "commons/commons-macros.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/commons/commons-macros.ftl"
16:22:08.059 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "spark/macros/attributes.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:08.060 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/macros/attributes_en_IN.ftl"): Not found
16:22:08.061 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/macros/attributes_en.ftl"): Not found
16:22:08.062 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/macros/attributes.ftl"): Found
16:22:08.062 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "spark/macros/attributes.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/spark/macros/attributes.ftl"
16:22:08.066 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "spark/macros/log.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:08.067 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/macros/log_en_IN.ftl"): Not found
16:22:08.068 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/macros/log_en.ftl"): Not found
16:22:08.068 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/macros/log.ftl"): Found
16:22:08.068 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "spark/macros/log.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/spark/macros/log.ftl"
16:22:08.076 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "spark/macros/recurse_nodes.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:08.077 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/macros/recurse_nodes_en_IN.ftl"): Not found
16:22:08.079 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/macros/recurse_nodes_en.ftl"): Not found
16:22:08.080 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/macros/recurse_nodes.ftl"): Found
16:22:08.080 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "spark/macros/recurse_nodes.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/spark/macros/recurse_nodes.ftl"
16:22:08.083 [TestNG-tests-1] DEBUG freemarker.cache - "spark/macros/log.ftl"("en_IN", UTF-8, parsed) cached copy not yet stale; using cached.
16:22:08.093 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "spark/partials/head.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:08.096 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/head_en_IN.ftl"): Not found
16:22:08.097 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/head_en.ftl"): Not found
16:22:08.097 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/head.ftl"): Found
16:22:08.097 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "spark/partials/head.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/spark/partials/head.ftl"
16:22:08.101 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "commons/commons-inject-css.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:08.102 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("commons/commons-inject-css_en_IN.ftl"): Not found
16:22:08.102 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("commons/commons-inject-css_en.ftl"): Not found
16:22:08.103 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("commons/commons-inject-css.ftl"): Found
16:22:08.106 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "commons/commons-inject-css.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/commons/commons-inject-css.ftl"
16:22:08.112 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "spark/partials/navbar.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:08.113 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/navbar_en_IN.ftl"): Not found
16:22:08.116 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/navbar_en.ftl"): Not found
16:22:08.116 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/navbar.ftl"): Found
16:22:08.116 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "spark/partials/navbar.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/spark/partials/navbar.ftl"
16:22:08.132 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "spark/partials/sidenav.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:08.132 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/sidenav_en_IN.ftl"): Not found
16:22:08.137 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/sidenav_en.ftl"): Not found
16:22:08.139 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/sidenav.ftl"): Found
16:22:08.139 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "spark/partials/sidenav.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/spark/partials/sidenav.ftl"
16:22:08.142 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "spark/partials/test.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:08.143 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/test_en_IN.ftl"): Not found
16:22:08.144 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/test_en.ftl"): Not found
16:22:08.144 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/test.ftl"): Found
16:22:08.144 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "spark/partials/test.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/spark/partials/test.ftl"
16:22:08.196 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "spark/partials/standard-content.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:08.197 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/standard-content_en_IN.ftl"): Not found
16:22:08.198 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/standard-content_en.ftl"): Not found
16:22:08.198 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/standard-content.ftl"): Found
16:22:08.198 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "spark/partials/standard-content.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/spark/partials/standard-content.ftl"
16:22:08.219 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "spark/partials/dashboard.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:08.222 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/dashboard_en_IN.ftl"): Not found
16:22:08.224 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/dashboard_en.ftl"): Not found
16:22:08.225 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/dashboard.ftl"): Found
16:22:08.232 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "spark/partials/dashboard.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/spark/partials/dashboard.ftl"
16:22:08.310 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "spark/partials/scripts.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:08.312 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/scripts_en_IN.ftl"): Not found
16:22:08.313 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/scripts_en.ftl"): Not found
16:22:08.314 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("spark/partials/scripts.ftl"): Found
16:22:08.314 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "spark/partials/scripts.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/spark/partials/scripts.ftl"
16:22:08.317 [TestNG-tests-1] DEBUG freemarker.cache - Couldn't find template in cache for "commons/commons-inject-js.ftl"("en_IN", UTF-8, parsed); will try to load it.
16:22:08.318 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("commons/commons-inject-js_en_IN.ftl"): Not found
16:22:08.319 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("commons/commons-inject-js_en.ftl"): Not found
16:22:08.320 [TestNG-tests-1] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("commons/commons-inject-js.ftl"): Found
16:22:08.320 [TestNG-tests-1] DEBUG freemarker.cache - Loading template for "commons/commons-inject-js.ftl"("en_IN", UTF-8, parsed) from "jar:file:/C:/Users/manasikarande/.gradle/caches/modules-2/files-2.1/com.aventstack/extentreports/4.1.4/90f3075a87a69ed3d921d3f9223b8cefd01bd893/extentreports-4.1.4.jar!/com/aventstack/extentreports/view/commons/commons-inject-js.ftl"

**Comment by anshooarora** [comment]
Using logback? log4j?

**Comment by manasi-rk** [comment]
nopes.. not using any logging.. only extent reporting.

**Comment by anshooarora** [comment]
Not directly, but probably a dependency or a configuration you have in your project which may be causing this.

See here:  https://stackoverflow.com/questions/27508468/disable-freemarker-logs-from-logs4j
and here:  https://freemarker.apache.org/docs/pgui_misc_logging.html
