### ISSUE TITLE
Extent Report Not Getting Generated

### ISSUE THREAD

**Issue by gitMukhtar** [extent-framework/extentreports-java#20]
package com.fuseapp.qa.ExtentReportListner;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.testng.IReporter;
import org.testng.IResultMap;
import org.testng.ISuite;
import org.testng.ISuiteResult;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.xml.XmlSuite;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

public class ExtentReporterNG implements IReporter {
	private ExtentReports extent;

	public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites,
			String outputDirectory) {
		String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new Date());
		extent = new ExtentReports(outputDirectory + File.separator + timeStamp+"_"+"Test_Report"+ "Extent.html", true);
		
		
//	extent = new ExtentReports (outputDirectory +File.separator+ timeStamp + ".html", true);

		for (ISuite suite : suites) {
			Map<String, ISuiteResult> result = suite.getResults();

			for (ISuiteResult r : result.values()) {
				ITestContext context = r.getTestContext();

				buildTestNodes(context.getPassedTests(), LogStatus.PASS);
				buildTestNodes(context.getFailedTests(), LogStatus.FAIL);
				buildTestNodes(context.getSkippedTests(), LogStatus.SKIP);
			}
		}

		extent.flush();
		extent.close();
	}

	private void buildTestNodes(IResultMap tests, LogStatus status) {
		ExtentTest test;

		if (tests.size() > 0) {
			for (ITestResult result : tests.getAllResults()) {
				test = extent.startTest(result.getMethod().getMethodName());

				test.setStartedTime(getTime(result.getStartMillis()));
				test.setEndedTime(getTime(result.getEndMillis()));

				for (String group : result.getMethod().getGroups())
					test.assignCategory(group);

				if (result.getThrowable() != null) {
					test.log(status, result.getThrowable());
				} else {
					test.log(status, "Test " + status.toString().toLowerCase()
							+ "ed");
				}

				extent.endTest(test);
				
			}
		}
	}

	private Date getTime(long millis) {
		Calendar calendar = Calendar.getInstance();
		calendar.setTimeInMillis(millis);
		return calendar.getTime();
	}
}
................This is my code: I was able to generate extent report with this but, now it has stopped generating extent report.
POM:

		<dependency>
			<groupId>com.relevantcodes</groupId>
			<artifactId>extentreports</artifactId>
			<version>2.41.2</version>
		</dependency>
......
Please help me with the resolution.
I can share my repo details if required.

**Comment by gitMukhtar** [comment]
Hi Team,
Any update?

**Comment by foursyth** [comment]
I would suggest upgrading to version 4 and using the testng-adapter. It will hugely simplify everything.

See: 
https://github.com/extent-framework/extentreports-testng-adapter

**Comment by gitMukhtar** [comment]
To implement this, I need to modify this. Do we have a stable version for this?
<dependency>
		<groupId>com.relevantcodes</groupId>
		<artifactId>extentreports</artifactId>
		<version>2.41.2</version>
	</dependency>
?

**Comment by foursyth** [comment]
Version 2 is not supported anymore and version 3 sport will end by Jan 2019. It should not take you more than 5 mins to setup version 4 with the testing adapter...

**Comment by gitMukhtar** [comment]
Facing some issues while implementing this into my framework. Can I get your mail ID?

**Comment by anshooarora** [comment]
I am closing this as there has not been a response. Feel free to re-open or create a new ticket referencing this one.  Thank you.
