### ISSUE TITLE
MarkupHelper.createCodeBlock is not working properly

### ISSUE THREAD

**Issue by Manoj-kumawat** [extent-framework/extentreports-java#202]
Extent Report Version - 4.1.6
I used MarkupHelper.createCodeBlock to display json response in report. but it is displaying some code snippet instead of json format.

Report screenshot-
![image](https://user-images.githubusercontent.com/39849715/86016842-efad3280-ba40-11ea-90d9-5101312dfc16.png)

![image](https://user-images.githubusercontent.com/39849715/86016895-fb98f480-ba40-11ea-9b19-035c1346533a.png)

**Comment by anshooarora** [comment]
This was fixed earlier and will be available in 4.1.7.

https://github.com/extent-framework/extentreports-java/commit/890492376708948ed914a5c90d7239ca6a6bc89d

**Comment by anshooarora** [comment]
You can now use:  `extentreports:4.1.7`.
