### ISSUE TITLE
Extent Report producing duplicate Suite Name in Parallel Execution

### ISSUE THREAD

**Issue by sahilsehgals4392** [extent-framework/extentreports-java#203]
Hi Team,
I am generating Extent Report for parallel execution in TestNG.
I am printing the Test name in report.
However, in parallel execution, it is not generating the correct name:

Could you please help me with this:
Attaching xml and project.

> TestNG.XML
  <suite name="Extent Report Parallel report" parallel="tests" >
   <listeners>
    <listener class-name="ExtentListener"></listener>
    </listeners>
    <test name="Local Chrome Browser Test">
        <parameter name="browser" value="chrome"/>
        <parameter name="platform" value="windows"/>
        <classes>
            <class name="testClassA"/>
        </classes>
    </test>
      <test name="Local FF Browser Test" >
        <parameter name="browser" value="Firefox"/>
        <parameter name="platform" value="windows"/>
        <classes>
            <class name="testClassA"/>
        </classes>
    </test>
</suite>`

**Comment by sahilsehgals4392** [comment]
[Demo Project.zip](https://github.com/extent-framework/extentreports-java/files/4852429/Demo.Project.zip)

**Comment by sahilsehgals4392** [comment]
<img width="960" alt="Serial Execution" src="https://user-images.githubusercontent.com/18054863/86139006-d4a7f480-bb0c-11ea-8883-45c044dbd01f.png">
<img width="960" alt="Parallel" src="https://user-images.githubusercontent.com/18054863/86139010-d671b800-bb0c-11ea-9124-8cec3de81f5c.png">

**Comment by anshooarora** [comment]
@sahilsehgals4392 Can you create a Github repo or a gist to share your code instead?
