### ISSUE TITLE
Extent Report version 4, In tags/category level , testcases dont have hyperlink with testcase in detail level

### ISSUE THREAD

**Issue by sahithichandarala** [extent-framework/extentreports-java#205]
I was using version 3 of extent report before, now i have upgraded version  4, what i have observed is, in category level previously there is hyperlink test case wise, upon clicking on testcase in category level, it navigates to respective testcase in 1st level, but in version 4, hyperlink is missing..is there any alternative way where i can produce this
version 3:
![image](https://user-images.githubusercontent.com/67781975/86453417-5ed5a000-bd3b-11ea-9dc7-e822a7d917d9.png)

version 4:
![image](https://user-images.githubusercontent.com/67781975/86453514-8a588a80-bd3b-11ea-90c0-e62895e77951.png)

code used:
I am using testNg with listener 'ITestListener' and extent report.

I have Report.java class where i will instantiate extents for each test case with below method
public extent createinstance()
{
ExtentReports extent1 = new ExtentReports(); 
ExtentSparkReporter htmlReporter = new ExtentSparkReporter(file); htmlReporter.loadXMLConfig(System.getProperty("user.dir")+"\\extent-config.xml");
extent1.attachReporter(htmlReporter);
return extent1;
}

in listerner class
@Override
	public void onTestStart(ITestResult result) {
		ThreadLocal<Report> report = new ThreadLocal<Report>();
		CSVReader CSV = new CSVReader();
                // retrieve category for test case from data file
		String category = CSV.getcategory(result.getMethod().getMethodName());
		System.out.println(("*** Running test method " + result.getMethod().getMethodName() + "..."));
		report.get().startTest(result.getMethod().getMethodName(), category);
	}

	public void onFinish(ITestContext testContext) {
		System.out.println(("*** Test Suite " + testContext.getName() + " ending ***"));
		ThreadLocal<Report> report = new ThreadLocal<Report>();
		ThreadLocal<ExtentManager> extentManager = new ThreadLocal<ExtentManager>();
		report.get().endTest();
		extentManager.get().getInstance().flush();
		ExtentManager.extent.set(null);
	}

....note: i have not update all the code here...

everything is as expected except that hyperlink for testcases which i was expecting in tag/category level

**Comment by anshooarora** [comment]
@sahithichandarala This was part of #168 and will be available with version 5, soon.
