### ISSUE TITLE
Clicking on Left Navigation Tabs while the report is loading leads to error page

### ISSUE THREAD

**Issue by puneetamishra1** [extent-framework/extentreports-java#206]
Clicking on Left Navigation Tabs while the report is loading leads to an error page.

Steps - Open the report immediately click on the dashboard link.
Issue - 404 not found page.

![image](https://user-images.githubusercontent.com/38757281/86988944-011bda80-c1b7-11ea-9997-bcfc7d1a4f02.png)

**Comment by anshooarora** [comment]
@puneetamishra1 I am not quite sure of this as I have not been able to reproduce it on my own.  Does this happens only with Jenkins?
