### ISSUE TITLE
AddScreenCaptureFromPath : The title is not working

### ISSUE THREAD

**Issue by musanas** [extent-framework/extentreports-java#208]
Hi,

**ExtentTest** has an overloading method - _addScreenCaptureFromPath_ which takes a **title** parameter, i suppose this is to display a tool tip for the the screenshot file in report.
Seems like passing a value for title has no effect, it do not shows up in the report
I am using ExtentSparkReporter to generate the ExtentReports

Thanks
Musaffir

**Comment by anshooarora** [comment]
@musanas This is currently a missing functionality in version 4.  It will be available in the upcoming version 5, and I will try to add it to v4 as well (after v5 is released though).
