### ISSUE TITLE
How to remove Duration Widget from report

### ISSUE THREAD

**Issue by musanas** [extent-framework/extentreports-java#209]
Hello,

This is a question, I would like to remove the Duration widget from the html report. How can i do that ?
I load xml config for ExtentSparkReporter instance, not sure we can do this from this file..

<img width="924" alt="Duration widget" src="https://user-images.githubusercontent.com/25841256/87275744-672c9880-c4fc-11ea-99f6-9411bef3a03a.png">

Thanks & Warm Regards
Musaffir

**Comment by anshooarora** [comment]
@musanas Via JS:

```
$('.dashboard-view .col-md-3').filter(function() { 
  return $(this).text().indexOf('Duration') >= 0; 
}).hide();
```
