### ISSUE TITLE
Extent spark reporter

### ISSUE THREAD

**Issue by AshutoshMishra08** [extent-framework/extentreports-java#210]
Hello,

I am unable to see charts in dashboard for Features, Scenario, Steps and Timeline. Any help appreciated
![extentReport](https://user-images.githubusercontent.com/19917872/87669047-43a36100-c73b-11ea-9061-c935227c87a6.png)

POM:
<dependency>
	    <groupId>com.aventstack</groupId>
	    <artifactId>extentreports</artifactId>
	    <version>4.1.7</version>
</dependency>

Code to start report -
ExtentSparkReporter spark = new ExtentSparkReporter(getReportPath(), ViewStyle.SPA);
    	spark.config().setCSS("css-string");
    	spark.config().setDocumentTitle(DTO.getApplicationName());
    	spark.config().setEncoding("utf-8");
    	spark.config().setJS("js-string");
    	spark.config().setProtocol(Protocol.HTTPS);
    	spark.config().setReportName(DTO.getReportHeadline());
    	spark.config().setTheme(Theme.STANDARD);
    	spark.config().setTimeStampFormat("EEEE, MMMM dd, yyyy, hh:mm a '('zzz')'");
    	spark.config().enableTimeline(true);
    	     	   	    	
        extent = new ExtentReports();
        extent.attachReporter(spark);         
        extent.setSystemInfo("OS", System.getProperty("os.name"));
        extent.setAnalysisStrategy(AnalysisStrategy.BDD);
        extent.setAnalysisStrategy(AnalysisStrategy.TEST);
	return extent;

Appreciate any help!

Thanks,
Ash

**Comment by anshooarora** [comment]
@AshutoshMishra08  If what you have shared is indeed the instantiation, you need to remove the below because both strings are invalid:

```
spark.config().setCSS("css-string");
spark.config().setJS("js-string");
```
