### ISSUE TITLE
Invalid Date Is Generating For Spark Report

### ISSUE THREAD

**Issue by chik145** [extent-framework/extentreports-java#211]
Invalid Date Is Generating For Spark Report For 4.1.7 Version 
setTimeStampFormat("mm/dd/yyyy hh:mm:ss a");

![image](https://user-images.githubusercontent.com/26041357/87634874-c3d9be80-c75b-11ea-82f8-1bc104b65adc.png)

**Comment by anshooarora** [comment]
@chik145 The correct format would be `setTimeStampFormat("MM/dd/yyyy hh:mm:ss a");` with 2 capital M's.
