### ISSUE TITLE
Extra spaces and tabs in docstring display fro cucumber adapter for extent version 4.1.x

### ISSUE THREAD

**Issue by grasshopper7** [extent-framework/extentreports-java#214]
This is in continuation of this issue https://github.com/extent-framework/extentreports-cucumber4-adapter/issues/60#issuecomment-660677316

Getting **2 spaces for the first line** in docstring display using the `MarkupHelper.createCodeBlock` for **extent version 4.1.7**. Get an **extra tab for versions 4.1.6** and below. In **BOTH cases** there is an **extra new line at the bottom**.
This **works perfectly in extent version 5**-snapshot.

Link to the relevant code (docstring branch) with print statements included - https://github.com/grasshopper7/extentreports-cucumber5-adapter/blob/b3a0a6226d831a24bf20f82fad8ab1ac5e6b170f/extentreports-cucumber5-adapter/src/main/java/com/aventstack/extentreports/cucumber/adapter/ExtentCucumberAdapter.java#L463

### Version 4.1.7
Console output - Extra 2 spaces for the first line in  markup output
```
--Original Doc String------
Hello there how r u?

Doing great.
Whats new?
--Markup Doc String------
<textarea readonly class='code-block'>
  Hello there how r u?

Doing great.
Whats new?
</textarea>
```
Browser output -
![docstring-extent-4 1 7](https://user-images.githubusercontent.com/10829355/87914022-ab381400-ca8d-11ea-96cd-b33a86327c26.png)

### Version 4.1.6 and below
Console output - Additional tab for the first line in markup output
```
--Original Doc String------
Hello there how r u?

Doing great.
Whats new?
--Markup Doc String------
<textarea readonly class='code-block'>
	Hello there how r u?

Doing great.
Whats new?
</textarea>
```
Browser output -
![docstring-extent-4](https://user-images.githubusercontent.com/10829355/87914131-d7539500-ca8d-11ea-8e5e-7b76fc939747.png)

For reference adding
### Version 5
Console output -
```
Hello there how r u?

Doing great.
Whats new?
--Markup Doc String------
<textarea readonly class='code-block'>Hello there how r u?

Doing great.
Whats new?</textarea>
```
Browser output -
![docstring-extent-5snap](https://user-images.githubusercontent.com/10829355/87914507-5c3eae80-ca8e-11ea-8923-8877a6de0c03.png)

**Comment by anshooarora** [comment]
Thank you for your detailed research :)  I am hoping to launch version 5 very soon, would it help if it becomes the standard dependency across all plugins?

**Comment by grasshopper7** [comment]
From the point of view of adapters or plugins this issue does not seem to be that important. As it works in 5, once the version is switched behind the scenes this disappears. This would only impact folks who use extent 4 directly and have not upgraded yet.
Do u have some kind of timeline when extent & klov V5 is available on central?

**Comment by anshooarora** [comment]
Planning to release this week if everything works out.

**Comment by anshooarora** [comment]
Relwase v5 is ready. Please update :)

**Comment by grasshopper7** [comment]
Will try to update both in a couple of days.
