### ISSUE TITLE
Tests page Timestamp for each test is incorrect

### ISSUE THREAD

**Issue by musanas** [extent-framework/extentreports-java#216]
Hi

This is same issue as https://github.com/anshooarora/extentreports-java/issues/993 reported by @carlc986

which is in archive repo now

I could also reproduce the same issue, the time stamp value in each test details section. please find the below pic

<img width="903" alt="Time stamp value" src="https://user-images.githubusercontent.com/25841256/88141193-be272180-cc10-11ea-8449-5627ea5e34e9.png">

**Comment by anshooarora** [comment]
Are you using IReporter? Possible to share your code so I can repro?

**Comment by musanas** [comment]
Hi @anshooarora 

Yes am using IReporter interface which is implemented in a listener class, 
hence the report building happens after the testNg suite execution completed.
The suite contains just one test class.

I will share the listener class here .
All you need to have is a test class which has few test methods. Add the listener class.
The reports gets generated as this listener class is configured to pick up ( i added it in testNg suite xml file ).

The **Tests** page in the report, which lists all the tests, shows the test log , there we have a **TIMESTAMP** field
This shows constant value for all tests, and it is equal to the suite completion time .

Am using : 4.1.5

`package extent;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.testng.IReporter;
import org.testng.IResultMap;
import org.testng.ISuite;
import org.testng.ISuiteResult;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.xml.XmlSuite;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;
import com.legal.quant.web.operations.SeleniumCommands;

public class ExecutionReporter implements IReporter
{
	private ExtentReports extent ;

	@Override
	public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
		extent = new ExtentReports();
		String sparkpath = System.getProperty("user.dir")+File.separator+"target";
		
		ExtentSparkReporter spark = setSparkConfig(sparkpath);
		
		extent.attachReporter(spark);
		setSystemInfo();
		extent.setReportUsesManualConfiguration(true);
		


		for (ISuite suite : suites) {
			Map<String, ISuiteResult> result = suite.getResults();

			for (ISuiteResult r : result.values()) {
				ITestContext context = r.getTestContext();

				buildTestNodes(context.getPassedTests(), Status.PASS);
				buildTestNodes(context.getFailedTests(), Status.FAIL);
				buildTestNodes(context.getSkippedTests(),Status.SKIP);
			}
			
			
		}

		extent.flush();
		
	}
	
	private void buildTestNodes(IResultMap tests, Status status) {
		
		ExtentTest test;
		
		Set<ITestResult> allResults = tests.getAllResults();
		
		// Set<ITestResult> : tests in this set are in some random order, same tests that run for diff test data
		//are not together. they are being sorted here after changing it to a List
		
		List<ITestResult> totalResults = new ArrayList<ITestResult>(allResults);
		Collections.sort(totalResults);
				

		if (tests.size() > 0) {
			for (ITestResult result : totalResults) {
								
				test= extent.createTest(result.getMethod().getMethodName(),getTestDetails(result));

				test.getModel().setStartTime(getTime(result.getStartMillis()));				
				test.getModel().setEndTime(getTime(result.getEndMillis()));

				String testclass = result.getTestClass().getName();
				test.assignCategory(testclass);
				
				// Attach execution logs files here
				//test.log(status, "just rams msmsms");

				if (result.getThrowable() != null) {
					test.log(status, result.getThrowable());
					try {
						String failurePic = result.getAttribute("screenshot").toString();
						//screenshot title is not working at the moment
						test.addScreenCaptureFromPath(failurePic);
						
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				} else {
					test.log(status, "Test " + status.toString().toLowerCase()
							+ "ed");
				}

			}
		}
	}

	private Date getTime(long millis) {
		Calendar calendar = Calendar.getInstance();
		calendar.setTimeInMillis(millis);
		return calendar.getTime();
	}
	
	
	private String getTestDetails(ITestResult result)
	{
		String[] parameters = result.getParameters()[0].toString().split(",");
		String testData = ""	;
		for (String data : parameters) 
		{
			testData=testData+data.toString()+"<br>";;
		}
		String details = "<b><u>"+ result.getMethod().getDescription()+"</u></b>"+
		//breaking line here to display test data in next line
				"<br>"+testData ;
		return details;
	}
	
	private ExtentSparkReporter setSparkConfig(String sparkpath)
	{
		ExtentSparkReporter spark = new ExtentSparkReporter(sparkpath);
		spark.config().setReportName(System.getProperty("appBuild", "AutomationReport- Build xyz"));
		spark.config().setDocumentTitle("AutomationReport");
		spark.config().enableTimeline(false);
		String configFile = SeleniumCommands.getFrameworkDir()+"/src/test/resources/extentReport/spark-config.xml";	
		spark.loadXMLConfig(configFile);
		//spark.config().setTheme(Theme.DARK);
		
		return spark;
	}
	
	
	private void setSystemInfo()
	{
		extent.setSystemInfo("TestEnv", System.getProperty("appURL"));
		extent.setSystemInfo("BrowserType", System.getProperty("browserType","Chrome"));
	}
		

}
`

**Comment by musanas** [comment]
This is the method adding the info
`					ExtentTest.log(Status status, String details)				
`

**Comment by anshooarora** [comment]
You are missing to set report times for events.  

```
test.getModel().getLogs().forEach(x -> x.setTimestamp(getTime(result.getEndMillis())));
```
