### ISSUE TITLE
Roboto font unavailable on 3.0.7

### ISSUE THREAD

**Issue by pchand-apttus** [extent-framework/extentreports-java#217]
Extent report 3.0.7 was working fine but recently have started getting the below error for the extent report.

This is a blocker for us,

![image](https://user-images.githubusercontent.com/63346558/88369252-3d515c80-cdad-11ea-9946-b6e06f361d01.png)

**Comment by anshooarora** [comment]
@pchand-apttus Version 3 is no longer supported and the latest version is 5.  Please consider upgrading.  

If that is not feasible, my recommendation is to use release 3.1.5 from [anshooarora/extentreports-java@6b052be](https://github.com/anshooarora/extentreports-java/tree/6b052be442a330e37c05a98714b1578a9f0bd157) and adding the fonts URL on [this line](https://github.com/anshooarora/extentreports-java/blob/6b052be442a330e37c05a98714b1578a9f0bd157/src/main/resources/com/aventstack/extentreports/view/html-report/head.ftl#L13).

```
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">.  
```
