### ISSUE TITLE
ExtentReport v5 test Status missing

### ISSUE THREAD

**Issue by casalribeiro** [extent-framework/extentreports-java#218]
Hi, I can't find `Status.DEBUG` or `Status.FATAL` in v5.
Were they removed?

**Comment by anshooarora** [comment]
@casalribeiro There have been a breaking changes in v5, please see here:  https://github.com/extent-framework/extentreports-java/wiki/Breaking-Changes

**Comment by casalribeiro** [comment]
You will make me change my framework because of that 😄 
Thanks for the fast response 👍

**Comment by anshooarora** [comment]
I can add `DEBUG` as for all supported reporters, there is little to no downstream impact.  `FATAL` is removed as no test framework outputs this status, the highest is `FAIL`.
