### ISSUE TITLE
Extentreports 5.0.0 is not backward compatible

### ISSUE THREAD

**Issue by rahgir** [extent-framework/extentreports-java#219]
Hi @anshooarora ,
This could be probably a question.

 After upgrading to extentreports- 5.0.0, I see below classes are not resolved which I used to use in junit tests. Unfortunately, my integration and cucumber tests are in same project and I was planning to use the code way for my junit integration test and cucumber-adapter4: 1.2.0 for my cucumber tests. Now I am really stuck as these classes are now unresoved.  cucumber-adapter4 version 1.2.0 is dependent on extentreports 5.0.0. Any pointers will be really helpful.

import com.aventstack.extentreports.ExtentReports
import com.aventstack.extentreports.convert.TestModelReportBuilder
import com.aventstack.extentreports.reporter.ExtentKlovReporter
import com.aventstack.extentreports.reporter.ExtentSparkReporter
import com.aventstack.extentreports.reporter.JsonFormatter
import com.aventstack.extentreports.reporter.configuration.Protocol
import com.aventstack.extentreports.reporter.configuration.Theme

**Comment by anshooarora** [comment]
@rahgir If you are using the adapter, these imports should not break anything in your code.  Can you share your pom.xml?

**Comment by rahgir** [comment]
sent mail. Please check. thanks !

**Comment by anshooarora** [comment]
Release `5.0.1` is now available,  please update.
