### ISSUE TITLE
Is there a way to show tags on the "tests" view like it used to in 4.0.x versions? 

### ISSUE THREAD

**Issue by anuragdeshpande** [extent-framework/extentreports-java#220]
I am looking for config settings if any that would allow me to show the tags assigned to a test with in the logs view like it used to do in the past. Sorry raising a ticket as I am unable to find any documentation to read

**Comment by anshooarora** [comment]
@anuragdeshpande  Tags are automatically shown under the TestName on the right-hand side.  Are they not visible for you?

**Comment by anuragdeshpande** [comment]
No this is how it looks like for me at the moment. That test has around 6-8 tags. they are visible under the tag view but not on the report itself

![image](https://user-images.githubusercontent.com/3684197/88903423-eb775f00-d210-11ea-96ab-54d0299e06ff.png)

**Comment by anuragdeshpande** [comment]
also I have no idea why/how the run time is showing in seconds. I have made no config changes asking for it. referring to 741.048 seconds on the screenshot above.

**Comment by anuragdeshpande** [comment]
is this fixed? is there a new version update that I need to look at?

**Comment by anuragdeshpande** [comment]
This has been fixed, I was able to confirm the changes are working in 5.0.2 version. Thank you

**Comment by anshooarora** [comment]
Thank you :) yes this was part of `5.0.2`.  See [changelog](https://github.com/extent-framework/extentreports-java/blob/master/CHANGELOG.md#502).
