### ISSUE TITLE
NullPointerException when init ExtentSparkReporter

### ISSUE THREAD

**Issue by oren451** [extent-framework/extentreports-java#221]
Hi Anshoo, I receive this exception when i init new ExtentSparkReporter,
My code is this:
ExtentSparkReporter htmlReporter = new ExtentSparkReporter(reportFilePath);
            htmlReporter.config().setDocumentTitle(reportFilePath);
            htmlReporter.config().setReportName(versionNumber);
            extent.attachReporter(htmlReporter);

java.lang.NullPointerException
        at com.aventstack.extentreports.reporter.AbstractFileReporter.<init>(AbstractFileReporter.java:45)
        at com.aventstack.extentreports.reporter.ExtentSparkReporter.<init>(ExtentSparkReporter.java:51)

**Comment by anshooarora** [comment]
This error originates from the [constructor](https://github.com/extent-framework/extentreports-java/blob/master/src/main/java/com/aventstack/extentreports/reporter/ExtentSparkReporter.java#L51) and happens from `ExtentSparkReporter htmlReporter = new ExtentSparkReporter(reportFilePath);`.

Can you check the `reportFilePath`?  I just ran the below to check:

```
ExtentReports extent = new ExtentReports();
ExtentSparkReporter spark = new ExtentSparkReporter("target/spark.html");
spark.config().setDocumentTitle("DocTitle");
spark.config().setReportName("1.0");
extent.attachReporter(spark);
extent.createTest("Test1").assignCategory("Cat1").pass("");
extent.flush();
```

**Comment by oren451** [comment]
Oh got it i need to give him relative path.
Maybe is good idea to create by default file where to project directory is, if not mention else.

**Comment by anshooarora** [comment]
You replied within seconds of mine, awesome, glad its resolved.
