### ISSUE TITLE
How to add S3 Link to our IMG Reporter?

### ISSUE THREAD

**Issue by awang101** [extent-framework/extentreports-java#229]
Hi,

We are currently using extent reports 3.1.5 and latest version of KLOV. We are currently migrating to the newest Extent Reports of 5.0.1. We currently are uploading all our image files to S3 after our Java Selenium project finishes. However with the introduction of different suites we would like to separate the buckets. 

Is there anyway in the newest version of Extent reports to reference our images in a S3 bucket in the reports?

`img = MediaEntityBuilder.createScreenCaptureFromPath("./../reports/images/" + snapNumber + ".png").build();`

The following code is used, but unfortunately we receive broken links in our HTML document, is there anyway to change the URL path of extent reports (over writing our html) document to have the s3 linkouts?

Thank you

**Comment by anshooarora** [comment]
Is the path correct?  Permissions valid?  The same principles of using relative paths would apply here.
