### ISSUE TITLE
in v4.0.6 timeline not working

### ISSUE THREAD

**Issue by mmajcherczyk** [extent-framework/extentreports-java#23]
![test report - mozilla firefox 2018-12-28 14 44 50](https://user-images.githubusercontent.com/6592592/50517181-484bea00-0aaf-11e9-9604-a8685086afdc.png)

in v4.0.5 is ok
![kraken test report - mozilla firefox 2018-12-28 15 15 44](https://user-images.githubusercontent.com/6592592/50517988-7e8b6880-0ab3-11e9-9455-f00f2cff8a3a.png)

**Comment by mmajcherczyk** [comment]
you're right, in 4.0.7-SNAPSHOT is ok

**Comment by anshooarora** [comment]
Thank you

**Comment by smaity91** [comment]
Happening again for SparkReporter. I have a report created for a suite running for around 5 mins. Timeline showing only upto 0.35s which is same as as I analyzed the **last failed test** case of my suite. PFB the screenshot of timeline part.
![image](https://user-images.githubusercontent.com/49211969/83249441-da758780-a1a6-11ea-8b61-22bd9c680d06.png)
