### ISSUE TITLE
[Question]ExtentSparkReporter does not show timeline in dashboard view

### ISSUE THREAD

**Issue by mchundi** [extent-framework/extentreports-java#233]
I am using ExtentSparkReporter 5.0.1 and I am not able to see the timeline.
sparkReporter.config().isTimelineEnabled() returns true and I see the below warning on browser console:
`DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/gh/extent-framework/extent-github-cdn@5cf22a596531402644b8523470526952516f345f/spark/js/bootstrap.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`
Tried enabling the timeline using : `sparkReporter.config().setTimelineEnabled(true);` but it doesn't work

**Comment by anshooarora** [comment]
Timeline is currently not available,  marking this as an enhancement.

**Comment by anshooarora** [comment]
This feature will be available beginning `5.0.4`.
