### ISSUE TITLE
ExtentAventReporterConfiguration class Missing

### ISSUE THREAD

**Issue by prakashpqa** [extent-framework/extentreports-java#234]
In the javadoc of version 4 there is a mention of ExtentAventReporterConfiguration class file. And in the ExtentAventReporter there is a mentioned of config() method of type ExtentAventReporterConfiguration. 

http://extentreports.com/docs/versions/4/java/javadoc/

Both are missing when I downloaded jar from mvn repo.

**Comment by anshooarora** [comment]
Avent is pro-only.  See [here](http://extentreports.com/docs/versions/4/java/). You can use `ExtentSparkReporter`.
