### ISSUE TITLE
Indentation is not proper. 

### ISSUE THREAD

**Issue by nisargdave1993** [extent-framework/extentreports-java#236]
1. Parent Extent Test Name is going out of the window
2. #test-id=1 is appearing
3. start-end time & group tags are overlapping

![image](https://user-images.githubusercontent.com/46313076/90189024-19949b80-ddda-11ea-997e-db35f5cf4c25.png)

4. Child Extent Test group tags are touching the box end line. not visually correct.

![image](https://user-images.githubusercontent.com/46313076/90189212-64aeae80-ddda-11ea-9691-1fb06e2a02f2.png)

Attaching images

**Comment by anshooarora** [comment]
1. Fixed
2. Anchors, see here:  https://github.com/extent-framework/extentreports-java/wiki/ExtentSparkReporter#anchors
3. Fixed
4. Fixed

Changes available from:

```
<dependency>
  <groupId>com.aventstack</groupId>
  <artifactId>extentreports</artifactId>
  <version>5.0.4-SNAPSHOT</version>
</dependency>
```

**Comment by nisargdave1993** [comment]
@anshooarora: is 5.0.4-SNAPSHOT released ? I am not able to download this dependency.

For Anchors: I see they are not clickable ? Am I missing anything here ?

**Comment by anshooarora** [comment]
You may need to enable download of SNAPSHOT releases from maven/conf/settings.xml as shown https://stackoverflow.com/a/7717234/4533615

Making anchors clickable is a good idea, these are to be copied only at present and manually appended at the end of the URL.
