### ISSUE TITLE
Visually not appealing from previous versions (for ex: 4.1.1)

### ISSUE THREAD

**Issue by nisargdave1993** [extent-framework/extentreports-java#238]
I know this is not an issue and I am sorry for putting it as an issue. 
I know you guys have worked hard to release this new version.
However I feel this new look and feel is not prominent in nature, not clean & not visually appealing. 
Seems like all elements are settling on html report on ad-hoc basis. Not feel good factor. 

I am a genuine supporter & user of extent Report library & closely following this space. Hence expressing my view. Please don't take it otherwise. Thanks!

**Comment by anshooarora** [comment]
Thank you!  I appreciate your feedback.  As with any iteration, it takes several revisions to come to a consensus where most users are happy with the look and feel.  Version 5 is new and the SparkReporter is also relatively new, so I will definitely take visual cues from the previous gen reports and incorporate the good elements.

So the battle is between the 2?  [v5.0.3](http://extentreports.com/docs/v5/wiki/spark/spark.html) vs [v4.1.1](http://extentreports.com/docs/v5/wiki/spark/v4Html.html)

**Comment by nisargdave1993** [comment]
I completely understand our points & thanks for taking the feedback. 
No, the battle is not between these 2 versions. I just gave reference of 4.1.1 since I personally feel it is gem to watch. :) 
Thanks !
