### ISSUE TITLE
timeline is broken if test it lasts longer than 30 minutes

### ISSUE THREAD

**Issue by mmajcherczyk** [extent-framework/extentreports-java#24]
![kraken test report - mozilla firefox 2018-12-28 23 08 46](https://user-images.githubusercontent.com/6592592/50529522-c501b700-0af5-11e9-8cc4-2cf6132818ec.png)

**Comment by anshooarora** [comment]
@mmajcherczyk

Other than the starting point being zero at start, which must be fixed, what else is not working correctly?

**Comment by mmajcherczyk** [comment]
I run 1 test, the timeline shows many tests

**Comment by anshooarora** [comment]
Would it be possible for you to share the report?  You can email me at anshooarora@gmail.com.
