### ISSUE TITLE
Do we have any guide to set up Klov and Extent Report v5

### ISSUE THREAD

**Issue by hainguyenh** [extent-framework/extentreports-java#242]
Hello Anshooarora,
Do we have any document for setting the Klov report with new version(v5)? I try to follow your step your guide on the Readme but it still said cannot connect to MongoDB
Env:
MacOS: 10.14.6
Mongo DB: Community 4.4
Java: 1.8
Docker image: docker pull anshooarora/klov:1.0.1

YML:

> version: '2'
services:
  klov:
      image: anshooarora/klov:1.0.1
      container_name: klov
      environment:
        - SPRING_DATA_MONGODB_URI=mongodb://localhost:27017
      ports:
        - 80:80

> docker-compose up
Creating network "tiq-automation_default" with the default driver
Creating klov ... done
Attaching to klov
klov    |  _     _             
klov    | | |__ | |  ___   _ _ 
klov    | | / / | | / . \ | | |
klov    | |_\_\ |_| \___/ |__/ 
klov    | 
klov    | 2020-08-16 05:51:46,644 INFO  [main] org.springframework.boot.StartupInfoLogger: Starting KlovApplication v1.0.1.RELEASE on 4f8d5cd789a5 with PID 1 (/klov.jar started by root in /)
klov    | 2020-08-16 05:51:46,653 INFO  [main] org.springframework.boot.SpringApplication: No active profile set, falling back to default profiles: default
klov    | 2020-08-16 05:51:48,427 INFO  [main] org.springframework.data.repository.config.RepositoryConfigurationDelegate: Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
klov    | 2020-08-16 05:51:48,663 INFO  [main] org.springframework.data.repository.config.RepositoryConfigurationDelegate: Finished Spring Data repository scanning in 221ms. Found 10 MongoDB repository interfaces.
klov    | 2020-08-16 05:51:50,601 INFO  [main] org.springframework.boot.web.embedded.tomcat.TomcatWebServer: Tomcat initialized with port(s): 80 (http)
klov    | 2020-08-16 05:51:50,629 INFO  [main] org.apache.juli.logging.DirectJDKLog: Initializing ProtocolHandler ["http-nio-80"]
klov    | 2020-08-16 05:51:50,631 INFO  [main] org.apache.juli.logging.DirectJDKLog: Starting service [Tomcat]
klov    | 2020-08-16 05:51:50,632 INFO  [main] org.apache.juli.logging.DirectJDKLog: Starting Servlet engine: [Apache Tomcat/9.0.34]
klov    | 2020-08-16 05:51:50,924 INFO  [main] org.apache.juli.logging.DirectJDKLog: Initializing Spring embedded WebApplicationContext
klov    | 2020-08-16 05:51:50,925 INFO  [main] org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext: Root WebApplicationContext: initialization completed in 4088 ms
klov    | 2020-08-16 05:51:51,728 INFO  [main] com.mongodb.diagnostics.logging.SLF4JLogger: Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
klov    | 2020-08-16 05:51:51,863 INFO  [cluster-ClusterId{value='5f38c977498f774d15abb5a2', description='null'}-localhost:27017] com.mongodb.diagnostics.logging.SLF4JLogger: Exception in monitor thread while connecting to server localhost:27017
klov    | com.mongodb.MongoSocketOpenException: Exception opening socket
klov    |       at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:70)
klov    |       at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:128)
klov    |       at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117)
klov    |       at java.lang.Thread.run(Thread.java:748)
klov    | Caused by: java.net.ConnectException: Connection refused (Connection refused)
klov    |       at java.net.PlainSocketImpl.socketConnect(Native Method)
klov    |       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
klov    |       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
klov    |       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
klov    |       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
klov    |       at java.net.Socket.connect(Socket.java:589)
klov    |       at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64)
klov    |       at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:79)
klov    |       at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65)
klov    |       ... 3 common frames omitted
klov    | 2020-08-16 05:51:52,556 INFO  [main] org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexResolver$1: Found cycle for field '_id' in type 'Test' for path 'parentTest -> parentTest'
klov    | 2020-08-16 05:51:52,558 INFO  [main] org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexResolver$1: Found cycle for field '_id' in type 'Test' for path 'parentTest -> nodes -> parentTest'

I also try to change localhost to 120.0.0.1 but the issue still occurred.

**Comment by hainguyenh** [comment]
I found the issue :'( that I configure the IP of mongo not correct...
The mongo install in my local machine not docker local so that the IP is not correct ....

**Comment by anuragdeshpande** [comment]
@anshooarora I have a similar question as well. This is my first time using the klov reporter. having a really hard time figuring out how the projects are created in the server. in my current config, I am creating the klov reporter when the testNG suite is started (onStart method in suite) and flush the extent reporter at the end of the suite (onFinish method in suite)

issue 1: a suite.xml file containing multiple <test> tags is started. I am getting a new project created in the klov server for every <test> tag in suite xml.
issue 2: how to control the logging level in the logger? I am getting all logs printed at debug level at the moment. 
issue 3: I have also reached out for a purchase enquiry almost a week ago and still havent heard back on it. I was hoping a purchase would get me some proper documentation

some kind of user manual or how-to document would be really helpful. Please help
