### ISSUE TITLE
Do we have any user/permission feature for Klov

### ISSUE THREAD

**Issue by hainguyenh** [extent-framework/extentreports-java#243]
As ver 0.2 0.3 of Klov,
I remember we have a function to create the user. So do we have any feature for log in/view/delete on Klov?
If we have 2 projects for 2 clients, we should have limit access for them. And with these features, they only see the project which assigns for the also view only. Any idea to develop this feature for Klov?

**Comment by anshooarora** [comment]
@hainguyenh This feature is not currently available in this version.  Although this is part of the product roadmap and will be available soon.

**Comment by anshooarora** [comment]
Please track this enhancement here: https://github.com/extent-framework/klov/issues/61
