### ISSUE TITLE
How to update existing test during re-run

### ISSUE THREAD

**Issue by ghadigaonkarnilesh** [extent-framework/extentreports-java#25]
Hi,
This is same as many users reported earlier.We would need feature so that during rerun of failed tests when we use same report(earlier report) , if rerun passes it should overwrite earlier fail status.Please note that this is very important feature as customer always wants single report for execution (which we can create setting flag as False during initialization) but it should also contain final status as customer is interested in that only.
Test may fail due to scripting issues which test engineer would fix and rerun and we want only final status to be available in report.  Can this be taken on priority?

Thanks,
Nilesh

**Comment by foursyth** [comment]
This feature is not available yet, but is planned for a future release.  

If you would like this sooner, I would suggest sending in a pull request.

**Comment by ghadigaonkarnilesh** [comment]
Hi.
Please note that when you do enhancement it should work in below scenario-
1.When you point to existing report using flag as false , and rerun test , it should overwrite test's earlier result.
2.I do see that there is method 'RemoveTest' in v4 but it requires extendtest object as input.
3.When we point to earlier report we can not have its extendtest object as it would get destroy with earlier session.We should be able to remove test with test name string as input.
4. Alternativly you can enhance starttest method which takes string input.

**Comment by sahi449** [comment]
I tried placing custom logo in report , it worked fine in v3 but it's not working in v4. Could you please share the code snippet to add custom logos through config file

**Comment by ghadigaonkarnilesh** [comment]
Hi Anshu,
I am not sure why you are not prioritising this. Please note , you have created excellent reports. I gave mutiple Demos to customer and we always get comment that we should share this report with all stakeholders after execution, which we are unable to do because it contains earlier fail results if test is ran mutiple times.
In my opinion, we automation engineer doesnt need such flashy reports ,even excel reports would suffice. We use extent report this as it is impressive for customer and if we can share it with them then it kills point.
This is open issue for us and we have added entry in our issue tracker as open issue.
So please dont mark as stale and fix it.

Thanks,
Nilesh

**Comment by foursyth** [comment]
@ghadigaonkarnilesh

I would highly suggest you to send in an enhancement request. This is not a priority for us because of Klov - which enables this feature out of box.

**Comment by anshooarora** [comment]
I had planned to create a json file for the session and using that to parse when recreating the HTML file.   Now, doing so is not so straight forward because of the tree structure and hierarchical relationships between the elements.  Using Gson is the most straight-forward but it does not support same element hierarchies so - its a little intensive serializing per element.

As @foursyth said,  we will welcome any pull requests.  I am leaving this feature up to the community to decide the best possible implementation.

**Comment by ghadigaonkarnilesh** [comment]
@anshooarora   @foursyth 
while exploring klov , I found solution for this. It seems Klov also tracks all test's status and if test is ran multiple times , it makes mutiple entries for same test which again cause same issue that it can not be used as final status . I see that in klov , you have added functionality to add cause to failed tests (Script Issue etc and we can create our own issue type also).

Can we enhance klov to add tags to all tests (manually using UI,even for passed and skipped test) and then see tests that belong to that tag. Advantage is after entire execution , we can create tag Final_Status and attach this tag to all tests where their status can be taken as final. This means klov will have entire history of all build runs but we can also see final status for that project. Note , it is necessary that once we select particular tag , it should  show all tests of that  project (not build , as  everyone will create separate project for each release regression). This mean Final_Status tag will allow to see final status of all tests for that release regression.

Please think , this will be really good enhancement as it will allow us to share klov with other  stakeholders where they can see final status of particular project.

**Comment by anshooarora** [comment]
Feature available starting `4.10.0-SNAPSHOT`, see #103 for details.

**Comment by mahesh-thummala-fluke** [comment]
Hi @anshooarora I am using the latest ExtentRepots 4.1.0, which is available as a nuGet package in visual studio.

just like @ghadigaonkarnilesh  we have Two requirements for our reports.

1) Append existing report (Say if I have 2 testcases, when I run the First test it generate a Html Report
 and now when I run the second Testcase if it fails it should not be appended To the existing Report
 but when we fix and rerun it should be appended to the Existing report if it passes).

2) Printable Version of the HTML report (Once the HTML Report is generated, when we want to print
 it, I can only see the first Testcase log messages and screenshot but Not The remaining Testcases.
 is there a way, when we print the html report it should be able to print all the testcases log messages with screenshots?)

If the above Two requirements Can be achievable by pro License version Please let me know.

**Comment by sampada-datey** [comment]
test-output generates testng extent report but unfortunately github workflow only overwrites target/surefire-reports can we not have test-output folder overwritten after execution of test ?
I am only able to update target/surefire-reports and not test-output folder which actually works in eclipse
