### ISSUE TITLE
Code is working fine on v3.1.5 but not working on 5.0.1

### ISSUE THREAD

**Issue by mananveoci** [extent-framework/extentreports-java#257]
`public void onTestSuccess(ITestResult result) {
	
		String methodName = result.getName().trim();
		String filePath = System.getProperty("user.dir") + "/Passed Screenshots/";
		try {
			takeScreenShot(filePath, methodName, driverMap.get(result.getTestClass().getRealClass().getSimpleName()));
		} catch (Exception e) {
			e.printStackTrace();
		}

		Log logObj = new Log();//getTest(Reporter.getCurrentTestResult().getInstanceName().replace(".", " ").split(" ")[Reporter.getCurrentTestResult().getInstanceName().replace(".", " ").split(" ").length-1].trim()));  
		logObj.setDetails("Test method " + result.getMethod().getMethodName() + " completed successfully");
		logObj.setStatus(Status.PASS);
	
		getTest(Reporter.getCurrentTestResult().getInstanceName().replace(".", " ").split(" ")[Reporter.getCurrentTestResult().getInstanceName().replace(".", " ").split(" ").length-1].trim())  .getModel().getNodeContext().get(testMethodCount.get()).getLogContext().add(logObj);

		med	= new ScreenCapture();
		med.setMediaType(MediaType.IMG);
		med.setPath(extentScreen);
		getTest(Reporter.getCurrentTestResult().getInstanceName().replace(".", " ").split(" ")[Reporter.getCurrentTestResult().getInstanceName().replace(".", " ").split(" ").length-1].trim())
		.getModel().getNodeContext().get(testMethodCount.get()).setScreenCapture(med);
	}`

This code is working good on "3.1.5" and I update extent report version 5.0.1

getting below error.
Error 1 : MediaType cannot be resolved to a variable.
Error 2 : The constructor ScreenCapture() is `undefined`
Error 3 : The method getNodeContext() is undefined for the type Test

**Comment by anshooarora** [comment]
@mananveoci I am not quite sure what you are trying to achieve from your code.  Please see docs here since there have been several breaking changes between version 3 -> 5:  https://www.extentreports.com/docs/versions/5/java/index.html#logging-screenshots
