### ISSUE TITLE
Spark Extent Report: Can I rename Tests to features and Can I add pie chart on Tests screen just like the HTML report

### ISSUE THREAD

**Issue by vishal131991** [extent-framework/extentreports-java#262]
@anshooarora 
I wanted to rename Tests to Features in side menu panel, Is it possible in spark report? If yes then how can I achieve this?
Also
Can I show the pie chart on Tests screen, l wanted to show Features, Scenarios and Steps pie chart on Tests screen just like we display them html report. ?

I am using com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter: and 
     <dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports-cucumber4-adapter</artifactId>
    <version>1.1.0-SNAPSHOT</version>
       </dependency>

**Comment by anshooarora** [comment]
@vishal131991 

That should be the default behavior when you use the cucumber-adapter.  Can you share a sample report file?
