### ISSUE TITLE
Scenario Outline shows Incorrect / Doubles Count in Dashboard View - extentreports-cucumber6-adapter 

### ISSUE THREAD

**Issue by bughunter7** [extent-framework/extentreports-java#263]
When Running a Scenario Outline the count in the dashboard is incorrect . it displays double count to what scenario is executed also tags section shows same scenario title twice.

**Please find Below link for report screenshots –**
https://github.com/bughunter7/ExtentReportIssue

**Dependency used –**

tech.grasshopper
extentreports-cucumber6-adapter
1.2.0
test

![96265766-7fbcbb00-0fe3-11eb-8446-b5d85f4d7924](https://user-images.githubusercontent.com/55976995/96571433-2f966f00-12e9-11eb-9a6f-3cfd1c898f9c.png)

Feature: user clicks on salesorder

  @salesorder @reg
  Scenario Outline: user clicks on orders
    Given user is on landing page
    And he enters his userid and password
    Then he is redirected to dashboard adminpage
    And he clicks on sales
    And he clicks on orders
    And clicks on create new order
    Then he enters the <email id> and <userid>
    And clicks on search button
    And clicks on search results
    Then selects Godirecttrade as a store
    And clicks on add products
    Then searches for <sku>
    And selects the product from checkbox
    And clicks on add selected products to order
    And enters the purchase order no <po number>
    And clicks on link get shipping methods and rates
    And selects the radio button
    And clicks on submit order
    Then message visible is you created the order
    And order no is displayed

    Examples: 
      | email id              | userid | sku                                | po number |
      | tom@mailinator.com |     70 | abc-bat-4-1000-2118860-4-106-a0820 |      1234 |

@anshooarora 
Please let me the solution its urgent .also let me know if any more info required from my end awaiting for your response 🙂

**Comment by anshooarora** [comment]
ExtentReports version?  The screenshots in the repo you have shared are for a reporter which is not available in the latest version 5.

**Comment by bughunter7** [comment]
@anshooarora  - I am using  extentreports-cucumber6-adapter   Version  1.2.0 

Reporter used properties - **extent.reporter.html.out**=target/test-output/HtmlReport/ExtentHtml.html

on using only  " **Scenario outline** " as a keyword in feature file  the report generates an incorrect count  as per attached screenshot above  .
as of now I am using " **Scenario** " in feature files to avoid incorrect count But maintenance takes time it could be lot more easier if I get accurate count using " **Scenario Outline** " . 

Please let me know if I need to upgrade to some other version / if you require anymore details.

Thanks :)

**Comment by grasshopper7** [comment]
U can try with 2.5.0 but HTML report is deprecated with extent 5. U will have to use the Spark report.

**Comment by grasshopper7** [comment]
U should try with 2.6.0 version for attaching images as Base64 encoded string src. U need to add the following property in extent.properties - extent.reporter.spark.base64imagesrc=true. Default is false. U just need to use scenario.embed() in step definition instead of the current code.
