### ISSUE TITLE
Switching theme is not working in Extent Reports 5.0.4

### ISSUE THREAD

**Issue by amuthansakthivel** [extent-framework/extentreports-java#264]
In older versions we have the option to switch themes with a single click but in this version it is not possible. Even the shortcut of 1 which is mentioned in the docs to switch themes is not working.
But the other shortcuts like P,F,S are working fine.

**Comment by anshooarora** [comment]
Please use the "L" key.  

Docs:  http://www.extentreports.com/docs/versions/5/java/spark-reporter.html
