### ISSUE TITLE
Alignment issue in authors table in the dashboard view.

### ISSUE THREAD

**Issue by amuthansakthivel** [extent-framework/extentreports-java#265]
When we assign a name to a test using assignAuthor method and if the name is having more than 15 characters, the alignment of the table in the dashboard view is not appealing. 

![image](https://user-images.githubusercontent.com/30618052/96333148-e4305680-1085-11eb-81a9-dd99d7e2a5c9.png)

**Comment by anshooarora** [comment]
Starting `v5.0.6` this and other such cards would span 6 columns (out of 12) on large viewports and 12 columns for 992px and smaller.

![image](https://user-images.githubusercontent.com/4107384/101328458-df398900-3824-11eb-87ae-d6469f57955c.png)

**Comment by amuthansakthivel** [comment]
Thank you for fixing the issue. 

I have made some efforts to teach the community about this awesome library. Not many people knows about all the latest features in extent report. I have made an complete playlist on youtube about extent reports.

https://www.youtube.com/playlist?list=PL9ok7C7Yn9A-yUEnE62gOQ2B4pL3gsC28

**Comment by anshooarora** [comment]
Thank you for creating such wonderful videos for the community and I highly appreciate your hard work.  I saw all of them and they are indeed enticing and I learned so much. Cheers

**Comment by amuthansakthivel** [comment]
Thank you for your kind words. I would be happy even if you want to feature this video playlist in the extent reports site.

Cheers :)

**Comment by anshooarora** [comment]
> Thank you for your kind words. I would be happy even if you want to feature this video playlist in the extent reports site.
> 
> Cheers :)

Ok.  Let me see what I can do.

**Comment by amuthansakthivel** [comment]
Thanks a lot Anshoo.

 I have added more videos on how to integrate extent reports with selenium
framework and custom annotations.

Using custom annotations and extent report:

https://youtu.be/8zD2ASUdLDg

https://youtu.be/clgEviKfjHk

Integration with framework :


https://youtu.be/uDCub7oISA8

https://youtu.be/FIHWcmE5LRE

https://youtu.be/l9uQopX1Kuc

Please check this out and let me know for any changes,

Thanks,
Amuthan
Testing Mini Bytes.

**Comment by anshooarora** [comment]
@amuthansakthivel  Sorry for the delay in this, I have not had much time to focus on ExtentReports. 

Please see (in very initial phases, but hopefully this will grow):  https://www.extentreports.com/community/
