### ISSUE TITLE
Having Issues Running Parallel Test Cases Not Appending Tags Correctly

### ISSUE THREAD

**Issue by awang101** [extent-framework/extentreports-java#266]
Hi,

For my code

```
	@BeforeMethod(groups = { "NBC"})
	public void beforeMethod(String browser, String platform, String applicationUrl) {
		
			test = startTestModule(testCaseName + " // [" + applicationUrl + "] - [" + browser + " - " + platform + "]",
					testDescription);
	

			test.assignCategory("NBC");
			

		startApp(browser, platform, applicationUrl, testCaseName);

	}
```

We spin up the test cases, but certain test cases finish earlier than the others. In this case I believe since some of these test cases finish earlier than the others, it cannot find the associated tags so it creates a new one. As a result some of the other are tagged correctly but there are others that are not. Is there anyway we can fix this scenario?

<img width="405" alt="Screen Shot 2020-10-19 at 1 11 21 PM" src="https://user-images.githubusercontent.com/45081352/96488900-b45f8b00-120c-11eb-80d8-4a2927acd6aa.png">

**Comment by anshooarora** [comment]
I will research this, but it definitely does not look correct.

**Comment by anshooarora** [comment]
Btw, you have not provided the version info.
