### ISSUE TITLE
check if a Child Node already exist

### ISSUE THREAD

**Issue by VladiKonovalov** [extent-framework/extentreports-java#268]
![image](https://user-images.githubusercontent.com/42347278/98921224-b2ba7780-24d9-11eb-9bc1-8e74ab855e0a.png)
i have a TestParents and he have childsTests , but i want to add to existing child test new line 

in the picture example i want to add to Create_ACCOUNT new lines , but before it i want to check if he already exist

**Comment by anshooarora** [comment]
@VladiKonovalov - you can check for nodes using:

```
ExtentTest test = extent.createTest("X");
test.createNode("Y");

Boolean b = test.getModel().getChildren()
  .stream().anyMatch(x -> x.getName().equals("Y"));
```

**Comment by VladiKonovalov** [comment]
can you tell me with witch version you use ? cause i with 3.1.5
