### ISSUE TITLE
Unable to update the charts when warning status is overwritten

### ISSUE THREAD

**Issue by anks061409** [extent-framework/extentreports-java#27]
Dependency used:

<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.relevantcodes</groupId>
			<artifactId>extentreports</artifactId>
			<version>2.41.2</version>
		</dependency>

Steps to reproduce:

1. Generate a report with warning status 
2. Add a JS code :+1: 
$('.test.warning').each(function() {
					$(this).addClass('pass').removeClass('warning'); 
				}); 
				$('.test-status.warning').each(function() {
					$(this).addClass('pass').removeClass('warning').text('pass with warning'); 
				});
				
				$('.tests-quick-view .status.warning').each(function() {
					$(this).addClass('pass').removeClass('warning').text('PASS'); 
				});
				testSetChart();

Error : unable to find the testSetChart

**Comment by anshooarora** [comment]
Please properly format your post.  Are you using version 2 and 3, both?

**Comment by anshooarora** [comment]
Closing due to no response. Please feel free to reopen this or a new issue if you still need help.
