### ISSUE TITLE
Scrollbar doesnot appear on right side for Extent Reports

### ISSUE THREAD

**Issue by SaiPrasanthN** [extent-framework/extentreports-java#272]
When I open Extent spark report, scrollbar doesn't appear to scroll to down to view all the nodes present on right side.
For ExtentHTML reporter, there is a scroll bar present by default on the right side to scroll down to view the scenarios. 
I am unable to see it for ExtentSparkReporter

**Comment by anshooarora** [comment]
@SaiPrasanthN 

Can you share a sample report file?
