### ISSUE TITLE
setEncoding not working on ExtentSparkReporter on 5.0.6

### ISSUE THREAD

**Issue by MatthieuTinnes** [extent-framework/extentreports-java#275]
Hello,
I can't change encoding on my report, It's stuck on the default UTF-8.
I've tried changing it with the configuration file or via java directly but without success.
spark.config().setEncoding("ANSI");

The other config like the theme, title or name work without any problem, only encoding is impossible to set. 

It was working on 4.1.3, I got this regression while upgrading.

**Comment by anshooarora** [comment]
@MatthieuTinnes 

This was indeed a regression, and is now fixed.  This will be part of the upcoming `5.0.7`.
