### ISSUE TITLE
it possible make a parentTest in the end of the list after the childrenTest?

### ISSUE THREAD

**Issue by VladiKonovalov** [extent-framework/extentreports-java#277]
I use the report for my QA Automation test,
i want to have the Parents that run "AFTEREACH" test that run .
sadly it still print them in top of the page 

as example in this picture the second "info" i want will be print after the child
![image](https://user-images.githubusercontent.com/42347278/103204948-1cafa480-4901-11eb-95a8-3c1e81d421ea.png)

**Comment by anshooarora** [comment]
@VladiKonovalov 

The default behavior is to aggregate events for each test nearby one another..  

One way to do this is to use a child-item to keep every group segregated and a bit of custom JS to open all nodes when viewing the test.

Example:

```java
ExtentSparkReporter htmlReporter = new ExtentSparkReporter("target/spark.html");
htmlReporter.config().setJs("$('.test-item').click(function() { $('.test-content .card-title > .node').each(function() { $(this).click() }) });");
ExtentReports extent = new ExtentReports();
extent.attachReporter(htmlReporter);

ExtentTest parent = extent.createTest("Test");
parent.createNode("A").pass("step 1");
parent.createNode("B").pass("step 2");
parent.createNode("C").pass("step 3");
parent.createNode("D").pass("step 4");

extent.flush();
```

The JS already include above.

```js
$('.test-item').click(function() { 
  $('.test-content .card-title > .node').each(function() { 
    $(this).click() 
  }) 
});
```
