### ISSUE TITLE
ExtentKlovReporter getReportId() not available in the new version. Alternative?

### ISSUE THREAD

**Issue by filipwoz** [extent-framework/extentreports-java#279]
I would like to log out the URL to my KLOV report in my code. The URL has a format like:
http://<HostName>:8080/projects/<ProjectName>/launches/<ReportName>/tests
How can I programatically extract the <ReportName>?
In extentreports version 4.1.3 I was able to do it by calling getReportId() of the ExtentKlovReporter class.
How can I do it in extentreports version 5.0.x?

**Comment by anshooarora** [comment]
@filipwoz 

You can use `klov.uri()` which returns the URI component of the build.  This field is available right after the 1st test is created.  If your host is `http://my-host.com`, you can use below for the fully qualified path of the build in Klov.

```java
String url = “http://my-host.com/” + klov.uri();
```
