### ISSUE TITLE
Concurrent test execution issues

### ISSUE THREAD

**Issue by AnatolyPopov** [extent-framework/extentreports-java#28]
When I try to use the framework with concurrent tests execution it slows down everything significantly.
This issue was introduced in version 3.
The thing is that log method in ExtentTest class is synchronized and internally calls log method from ExtentReports class that is also synchronized. Such way, as I understand, the framework is not able to add log messages concurrently at all and this is a blocking issue for me and I have to stay on version 2.

**Comment by foursyth** [comment]
@AnatolyPopov We are aware of this issue, and will release an alternate way to lock shared state.  However, I would still recommend using existing adapters for version 4 which would not raise such occurences.  We already have adapters for testng and cucumber.  Are you using either of these?

**Comment by AnatolyPopov** [comment]
@foursyth No, I'm not using these adapters. I had to write my own small test framework because of concurrency issues in TestNG and right now trying to migrate to JUnit5 to get an implementation of proper concurrent tests execution from scratch.

**Comment by foursyth** [comment]
Oh, I was not aware of TestNG having concurrency issues..  I would then recommend making sure your Extent instance and access to its tests are done one at a time which is what the adapters do to alleviate this. 

We will still release the fix but we would like your issue to be resolved in the meantime..  anything we can do other than fixing this in the interim, please let us know. Cheers.

**Comment by foursyth** [comment]
@anshooarora please chime in, this is the same issue raised by another user over email.

**Comment by AnatolyPopov** [comment]
@foursyth TestNG is not able to handle parallel parameterized tests properly and as I know this will not be ever fixed.

As for this framework - the only thing I managed to invent and try was to create a separate log messages queue, fill it form all the test threads and create a single consumer for this queue that will add log messages to the report. But as I remember the thing was that I was not able to set log message timestamp in advance in version 3, since it was set during Log object creation. I'm not sure how it works now, I did not managed to find the place in the code where it's set.

**Comment by anshooarora** [comment]
To set timestamp for logs:

```
test.getModel().getLogContext().getAll().forEach(x -> x.setTimestamp(x));
```

for tests:

```
test.getModel().setStartTime(x);
test.getModel().setEndTime(x);
```

Make sure to use the below setting in initialization so your overrides (above) persist:

```
extent.setReportUsesManualConfiguration(true);
```

**Comment by virenv** [comment]
@AnatolyPopov : A quick question, how did you figure out that the time increase is because of Synchronized Extent classes?

**Comment by AnatolyPopov** [comment]
@virenv Still using Extent Reports version 2.

**Comment by virenv** [comment]
@AnatolyPopov : The question was out of curisoity. Also to understand the threading model that you might have used in your test code. 
This also brings me to another question? Was there a specific fix made that resolved your issue ? because it seems that the methods that you mentioned are still Synchronized in the latest release.

**Comment by virenv** [comment]
@AnatolyPopov : Could please try out a fix in this branch: https://github.com/extent-framework/extentreports-java/pull/75 and see if you still get the concurrent test execution exception?

**Comment by virenv** [comment]
@AnatolyPopov : Can you take a look at the request above. We have pushed a change that should fix your issue. If possible can you test it out by taking the latest pull from master?
