### ISSUE TITLE
extentreports.com is insecure

### ISSUE THREAD

**Issue by kishaningithub** [extent-framework/extentreports-java#280]
Did not know where to report this hence putting this here. Kindly feel free to move this issue whereever it is relevant.

The site seems to use a self signed certificate rather than using one from CAs like Lets Encrypt. Kindly correct his.

Screenshots below.

<img width="495" alt="Screenshot 2021-02-05 at 12 35 52 PM" src="https://user-images.githubusercontent.com/763760/107000909-b1ce7480-67ae-11eb-8ed3-1f5e2ec527a1.png">

<img width="1080" alt="Screenshot 2021-02-05 at 12 38 14 PM" src="https://user-images.githubusercontent.com/763760/107001094-0eca2a80-67af-11eb-8800-fd03b5bc29ca.png">

**Comment by kishaningithub** [comment]
Also now, HTTPS site reports site not found where as HTTP site loads correctly

## HTTPS Site Screenshot

<img width="1167" alt="Screenshot 2021-02-05 at 12 44 45 PM" src="https://user-images.githubusercontent.com/763760/107001614-f1499080-67af-11eb-9605-87707de16aba.png">

## HTTP Site Screenshot

<img width="1432" alt="Screenshot 2021-02-05 at 12 46 41 PM" src="https://user-images.githubusercontent.com/763760/107001759-340b6880-67b0-11eb-9423-0873bd71cc8d.png">

**Comment by anshooarora** [comment]
Thank you.  This is now fixed.
