### ISSUE TITLE
How to add More Column and use it  while logging?

### ISSUE THREAD

**Issue by Irashad** [extent-framework/extentreports-java#281]
Hi, my purpose is to add more column to the table, I look for docs but i can't find solution.
Picture below shows what i want.  is there a way to add column? and add log information when execute test cases? I use IntellijIdea and java programming language, and i use Extent report (community) 
![Problem](https://user-images.githubusercontent.com/30791173/108178379-d109c200-711d-11eb-9435-96a19796b19b.png)

**Comment by anshooarora** [comment]
It is possible to add additional columns in version 5 only.  

Link:  https://www.extentreports.com/docs/versions/5/java/index.html#custom-logs
