### ISSUE TITLE
Category tags are being duplicated if multiple tests have same tag

### ISSUE THREAD

**Issue by kakkargaurav** [extent-framework/extentreports-java#282]
Hi @anshooarora 
While I am using version 5.0.6 the categories tags are being duplicated, when I am  adding new tests to the same tag.
 I upgraded form 3.1.5 to 4.0.0 to 5.0.6 the issue exists in both the later versions.

**Comment by anshooarora** [comment]
Can you share a sample report file that reproduces this issue?

**Comment by kakkargaurav** [comment]
The below method is being called in @beforetest annotation of TestNG 	

public static ExtentTest startTest(String testname, String[] groups) {
		ExtentTest test;
		test = extent.createTest(testname);
		test.assignCategory(groups);
		return test;
	}


![image](https://user-images.githubusercontent.com/58491542/108806362-9c9e7600-75f5-11eb-8d35-e9307bbf758f.png)

**Comment by anshooarora** [comment]
I am able to reproduce with:

```java
IntStream.range(1, 100).parallel().forEach(x -> {
  _extent.createTest("Test" + x).assignCategory(new String[] { "t1", 't2" }).pass("");
});
```

**Comment by kakkargaurav** [comment]
HI @anshooarora 

Is there a recommended workaround to avoid this for the meanwhile?

**Comment by anshooarora** [comment]
You can use the snapshot release:

```xml
<version>5.0.7-SNAPSHOT</version>
````

**Comment by kakkargaurav** [comment]
Hi @anshooarora,
Thank you for the quick turnaround. Has the above version been release to maven or is there any particular way of accessing this version.

**Comment by kakkargaurav** [comment]
Thanks I found how to enable snapshot by adding sonatype to repos

<profiles> <profile> <id>allow-snapshots</id> <activation><activeByDefault>true</activeByDefault></activation> <repositories> <repository> <id>snapshots-repo</id> <url>https://oss.sonatype.org/content/repositories/snapshots</url> <releases><enabled>false</enabled></releases> <snapshots><enabled>true</enabled></snapshots> </repository> </repositories> </profile> </profiles>
