### ISSUE TITLE
Display config error when i flush the report.

### ISSUE THREAD

**Issue by chetanJTH** [extent-framework/extentreports-java#284]
I have updated my report v 3.1.5 to 4.1.3
I have changes HTML to the logger.
but it gives me an error when I flush the report
please help to resolve the issue.
![Screenshot_4](https://user-images.githubusercontent.com/48850556/110097479-1805e180-7dc5-11eb-8b16-c5908bfea625.png)

**Comment by anshooarora** [comment]
@chetanJTH Please update to version 5 as I am unable to provide support for versions 4 and lower.

**Comment by chetanJTH** [comment]
@anshooarora okay

**Comment by chetanJTH** [comment]
@anshooarora tried upgrading to v5. but it gives me lots of error. can you give me basic code to configure v5.
