### ISSUE TITLE
Incorrect count is displaying for cucumber tags in cucumber extent adapter reports

### ISSUE THREAD

**Issue by qatestingravi** [extent-framework/extentreports-java#285]
Environment:
selenium:3.141.59
testng: 6.14.3
cucumber:6.8.1
extentreports-cucumber6-adapter: 2.6.0

Steps to reproduce:
1. Pull the project from below github url
https://gitlab.com/alltempprojects/tempuiwebjvtestngcucumberextentadapterreport.git
2. Run all features from testrunner file in src/test/java/testrunners/TestRunner.java

Expected:
Cucumber Tags count must be displayed correctly. 
Following cucumber tags count must be one (1)
@VerifyContactEmailInFooterFeature
@VerifyLinksUnderMyAccountInFooterFeature
@VerifySearchInHomePageTest

Actual:
Incorrect count is displaying for cucumber tags in cucumber extent adapter reports
Following cucumber tags count  is displayed as two (2)
@VerifyContactEmailInFooterFeature
@VerifyLinksUnderMyAccountInFooterFeature
@VerifySearchInHomePageTest

See the snapshot and reports(reports>extent-adapter-reports>ExtentAdapterHtmlReport) for reference

![extent adapter report for tags1](https://user-images.githubusercontent.com/38858602/110287337-55a87b80-800c-11eb-92db-32f005c2b3ae.png)
![extent adapter report for tags2](https://user-images.githubusercontent.com/38858602/110287357-5a6d2f80-800c-11eb-8d45-1b317ae0379a.png)

**Comment by kakkargaurav** [comment]
Hi @qatestingravi  this has been fixed in version 5.0.7-SNAPSHOT. Refer issue# 282.

**Comment by qatestingravi** [comment]
@kakkargaurav In the above project, I have not used the extent reports maven dependency.
I have used only below extentreports-cucumber6-adapter maven dependency. 
see the pom.xml for reference. 


<dependency>
    <groupId>tech.grasshopper</groupId>
    <artifactId>extentreports-cucumber6-adapter</artifactId>
    <version>2.6.0</version>
</dependency>



Is it mandatory to use extent reports dependency in order to use cucumber adapter reports?

**Comment by kakkargaurav** [comment]
I am not sure @qatestingravi but you can try that. I felt your issue is similar to 282.

**Comment by qatestingravi** [comment]
@kakkargaurav issue is similar to 282, but this is specific to cucumber extent adapter report. @anshooarora  can you please look in it?

**Comment by grasshopper7** [comment]
@qatestingravi Will have a look at it. The adapter internally uses the extentreport as a dependency. The 2.6.0 adapter version is currently using the 5.0.5 extent jar. 
I will switch over to 5.0.7, when it is available in Maven, and give it a shot.

FYI, please consider adding adapter version 6 issues at this repo - https://github.com/grasshopper7/extentreports-cucumber6-adapter/issues. Easier to track and fix. Thx.

**Comment by qatestingravi** [comment]
@grasshopper7 thanks for the update, Let me know when you update the 5.0.7 extent jar. I will check it.

**Comment by anshooarora** [comment]
@grasshopper7 @qatestingravi   Just pushed the latest `5.0.7`.  PS.  It may take a few hours for the build to propagate and start appearing in search results.
