### ISSUE TITLE
Attached Images in Extends Reports not displaying as Thumbnail

### ISSUE THREAD

**Issue by pulkitclg** [extent-framework/extentreports-java#287]
**Version-** 5.0.7
**Code Snippet-**
String base64Screenshot = "data:image/jpg;base64,+ ((TakesScreenshot) driver).getScreenshotAs(OutputType.BASE64);
ExtentTestManager.getTest().fail(MediaEntityBuilder.createScreenCaptureFromBase64String(base64Screenshot).build());
**Problem-** Image 'base64 img' not displaying as thumbnail. Image opens well when I click it but I want the image to be displayed as thumbnail. Is there any solution that you can suggest to archive this?
**Screenshot-**
![ExtendsReport_Image_Thumbnail](https://user-images.githubusercontent.com/54498050/110819097-ddfc7a00-82b3-11eb-8da7-2b048b5d7139.png)

**Comment by anshooarora** [comment]
Since this has been the default behavior,  this feature will be enabled via configuration starting `5.0.8` onwards.

XML:

```xml
<thumbnailForBase64>false</thumbnailForBase64>
```

JSON:

```json
"thumbnailForBase64": true,
```

Java:

```java
spark.config().thumbnailForBase64(true);
```

Updated config [here](https://github.com/extent-framework/extentreports-java/tree/master/config).
