### ISSUE TITLE
Skipped test cases accumulative count is not getting displayed in report.

### ISSUE THREAD

**Issue by yogitthakral** [extent-framework/extentreports-java#30]
![image](https://user-images.githubusercontent.com/34978997/51099920-80fef980-17f9-11e9-9e90-c5e2a4ea24ba.png)

**Comment by yogitthakral** [comment]
Here in this picture , there is one failure and 1 skipped test case , failed test case count is getting shown above but skipped test case count is not getting displayed.

**Comment by foursyth** [comment]
Version?

**Comment by yogitthakral** [comment]
4.0.6

**Comment by yogitthakral** [comment]
Same thing with the category view count  here : 
![image](https://user-images.githubusercontent.com/34978997/51100097-6f6a2180-17fa-11e9-8762-a72c24431c5f.png)
