### ISSUE TITLE
ExtentHtmlReporter custom JS not working

### ISSUE THREAD

**Issue by asezani** [extent-framework/extentreports-java#300]
Using ExtentReports v.4.10 .Net Standard Community Edition

I can't seem to get my custom JS to work. For example, removing the 2nd chart (Scenarios).

I've tried by loading an XML config and directly from code.

**XML Code**
```
<?xml version="1.0" encoding="utf-8" ?>

<extentreports>
	<configuration>
		<scripts>
			<![CDATA[
                $(document).ready(function() {
                    document.getElementsByClassName('col-md-3')[1].remove();
                });
            ]]>
		</scripts>
	</configuration>
</extentreports>  
```

```
var htmlReporter = new ExtentHtmlReporter(path);
htmlReporter.LoadConfig(@"C:\path\html-config.xml");
```

**Directly from code**

`htmlReporter.Config.JS = "document.getElementsByClassName('col-md-3')[1].remove();";`

But chart is still here:
![image](https://user-images.githubusercontent.com/38120869/118050708-aa31e500-b334-11eb-8743-000b3b96b824.png)

**Comment by rmathur75** [comment]
How did you resolved it?
