### ISSUE TITLE
Assigned devices are not displayed in the extent report 

### ISSUE THREAD

**Issue by vali92** [extent-framework/extentreports-java#31]
extentreports-4.0.6

I'm trying to assign devices on test cases but in the report nothing is displayed. I assign them like categories/authors. E.g.

static ExtentTest extentTest;
.
.
.
extentTest = extent.createTest(valueTitle, valueDescription);
extentTest.assignDevice("Chrome");

**Comment by vali92** [comment]
Thanks @anshooarora, when do you think that 4.0.7 will be released?

**Comment by anshooarora** [comment]
It is already.

**Comment by vali92** [comment]
I was checking [here](http://extentreports.com/community/)

**Comment by anshooarora** [comment]
Fix available starting `4.0.8-SNAPSHOT` [link](https://oss.sonatype.org/content/repositories/snapshots/com/aventstack/extentreports/4.0.8-SNAPSHOT/)
