### ISSUE TITLE
Extent Report Selenium Dynamic Report Name

### ISSUE THREAD

**Issue by kppetrick** [extent-framework/extentreports-java#319]
Is there a way to have the report name change based on what feature file is being run? For example if I run say feature file named ABC testing it makes the report name ABC testing and if I run feature file DEF testing it names the report DEF testing

**Comment by anshooarora** [comment]
@kppetrick You can pass the name to the reporter's instantiation:

```
ExtentSparkReporter spark = new ExtentSparkReporter("ABC.html");
```
