### ISSUE TITLE
The report generated is not having scroll bar. Hence unable to scroll down.

### ISSUE THREAD

**Issue by iamlivinsunny** [extent-framework/extentreports-java#326]
![image](https://user-images.githubusercontent.com/71168111/137590779-8eac6ca2-fc61-421e-bb0c-72fd579ee765.png)

The scroll bar is not visible in the report generated using 5.0.9 version of extent report. Hence cant scroll down. 
Chrome version : 94.0.4606.81
Display : 
15.6-inch  WQHD (2560 x 1440) 16:9

**Comment by HCLW4W** [comment]
I am also facing this issue in 5.0.9. Tried with some earlier version as well, but issue is still coming. We need a fix of this.

**Comment by iamlivinsunny** [comment]
If your laptop support gesture like two finger scroll then the scroll bar will be visible. Just use two finger to scroll. Can be used as a work around.

**Comment by iamlivinsunny** [comment]
Two finger scroll can be used for making the scrollbar visible in laptops. Hence closing the issue.

**Comment by Sowmya013** [comment]
This issue is still exists. any Workaround for this ?

**Comment by abhiz007** [comment]
Issue still persists, I am printing response message in the report and not able to scroll. I had to make Zoom % to 60 to view all content, do we have any workaround or do we have any fix available for it. I am using 5.1.2

**Comment by abhiz007** [comment]
we can create a custome java script file and then add as reporter.config().setJs("path_to/scroll.js"); now it's working for me

**Comment by manaswinimohanty** [comment]
sparkReport.config().setCss("div.test-content-detail{style='overflow-y:scroll;'}");
