### ISSUE TITLE
Custom javascript and styles doesn`t work in version 5.0.0 - 5.0.9

### ISSUE THREAD

**Issue by Tanng0** [extent-framework/extentreports-java#344]
I have upgraded my Extentreport from version 4.0.9 to version 5.0.9 recently, and my custom javascript scripts and css styles are not present in the .html file no more.  

This is my XML configuration:

    <configuration>
        
        
        <theme>standard</theme>

        
        <timeStampFormat>MMM dd, yyyy HH:mm:ss</timeStampFormat>

        
        
        <encoding>UTF-8</encoding>

        
        
        
        <protocol>HTTPS</protocol>

        
        <timelineEnabled>true</timelineEnabled>

        
        <reportName>My project</reportName>

        
        <scripts>
            <![CDATA[
                $(document).ready(function () {
                    $('li.test-item').on("click",function(){
                        $('.test-content').scrollTop(0);
                    });
                });
            ]]>
        </scripts>

        
        <styles>
            <![CDATA[
            .r-img { width: 15%; }
      ]]>
        </styles>

    </configuration>

And the outcome in the Report.html is:
`<style type="text/css"></style>`

`<script type="text/javascript"></script>`

I have verified version 5.0.0 and 5.0.9.
The issue i am trying to resolve with this custom javascript is that list of tests steps is not automatically scrolled to the top when moving between tests

**Comment by grasshopper7** [comment]
Give it a try by replacing "scripts" with "js" and "styles" with "css". Refer this - https://github.com/extent-framework/extentreports-java/blob/master/src/test/resources/config/spark-config.xml

**Comment by Tanng0** [comment]
Oh yea, i was referring to this configuration: https://github.com/extent-framework/extentreports-java/blob/master/config/spark-config.xml - your suggestion of course fixed my problem - thanks for quick reply!
