### ISSUE TITLE
Add system properties to Extent config XML file

### ISSUE THREAD

**Issue by JustinH1989** [extent-framework/extentreports-java#365]
I am trying to add environment variables to my report via the XML file, I am using the cucumber extent report adapter but cannot find any docs anywhere on how to set the environment variables in the XML config file, or even in the extent.properties file.
Please help

**Comment by grasshopper7** [comment]
Refer to this implementation to pass these from extent.properties in cucumber 7 adpater  - https://github.com/grasshopper7/cuke7-extent-adapter-report/blob/aa9e003f05be5f7765f95b8ff72722d15d53ecd1/cuke7-extent-adapter-report/src/test/resources/extent.properties#L25
Documentation -  search for section 'Environment or System Info Properties' at https://ghchirp.online/3196/

**Comment by JustinH1989** [comment]
Thanks for the help, issue is solved
