### ISSUE TITLE
Extent Report sent via mail using smtp server is not opening for v5xx.

### ISSUE THREAD

**Issue by rmathur75** [extent-framework/extentreports-java#373]
Please help!
I am new to selenium and working on Bdd-Testng framework using Cucumber(6)+maven+Testng+ExtentReport (5.0.9).
I am trying to send mail after execution, mail is getting tiggered but attachement is not opening properly in other's system. Please help.{Please note : when I send manually from outlook manually from my system, it is working fine in other system.}

Below is code i am using. 
[I  searched on net and all examples are with password n all, and here in my case Password is not required, so not able to use the examples.]

public static void sendMail() {
		try {
			
				String smtpHostServer = "relay.[CompanyName].com"; ----//[removed company name for security purpose]
				Properties props = System.getProperties();
		//	props.put("mail.smtp.auth", "true");
				//props.put("mail.smtp.starttls.enable", "true");
				 // props.put("mail.smtp.ssl.protocols", "TLSv1.2");
				//props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
				//props.put("mail.smtp.ssl.checkserveridentity", true);
				 
				if (PropertyUtils.get(ConfigMap.SENDMAILUSING).equalsIgnoreCase("Gmail")) {
					props.put("mail.smtp.host", "smtp.gmail.com");
					props.put("mail.smtp.port", "465");
				} else if (PropertyUtils.get(ConfigMap.SENDMAILUSING).equalsIgnoreCase("Outlook")) {
					props.put("mail.smtp.host", "smtp.live.com");
					props.put("mail.smtp.port", "587");
				}else 
				{props.put("mail.smtp.host", smtpHostServer);}
		       
				Session session = Session.getInstance(props, null);{

				//Session session = Session.getDefaultInstance(props, new javax.mail.Authenticator() {
					//@Override
					//protected PasswordAuthentication getPasswordAuthentication() {
						//try {
							//String decodedPassword = new String(Base64.getDecoder().decode(encodedPassword.getBytes()));
							//return new PasswordAuthentication(emailId, decodedPassword);
					//	} catch (Exception e) {
						//	e.printStackTrace();
						//}
					//return null;
					
				//});
				MimeMessage message = new MimeMessage(session);
				message.addHeader("Content-type", "text/HTML; charset=UTF-8");
				message.addHeader("format", "flowed");
				message.addHeader("Content-Transfer-Encoding", "8bit");
	            //  message.setContent(content,"text/html");
	            //  message.setContent(session, "text/html");
				message.setFrom(new InternetAddress(emailId));
				message.addRecipient(Message.RecipientType.TO, new InternetAddress(receiversEmailID));
				
				// msg.setFrom(new InternetAddress(properties.getProperty("FromEmailID"), "NoReply-JD"));
	              // msg.setReplyTo(InternetAddress.parse(properties.getProperty("ToEmailID"), false));
	              
				
				message.setSubject("Test Execution Report - " + reportName);

				BodyPart body = new MimeBodyPart();
				body.setText("Please find attached Execution" + "\r\n" + "\r\n" 
			             
			               + "\r\n" +   "Scenario Passed: "
			               + "\r\n" +   "Scenario Failed: "
			               + "\r\n" +   "Scenario Skipped: "
			               +" \r\n" +" \r\n" +  "Thanks"+ "\r\n" + "Automation Testing Team");
			         
				
				MimeBodyPart mimeBodyPart = new MimeBodyPart();
				DataSource source = new FileDataSource(report);
				mimeBodyPart.setDataHandler(new DataHandler(source));
				mimeBodyPart.setFileName(reportName);
				Multipart multipart = new MimeMultipart();
				multipart.addBodyPart(body);
				multipart.addBodyPart(mimeBodyPart);
				message.setContent(multipart);
				Transport.send(message);
				System.out.println("\n\n");
				System.out.println(Email Sent!!");
				
			}
			}
		} catch (MessagingException e) {
			e.printStackTrace();
		}

	}

**Comment by grasshopper7** [comment]
Can you give more details about - " attachment is not opening properly in other's system"?

**Comment by rmathur75** [comment]
> Can you give more details about - " attachment is not opening properly in other's system"?

Please find the screenshot for the mail received.

![image](https://user-images.githubusercontent.com/129526408/229274880-72cd4a94-1e27-4fd5-929b-420bbbabc3c6.png)
On opening the attachment

![image](https://user-images.githubusercontent.com/129526408/229274978-0ef207fd-b7ee-43a9-b3b8-6f357dcb1ac5.png)

execution report is not displaying properly. Saved the attachment in local and the tried but same result.

**Comment by grasshopper7** [comment]
This happens when the report is not able to fetch resources (js css etc) from the internet. You will need to generate the report in offline mode. Then zip the html report file plus other generated resources. Then send this as attachment on the email.

To generate report in offline mode add 'offlineMode' setting to 'true' in your spark-config.xml. 

For example - https://github.com/grasshopper7/cuke7-extent-adapter-report/blob/0d57e1b7c5486016263b907188d58175addfa3c5/cuke7-extent-adapter-report/src/test/resources/spark-config.xml#L23. Set this to 'true' instead

**Comment by rmathur75** [comment]
> This happens when the report is not able to fetch resources (js css etc) from the internet. You will need to generate the report in offline mode. Then zip the html report file plus other generated resources. Then send this as attachment on the email.
> 
> To generate report in offline mode add 'offlineMode' setting to 'true' in your spark-config.xml.
> 
> For example - https://github.com/grasshopper7/cuke7-extent-adapter-report/blob/0d57e1b7c5486016263b907188d58175addfa3c5/cuke7-extent-adapter-report/src/test/resources/spark-config.xml#L23. Set this to 'true' instead
Thanks for the reply, I will try this one out.
Could you please also help on below extent report class which i am maintaining.

Problem statement : Rename the charts from Test, steps, Log events to ' Features', Scenarios, 'Steps'.
I am able to achieve this by below line.
spark.config().setJs("document.getElementsByClassName('card-title')[0].firstChild.nodeValue='Features';");

However, when i write below 3 line for all the charts together,only last line is getting executed and first two lines are getting overridding or ignored.
	               spark.config().setJs("document.getElementsByClassName('card-title')[0].firstChild.nodeValue='Features';");
			spark.config().setJs("document.getElementsByClassName('card-title')[1].firstChild.nodeValue='Scenarios';");
			spark.config().setJs("document.getElementsByClassName('card-title')[2].firstChild.nodeValue='Steps';");


![image](https://user-images.githubusercontent.com/129526408/229299630-4daae231-e778-406c-91cf-9ba775c6c5eb.png)

Below is my class which i am using. please help!

public final class ExtentReport {
	private ExtentReport() {
	}

	private static ExtentReports extentReports;
	public static void initReports() throws IOException {
		if (Objects.isNull(extentReports)) {
			// Setting the view order for the tabs in report
			ExtentSparkReporter spark = new ExtentSparkReporter(ReportPath.getReportPath()).viewConfigurer()
					.viewOrder().as(new ViewName[] { ViewName.DASHBOARD, ViewName.TEST, ViewName.CATEGORY,
							ViewName.DEVICE, ViewName.AUTHOR, ViewName.EXCEPTION })
					.apply();
			
			extentReports = new ExtentReports();
			
			spark.config().setJs("document.getElementsByClassName('card-title')[0].firstChild.nodeValue='Features';");
			spark.config().setJs("document.getElementsByClassName('card-title')[1].firstChild.nodeValue='Scenarios';");
			spark.config().setJs("document.getElementsByClassName('card-title')[2].firstChild.nodeValue='Steps';");
			
			extentReports.attachReporter(spark);
			
		}
	}

**Comment by rmathur75** [comment]
Closing this issue, as it is resolved. Issue was with config.xml file
