### ISSUE TITLE
On Failure the total execution time is displayed as Zero under test section

### ISSUE THREAD

**Issue by saikiran40cs** [extent-framework/extentreports-java#38]
Java Version: 11
Os: Windows 10 Pro
Extent version: 4.0.6
TestNG Version: 6.14.3

On Failure the total execution time is displayed as Zero under test section.
Refer the image for more reference.

![image](https://user-images.githubusercontent.com/6228048/51459726-81f6d480-1d7f-11e9-9dad-92331bcbce50.png)

**Comment by vali92** [comment]
@anshooarora I'm using 4.0.8 and is working fine for Spark Reporter and Logger Reporter, maybe it helps.

**Comment by letmejustfixthat** [comment]
I have the same issue with 4.0.8 and klov 0.2.3.The runtime of my tests is always zero, altough the timestamps in the test nodes seem correct

![screenhunter_180 jan 24 08 25](https://user-images.githubusercontent.com/12950399/51661773-26605d00-1fb2-11e9-9bc7-9d36c5ad681d.jpg)

I would expect these stuff to be calculated automatically, how ever, I also tried the following:

    @Listeners(TestTimeMeasuringAdapter.class)
    public abstract class SeleniumBaseTest {
      ...
    }

And the implementation:

    @Slf4j
    public class TestTimeMeasuringAdapter implements ITestListener {

    @Override
    public void onTestStart(final ITestResult iTestResult) {

    }

    @Override
    public void onTestSuccess(final ITestResult iTestResult) {
        final Date time = new Date();
        log.info("setting end time for {} to {}", iTestResult.getName(), time.toString());
        iTestResult.setEndMillis(time.getTime());
    }

    @Override
    public void onTestFailure(final ITestResult iTestResult) {
        final Date time = new Date();
        log.info("setting end time for {} to {}", iTestResult.getName(), time.toString());
        iTestResult.setEndMillis(time.getTime());
    }

    @Override
    public void onTestSkipped(final ITestResult iTestResult) {
        final Date time = new Date();
        log.info("setting end time for {} to {}", iTestResult.getName(), time.toString());
        iTestResult.setEndMillis(time.getTime());
    }

    @Override
    public void onTestFailedButWithinSuccessPercentage(final ITestResult iTestResult) {
        final Date time = new Date();
        log.info("setting end time for {} to {}", iTestResult.getName(), time.toString());
        iTestResult.setEndMillis(time.getTime());
    }

    @Override
    public void onStart(final ITestContext iTestContext) {
        log.info("starting context {}@{}", iTestContext.getName(), iTestContext.getHost());
    }

    @Override
    public void onFinish(final ITestContext iTestContext) {
        log.info("finishing context {}@{}", iTestContext.getName(), iTestContext.getHost());
    }
    
    }

Am I doing something wrong?

**Comment by anshooarora** [comment]
Okay, maybe the node timestamps are not moving up a level to the parent.  Let me check again.

**Comment by anshooarora** [comment]
Still not able to reproduce.  Also, please use the `extentreports-testng-adapter` where possible, instead of a custom Extent implementation.  Adapter [link](https://github.com/extent-framework/extentreports-testng-adapter) and examples [link](https://github.com/extent-framework/examples/tree/master/extentreports-testng-adapter-example).

Please create an example that I can use to reproduce..

**Comment by letmejustfixthat** [comment]
hmm... I tried the `ExtentITestListenerClassAdapter` but that doesn't work either. As already stated [here](https://github.com/extent-framework/klov-server/issues/7#issuecomment-454683553) I create a "root" test for every customer environment first and then create nodes on top of that for every test. 

    private static final Map<String, ExtentTest> testReports = new HashMap<>();

    private static ExtentTest getCustomerTestReport(final BasicParameter parameter) {
        if(testReports.get(parameter.getCustomer()) == null) {
            testReports.put(parameter.getCustomer(), getReporter(parameter).createTest(parameter.getCustomer()).assignCategory(parameter.getCustomer()));
        }
        return testReports.get(parameter.getCustomer());
    }

    public static ExtentTest testStarter(...) {
        final ExtentTest test = getCustomerTestReport(parameter).createNode(testTitle, testDescription);
        ...
        return test;
    }

The test will use that method and only log on the nodes.

    @Test
    public void test() {
        final ExtentTest test = TestUtilFactory.testStarter(....);
        test.info("let's do this");
        if(fail) { test.fail(...); }
        else { test.pass(...); }
   }

**Comment by anshooarora** [comment]
What does this do in your code and why is it required:

```
iTestResult.setEndMillis(time.getTime());
```

**Comment by anshooarora** [comment]
Closing this as there is no response from OP.  If you are still experiencing this, please create a new ticket and provide an example to reproduce.  Thank you
