### ISSUE TITLE
How to display report to japanese

### ISSUE THREAD

**Issue by CurryPham** [extent-framework/extentreports-java#384]
I working with client Japanese. So how i can to display report to japanese?

**Comment by CurryPham** [comment]
I'm try this config but it didn't work 

` public static final ExtentReports extentReports = new ExtentReports();
ExtentSparkReporter reporter = new ExtentSparkReporter(System.getProperty("user.dir") + "/extentV5/ExtentReport " + new SimpleDateFormat("HH.mm.ss.dd.MM.yyyy").format(new java.util.Date()) + ".html");
reporter.loadXMLConfig (new File(System.getProperty("user.dir") + "\\extent-config.xml"));
`

`<extentreports>
    <configuration>
        <language>ja</language>
    </configuration>
</extentreports>
`

**Comment by anshooarora** [comment]
`<language>` is not a permitted configuration.  I would recommend looking at the appropriate encoding.  Although, the default UTF-8 which should work here IMO.
