### ISSUE TITLE
Extent Report Dashboard counts Skipped retried Test as well to count Pass and Fail %

### ISSUE THREAD

**Issue by sampathraghupatruni** [extent-framework/extentreports-java#386]
If we have a Retry Mechanism is place , for example 2 retries and a test fails for the first two times and passes in the third, the pass % takes into account skipped tests as well . Is there a solution to  fix this % calculation?
![image](https://github.com/extent-framework/extentreports-java/assets/99191412/0f962ddf-7f2e-478d-a5dc-8ed8e5e00825)

**Comment by anshooarora** [comment]
This is not possible at the moment.  I'm thinking it can be introduced via property to preserve the existing behavior.

**Comment by grasshopper7** [comment]
Hi,
I was trying to include this functionality in the cucumber adapter but I think I have come across a bug. 

The onNodeCreated() is searching for an existing test in the list which contains the top level tests. So a test node can remove a top level test with the same name. It should instead be searching for the tests among its siblings only.

For example in a Scenario Outline, a new Scenario within it should only check in the existing scenarios for this scenario outline.

**Comment by SSINGHPR** [comment]
+ Following.
