### ISSUE TITLE
Req for New Features

### ISSUE THREAD

**Issue by chik145** [extent-framework/extentreports-java#393]
Hi Developer,
These are the few enhancements request, please look into it 

1. Auto Scroll till Failed Step
Is it possible to add an auto scroll button to test report which will scroll the page till failed steps back-to-back?
in case of long selenium test case, it's hard to look for the failed tag icon by scrolling manually.
an auto scroll feature will be a good add on.

2. Custom Report Status
It will be good if there will be an option to add a custom status to report based on requirement.
currently we are bound choose from: pass, fail, skip, warn etc.

3. Merging Multiple Reports to Make One Consolidate Report
If we have multiple extent reports after test execution, an option to merge them into a single report will be good. 

Please consider above requests.

Thanks
Your effort is much appreciated :)

**Comment by anshooarora** [comment]
Just fyi - #3 in your list is already available:  https://www.extentreports.com/docs/versions/5/java/#combine-multiple-reports

**Comment by anshooarora** [comment]
#2 in your list is similar to #313.

**Comment by anshooarora** [comment]
The above commit resolves #1 in your list with the "forward red button" on the top right-side of the details pane, but making this setting automatic would impact current usage.  Also, there may be multiple errors, so the current approach allows navigating to each error individually.

<img width="1127" alt="Screenshot 2023-08-12 at 7 09 29 PM" src="https://github.com/extent-framework/extentreports-java/assets/4107384/3ebb9113-e914-4308-9cf9-b736dbda2fc3">

**Comment by chik145** [comment]
Thanks Anshoo,
How can i use this feature?
updated dependencies to 5.1.0 & JDK to 11

unable to see above changes
