### ISSUE TITLE
Issue With Version 5.1.0

### ISSUE THREAD

**Issue by chik145** [extent-framework/extentreports-java#394]
Getting Below Issue After Updating From 5.0.9 to 5.1.0

java: cannot access com.aventstack.extentreports.ExtentTest
  bad class file: /D:/Maven Repo/Repo/com/aventstack/extentreports/5.1.0/extentreports-5.1.0.jar!/com/aventstack/extentreports/ExtentTest.class
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by anshooarora** [comment]
5.1.0 upgrades JDK from 8 to 11.

**Comment by chik145** [comment]
Thanks, 5.0.9 is the last supported version for JDK 8?

**Comment by anshooarora** [comment]
Yes

**Comment by anshooarora** [comment]
I would love to continue maintaining the library with JDK 8 and utilize the lowest possible version, but many have migrated to at least JDK 11+ and so will/have many others OSS libraries.  For instance:  the [Selenium project will stop supporting JDK 8 after September 30, 2023](https://www.selenium.dev/blog/2023/java-8-support/).

**Comment by chik145** [comment]
No Worries Mr. Anshoo

but if you can make a one last release for JDK 8 includes these new things will be good

https://github.com/extent-framework/extentreports-java/issues/393
