### ISSUE TITLE
Spark Report Javascript implementation for Cucumber-JS plugin

### ISSUE THREAD

**Issue by grasshopper7** [extent-framework/extentreports-java#399]
Hi,
I have created an implementation of the Spark report using Javascript with Node and Nunjucks templating. This is strictly designed for use as a Cucumber-JS plugin. 
This is the repository for the code - https://github.com/grasshopper7/cucumber-js-extent-report. I am planning to upload this to NPM.

The report uses the online js and css files that are used in the Java version of the report.
Is it acceptable to use these artifacts and the design in creating this report? I will give you full credit as well add your license to the project.

Thanks.

**Comment by anshooarora** [comment]
Great work @grasshopper7, super impressive.  Go for it :)
