### ISSUE TITLE
Test case is showing as pass even though its failing

### ISSUE THREAD

**Issue by yasinyilmazzz** [extent-framework/extentreports-java#406]
Test case is showing as pass even though its failing, but take screenshot on failed step

<img width="266" alt="image" src="https://github.com/extent-framework/extentreports-java/assets/116284952/e4325e38-4e3d-40ae-ac9b-40635fdb2838">

**Comment by anshooarora** [comment]
Looks like the failed status isn't passed to the test.  The default status on each step is PASS - the other steps may be showing the default status.  On failure, within your hook, you can:

```
test.fail("details");
```
