### ISSUE TITLE
Missing Offline Mode functionality

### ISSUE THREAD

**Issue by maddiesumner** [extent-framework/extentreports-java#41]
Upgrading from extentreports v2 I noticed there was only one breaking change - the lack of offline mode, which means we cannot run our automated tests in a box separated from the internet.
Is there a plan to re-implement this?
(Also extentreports is amazing)

**Comment by anshooarora** [comment]
OfflineMode will be available soon, it is part of the road map and I anticipate it being part of release `4.1.0`.

**Comment by pavankumarmt** [comment]
When would be 4.1.0 released? @anshooarora

**Comment by foursyth** [comment]
As per @anshooarora, latest should be released today
