### ISSUE TITLE
ExtentReports _ Spark Reporter _ HyperLinks on Bug Page Not redirect to failed tests in latest version 5.1.1

### ISSUE THREAD

**Issue by zanoon2020** [extent-framework/extentreports-java#411]
in latest version 5.1.1 hyper links on bug pages in generated report not redirect to failed tests 

sample code 
```java
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;

public class TestExtent {
	
	
	@Test(description="test description")
	public void testFail(Method method) {
		ExtentReports extent = new ExtentReports();
		ExtentSparkReporter spark = new ExtentSparkReporter("target/");
		extent.attachReporter(spark);
		ExtentTest test;
	    test = extent.createTest("Test Name here");
		test.fail(new IllegalStateException("Fail message"));
		extent.flush();
	}
}
```

![image](https://github.com/extent-framework/extentreports-java/assets/65794900/551cb847-15e5-459d-9ec8-587c1b1302af)

**Comment by zanoon2020** [comment]
dear @anshooarora for your kind support

**Comment by zanoon2020** [comment]
Dear @anshooarora any chance for that to be solved soon 😊

**Comment by zanoon2020** [comment]
dear @anshooarora will the fix be available next release or this is hot fix that i can use immediately , and if i can use it immediately kindly tell me how

**Comment by anshooarora** [comment]
It's currently available as a SNAPSHOT release:  https://oss.sonatype.org/content/repositories/snapshots/com/aventstack/extentreports/5.1.2-SNAPSHOT/

```
<groupId>com.aventstack</groupId>
<artifactId>extentreports</artifactId>
<version>5.1.2-SNAPSHOT</version>
```

**Comment by zanoon2020** [comment]
> It's currently available as a SNAPSHOT release:  https://oss.sonatype.org/content/repositories/snapshots/com/aventstack/extentreports/5.1.2-SNAPSHOT/
> 
> ```
> <groupId>com.aventstack</groupId>
> <artifactId>extentreports</artifactId>
> <version>5.1.2-SNAPSHOT</version>
> ```

Many thanks @anshooarora
