### ISSUE TITLE
Unable to navigate to the test case from Category section in version 5.1.1

### ISSUE THREAD

**Issue by sanoj-s** [extent-framework/extentreports-java#418]
Unable to navigate to the test case from the Category section in version 5.1.1. When I click on the test case link from Category section, nothing happens and stay in the same page. It should navigate to the selected test case. Same feature is working as expected in version 5.1.0

**Comment by rado-o** [comment]
Is there any update on this issue available?

**Comment by piotr-ponikowski-source** [comment]
I was also looking for fix, and it looks it is already fixed through: https://github.com/extent-framework/extentreports-java/issues/417

**Comment by anshooarora** [comment]
Thanks @piotr-ponikowski-source - it was fixed and the latest release is also available:

```
<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>5.1.2</version>
</dependency>
```
