### ISSUE TITLE
FreeMarker breaks JSON codeblocks after 999 code blocks

### ISSUE THREAD

**Issue by apex-sewilliams** [extent-framework/extentreports-java#419]
FreeMarker templates are adding a `,` or `.` after 999 code blocks. Which breaks javascript function naming formats and causes the codeblock to not show up.

![image](https://github.com/extent-framework/extentreports-java/assets/129118843/47e624d7-e746-4411-9a96-2709d4db2c0e)

I believe this PR should fix the issue: https://github.com/extent-framework/extentreports-java/pull/413

**Comment by wayne-manselle-apex** [comment]
@anshooarora - any chance someone can look the linked PR in the near future? It would really help folks out.

Tagging you specifically as it looks like you're the contributor most recently active on Github.

Thanks!
