### ISSUE TITLE
My long names overlap if I include them. Please let me know if you have a solution.

### ISSUE THREAD

**Issue by Sai7574** [extent-framework/extentreports-java#429]
My long names overlap if I include them. Please let me know if you have a solution.

![image](https://github.com/extent-framework/extentreports-java/assets/113346566/19b22b85-c7a8-4401-b206-1f6f7d415901)
test = extent.createTest(
				"Verification of Area Usage with Return decision at check transaction and Restart, Restop and Approve at Check Transaction.")
				.assignAuthor(ConfigsReader.getPropValue("usernameRev")).assignCategory(
						"Verification of Area Usage with Return decision at check transaction and Restart, Restop and Approve at Check Transaction.");
We are using this code, similar to the scenario name.

**Comment by anshooarora** [comment]
Here is what I found (notice the viewport size at the top-right of both screenshots):

![Screenshot 2024-07-02 at 4 40 12 PM](https://github.com/extent-framework/extentreports-java/assets/4107384/2ff44c44-2922-4ace-8149-5e4f60f70ec6)

![Screenshot 2024-07-02 at 4 38 01 PM](https://github.com/extent-framework/extentreports-java/assets/4107384/39333bb2-1f37-4fbe-952c-0ff86b777cf7)

Your viewport is < 1478px.  This is where this exact tag starts to break layout.  

A simple fix:


```js
// you can inject the below js:
$(document).ready(function() {
  $(".detail-head .info + div").addClass("tag-info");            
});
```

```css
/* and the following css */
@media only screen and (max-width: 1500px) {
  .tag-info { margin-top: 35px !important; }
}
```

Just curious though, the tag name is the same as the test name - why?  It's really long.  :) 

I'm closing this issue as the above would resolve it.  Feel free to reopen this or a new issue if the issue persists.  Note:  I tested with the latest version: 5.1.2.
