### ISSUE TITLE
No data generated in Extent reporting for firefox

### ISSUE THREAD

**Issue by shubautomation** [extent-framework/extentreports-java#434]
Hi @anshooarora ,

I am using Selenium Java - Test NG framework for my Automation. When I am running the Test cases (around 200, batch run through run.xml) , no data is getting generated in Extent report only for Firefox browser. For Chrome Edge is working fine. 

Could you please help me here as it is little urgent due to project critical release

Please find the below details:

Versions:
selenium-java: 4.15.0
Extent Reporting: 5.0.9
Junit: 4.11
Running Platform: VM - Windows server 2022

![image](https://github.com/extent-framework/extentreports-java/assets/115528914/8f5dba56-39f0-4794-966e-9014dc383b22)
![image](https://github.com/extent-framework/extentreports-java/assets/115528914/16d0ff3f-101a-44da-bfa9-4588f6ebd356)

**Comment by shubautomation** [comment]
hi @anshooarora ,

Could you please help me here.?

**Comment by anshooarora** [comment]
You haven't provided any details how test information is passed to the report.  Can you share your usage?

**Comment by shubautomation** [comment]
> You haven't provided any details how test information is passed to the report. Can you share your usage?

Hi @anshooarora,

I am using extent reporting as listener and also running the tests through Run.xml. Please find the POM image.

Is this you want to know? Sorry If I am not able to understand your question. 

Firefx version : 125

![image](https://github.com/extent-framework/extentreports-java/assets/115528914/52ce359d-6db6-42ef-8f14-f08cd3c5a5f5)

**Comment by anshooarora** [comment]
Can you check if `ExtentReporterNG` is being invoked?  

Is the `maven-surefire-plugin` under `<build>` or `<reporting>`?

**Comment by shubautomation** [comment]
> Can you check if `ExtentReporterNG` is being invoked?
> 
> Is the `maven-surefire-plugin` under `<build>` or `<reporting>`?


Hi @anshooarora 

Please find the POM.xml. maven-surefire-plugin` under `<build> in POM.

Also, For chrome and Edge , Safari , extent reporting is working fine. Hence ExtentReporterNG is getting invoked I believe.

[pom.txt](https://github.com/extent-framework/extentreports-java/files/15285181/pom.txt)

**Comment by anshooarora** [comment]
Can you debug to be sure it is being invoked for a Firefox test?  It is not possible to know exactly what the issue is with the information here.

**Comment by anshooarora** [comment]
Closing this as there was no response.  Please feel free to open a new issue if you're continuing to have this issue.
