### ISSUE TITLE
New release for error: Fix Ids in FreeMarker templates for values greater than 999

### ISSUE THREAD

**Issue by SebastianRG2** [extent-framework/extentreports-java#436]
Hi, its possible to create a new release where the ‘Fix Ids in FreeMarker templates for values greater than 999’ is included, so that we can consume the library with this fix?

**Comment by anshooarora** [comment]
Released (5.1.2) to central repository.  It should be visible on maven search shortly.  

![Screenshot 2024-06-26 at 5 43 45 PM](https://github.com/extent-framework/extentreports-java/assets/4107384/c5391190-5fa0-4c2a-8ea3-f06980e2d407)
