### ISSUE TITLE
on hover percentage of others is displaying as 0 %.

### ISSUE THREAD

**Issue by yogitthakral** [extent-framework/extentreports-java#45]
In the dashboard view , the onhover percentage of others is showing as 0 % while it still has some count.

Using extent version 4.0.6.

![image](https://user-images.githubusercontent.com/34978997/51801590-f04b0380-2265-11e9-8e40-162a91159ce9.png)

**Comment by yogitthakral** [comment]
Using extent version 4.0.6.

**Comment by foursyth** [comment]
@anshooarora 

It would better to use Pass, Fail, Skip & others (if there are any) as currently it is calculating percentage of Others which do not consider SKIP

* [template](https://github.com/extent-framework/extentreports-java/blob/master/src/main/resources/com/aventstack/extentreports/view/v3html/test-view/v3-html-test-view-charts.ftl#L21)
* [stats](https://github.com/extent-framework/extentreports-java/blob/master/src/main/java/com/aventstack/extentreports/ReportStatusStats.java#L110)

**Comment by anshooarora** [comment]
Thank you!
