### ISSUE TITLE
Extent Report is not getting generated correctly.

### ISSUE THREAD

**Issue by yogitthakral** [extent-framework/extentreports-java#46]
I got a case in one of my projects where extentreport html is not getting generated properly .( i.e)  Test cases are not showing , not able to go to category view and dashboard , basically , this is the view I am getting and not able to navigate by clicking on any link.

Version :- 4.0.9
Implementation :- Testng ITestListener
Console Errors :- Nothing
More Info :- Same test suite when executed on chrome , gives me report just fine . When Executed on Firefox 61 with geckodriver 0.21.0 , gives report like this :-

Screenshot :- 
![image](https://user-images.githubusercontent.com/34978997/51805884-f908fd00-2298-11e9-8e0b-32a1249b5c55.png)

Html Source Code :-
https://drive.google.com/file/d/1oCWl84SlfYJ7v_aqhZ-4eKgHxK3fOVmH/view?usp=sharing

**Comment by foursyth** [comment]
Wrap all HTML elements, or stack-trace that includes HTML elements into a [CodeBlock](http://extentreports.com/docs/versions/4/java/#code-block)

```
test.fail(MarkupHelper.createCodeBlock(e));
```

or, pass the exception to `ExtentTest` instead of stringified details:

```
Exception e;
test.fail(e);
``
