### ISSUE TITLE
Way to Generate Anchor for each test ?

### ISSUE THREAD

**Issue by staniere** [extent-framework/extentreports-java#47]
Hello, 
as I have now wonderfull reports generated with ExtentHtmlReporter, I now have big reports containings tenth of tests :)
I would like to help users to generate direct links to a specific test (in order to add this link when creating an issue)
I tried to find a way to have an direct anchor but I did not find any <div> with Id in generated html . 
I tried to generate a link with url ".../index.html#mytest_number54". 
Is it possible to generate html anchors ? 

For example on this screenshot, I would like to directly display Tnt1Shipment test when using url "index.html#Tnt1ShipmentMonoOrderAddStatus"
[https://drive.google.com/file/d/1GE2XnepgLmyCZ9y3wxFk-Zu8XPtoeuuM/view?usp=sharing](url)

**Comment by anshooarora** [comment]
This is not very straight-forward as in the HtmlReporter, the links are driven purely by JavaScript.

In SparkReporter, links are driven by uri anchor and JavaScript.  

Marking this as an enhancement to enable linking to test and their children.

**Comment by staniere** [comment]
Ok, I understand the difficulty. 
Perhaps another way more straight-forward would be to be able to drive javascript with GET URL like "index.html?test_name=mytest_number54"
or directly with id as "index.html?test-id=2" ?

**Comment by anshooarora** [comment]
With both Html and Spark reporters, the below will work:

```
index.html?test-name=TestName
index.html?test-name="TestName"
index.html?test-name=Test Name
index.html?test-name="Test Name"
```

**Comment by staniere** [comment]
It was quick, thank you Anshooaroa :)
Will these links be directly available from extent-report or will I have to compose it manually ?
The best would be to have a link in order to be able to use right click \ "copy link url" 
In <h5> title of <div class="view-summary"> for example

Other question, when will it be available to test ? (next version of extent-report is expected at which date ?)

**Comment by staniere** [comment]
Hello Anshooaroa, 

I tried to use it with, but it does not display desired test. 
Is there some special characters to avoid in test-name ?

Here is URL I tried to use : 
`file:///C:/dev/myfm-selenium/MyScmFramework/target/extent-reports/index.html?test-name="Tnt4_5TripMultiOrderAddStatus1HourInPastWithFutureNotAllowed[0-chrome-latest-PAris]"`

Here is my extent-report generated  index.html : 
[index.zip](https://github.com/extent-framework/extentreports-java/files/2925984/index.zip)

**Comment by anshooarora** [comment]
Can you try adding this to your custom JS in config.xml:

```
$(document).ready(function() {
  var loc = window.location.href;
  if (loc.indexOf('?test-name')>0) {
    var name = loc.match(/test-name.*/)[0].replace('test-name=', '');
    name = name.replace(/%22/g, '').replace(/%20/, ' ');
    $('.test-detail .name').filter(function() {
      return $(this).text() == name;
    }).closest('.test-item').click();
  }
}
```

or via `setJS` method:

```
$(document).ready(function() {var loc = window.location.href;if (loc.indexOf('?test-name')>0) {var name = loc.match(/test-name.*/)[0].replace('test-name=', '');name = name.replace(/%22/g, '').replace(/%20/, ' ');$('.test-detail .name').filter(function() {return $(this).text() == name;}).closest('.test-item').click();}}
```

then using the test-name in the URL like so:

```
file:///C:/index.html?test-name="Tnt4_5TripMultiOrderAddStatus1HourInPastWithFutureNotAllowed[0-chrome-latest-PAris]"
```

If the above works,  I will make this part of the standard JS so you won't need to do so explicitly.

**Comment by anshooarora** [comment]
Starting v5.0, an anchor will be generated for each test by default.  It will appear at the right-side when you open any test, like so:

```
#test-id=2
```

![image](https://user-images.githubusercontent.com/4107384/87883485-8627a080-c9bc-11ea-9ba7-e084a19e299d.png)

To navigate to the test using the anchor, simply add the uri component at the end of the report URL;

```
http://server/index.html#test-id=2
```
