### ISSUE TITLE
Please merge changes from 3.1.6-SNAPSHOT to latest master or 4.0.9

### ISSUE THREAD

**Issue by skunti** [extent-framework/extentreports-java#48]
Please merge changes from 3.1.6-SNAPSHOT to latest master or 4.0.9.

I am not sure if you could remember but an important fix https://github.com/anshooarora/klov/issues/45 went in 3.1.6-SNAPSHOT which addresses attaching screen sots to klov report. But looks like those changes were never merged back into master. If I use 4.0.9 or any latest version then I am still seeing issue `java.io.IOException: The system cannot find the file specified` but works fine if I use 3.1.6-SNAPSHOT.

**Comment by anshooarora** [comment]
It would help to see a sample that reproduces this as I am unable to.

**Comment by anshooarora** [comment]
Closing as there was no response. Please create a new one I'd you are still facing this.
