### ISSUE TITLE
long text is leaving the screen

### ISSUE THREAD

**Issue by mmajcherczyk** [extent-framework/extentreports-java#50]
long text is leaving the screen
v.4.0.9 
ExtentSparkReporter

![222](https://user-images.githubusercontent.com/6592592/52306675-e24d5f00-2998-11e9-9cdf-f473c9721a12.png)

**Comment by anshooarora** [comment]
Will fix this, but would also recommend to use MarkupHelper->CodeBlock here which would prettify the json.

http://extentreports.com/docs/versions/4/java/#markup-helpers-codeblock
