### ISSUE TITLE
Dashboard Screen: Skip test cases should be counted in Others 

### ISSUE THREAD

**Issue by yogitthakral** [extent-framework/extentreports-java#51]
![image](https://user-images.githubusercontent.com/34978997/52396309-732a5480-2ad7-11e9-867e-a83a397d2a89.png)

**Comment by ghy090523** [comment]
![图片](https://user-images.githubusercontent.com/17328775/69392886-7ca54600-0d12-11ea-84d8-ba244e80af79.png)
