### ISSUE TITLE
code block in firefox 

### ISSUE THREAD

**Issue by mmajcherczyk** [extent-framework/extentreports-java#53]
![test](https://user-images.githubusercontent.com/6592592/52445224-ce396700-2b2a-11e9-8377-ac19f70ddd23.png)
The code block show condensed and upon clicking, it changes size to it's actual content. But this work only in chrome, in firefox doesn't work.

**Comment by anshooarora** [comment]
This seems to work everywhere except Firefox.. seems to be an issue with Firefox itself.  Firefox is not executing the toggle action when the element is disabled, but everything works as usual when the element is not enabled.

With firefox then, I would suggest putting this in your `script` hook:

```
$("textarea").prop("disabled", false);
```

**Comment by mmajcherczyk** [comment]
`$('textarea').prop('disabled', false).prop('spellcheck', false);` works perfectly
why textarea is disabled ?

**Comment by anshooarora** [comment]
Its disabled to appear like a `pre` block with the text cursor disabled and text itself as read-only.
