### ISSUE TITLE
Appending test cases to ExtentHtmlReporter v4

### ISSUE THREAD

**Issue by Piotroslav** [extent-framework/extentreports-java#54]
There is .setAppendExisting(true) method for v3 but I cannot find anything similar in v4.
Could you suggest how to make that work in v4?

Thanks in advance!

**Comment by anshooarora** [comment]
Duplicate, see #25.

**Comment by anshooarora** [comment]
Feature available starting `4.10.0-SNAPSHOT`, see #103 for details.
