### ISSUE TITLE
Filters in each tests are not working (for the failed steps)

### ISSUE THREAD

**Issue by harshith-rs** [extent-framework/extentreports-java#58]
Filters in "Status" and the filters in "Test Steps are not working in 4.0.9

![image](https://user-images.githubusercontent.com/26961953/53243136-f0a3b680-36cc-11e9-8637-f81b24dceee7.png)

**Comment by foursyth** [comment]
I am not sure if I completely understand but based upon your inputs,  let me try my best:   I believe these filters are used only for children tests, not for events.  Maybe thats why?

**Comment by twbraam** [comment]
I'm having the same issue with 4.0.0+. 3.1.5 is the last working version.

I can also see the following errors in my browser:
![image](https://user-images.githubusercontent.com/13508317/68913804-8de0d680-0797-11ea-8d28-502fafcde71c.png)
