### ISSUE TITLE
Extent report: Could we change the left side panel width - for better view of test steps ( refer snapshot)

### ISSUE THREAD

**Issue by jvattathara** [extent-framework/extentreports-java#61]
Extent report: Could we change the left side panel width - for better view of test steps ( refer snapshot)

![extentdashboard1](https://user-images.githubusercontent.com/30731958/53535769-912d1880-3ac9-11e9-86c2-13e88e557e48.PNG)

**Comment by jvattathara** [comment]
I mean that way right side have more viewing area.. I tried .xml file changes , but not seems working properly-- Any help appreciated!

**Comment by mmajcherczyk** [comment]
@jvattathara 
try 
`        htmlReporter.config().setCSS(".subview-left{width: 35%;}");
`

**Comment by jvattathara** [comment]
Thanks much!. It worked..
I would really appreciate if you have any code snippet to change font and position ( how to center it) for the "headline" from configure  .xml file, we are new on this adoption.

**Comment by jvattathara** [comment]
Closing the original issue.!
