### ISSUE TITLE
Custom log message to extent report and klov report

### ISSUE THREAD

**Issue by sureshkammari** [extent-framework/extentreports-java#62]
As of now I am getting report with steps of feature file. How to add custom log message to extent report in BDD cucumber framework

**Comment by virenv** [comment]
@sureshkammari : Can you please elaborate the issue? Possibly with examples would really help us understand the issue.

**Comment by sureshkammari** [comment]
I am getting the report in cucumber selenium frame work with the feature file steps like-
Given, when, than etc.,

But I need to add log massage of step output to this report like-
Example:
After submit the case create , I need to add the case number to report as log message

**Comment by foursyth** [comment]
Please provide a bit more details about your usage at the code level to help us know more..  I would personally suggest using the [cucumber-adapters](https://github.com/extent-framework) available and adding any custom steps from `scenario.write(args)` hook.

**Comment by NerdishShah** [comment]
> Please provide a bit more details about your usage at the code level to help us know more.. I would personally suggest using the [cucumber-adapters](https://github.com/extent-framework) available and adding any custom steps from `scenario.write(args)` hook.

Can you confirm if it worked for adapter4?

**Comment by anshooarora** [comment]
Unable to reproduce, all scenario writes show up on all reporters.  I would suggest at this point to share your code.

**Comment by virenv** [comment]
Closing the issue because of lack of response.
