### ISSUE TITLE
How to group a Test which runs multiple times in extent report

### ISSUE THREAD

**Issue by kabilanmani93** [extent-framework/extentreports-java#64]
Hi Anshoo,

I am using extent-report(version 3.1.5) in my project along with TestNG listener

I need a help on a scenario where a particular test is parameterized with TestNg Data provider which runs  say 4 times and has few logging and assertion

In Extent report the same test is shown 4 times. so how do i group it and display 

-  **Create User (Parent Test)**

-      ---> Test cycle 1
-                 ---> logging part (info,pass,fail)
-      ---> Test cycle 2
-                 ---> logging part (info,pass,fail)
-      ---> Test cycle 3
-                 ---> logging part (info,pass,fail)
-      ---> Test cycle 4
-                 ---> logging part (info,pass,fail)
- 

It would be helpful if you could help me on this.

**Comment by foursyth** [comment]
I am not 100% sure on this, but this should be provided out-of-box if you use the [testng-adapter](https://github.com/extent-framework/extentreports-testng-adapter).  You can even choose the level of hierarchy by selecting which of the listeners you want within the adapter, have a look.  This is ExtentReports version 4 only though.
