### ISSUE TITLE
Update test status after failed test node  passes in rerun

### ISSUE THREAD

**Issue by Saurabhrck** [extent-framework/extentreports-java#67]
Hi, 

Today I have migrated our extent report framework from version 2 to version 4. Our framework is a testng based framework with selenium and cucumber. we use various testng listener to initialize and flush report in extent report.

On a test failure, we retry the test up to n number of times and publish the final result in CI-CD tool. The problem here is once the failed test/scenario(which is a node of a test) rerun and passes, in the extent report html the status of the parent test is still shown as fail. even though we have removed the failed child node from extent report by:

ExtentTest test = extent.createTest("Test");
ExtentTest node = test.createNode("Node")
if node fail{
extent.removeTest(node);
}

Also if anyone can suggest me how to initialize ExtentReport without overwriting  existing HTML file? As we run multiple testNG suite at once if would be a nice option to have it flush in a single html file.

**Comment by anshooarora** [comment]
Please check with:

```
<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>4.0.10-SNAPSHOT</version>
</dependency>
```

[link](https://oss.sonatype.org/content/repositories/snapshots/com/aventstack/extentreports/4.0.10-SNAPSHOT/)

**Comment by Saurabhrck** [comment]
Hi @anshooarora ,

Thanks for the build. unfortunately I can only download dependency from https://repo.maven.apache.org/maven2/com/aventstack/extentreports/ . I guess I will have to wait till you push this fix to release.

Thanks again.

**Comment by foursyth** [comment]
Hmm, enabling snapshots should work and the link Anshoo shared is what central pulls from, so I don't see any issues

**Comment by virenv** [comment]
The core issue in this bug has been fixed. Closing the bug.
