### ISSUE TITLE
ExtentReports with Cucumber ends the program

### ISSUE THREAD

**Issue by jchristheodore** [extent-framework/extentreports-java#69]
Extent report when used with cucumber feature files and there is a step error. It ends the java program and doesn't call @afterClass/@after.

**Comment by foursyth** [comment]
Can you share the Cucumber/ExtentReports/adapter versions?

**Comment by virenv** [comment]
@jchristheodore : Because of lack of information, I am closing the issue. Please reopen it by adding more details to reproduce the issue.
