### ISSUE TITLE
Test level time-taken not populated

### ISSUE THREAD

**Issue by scottatstchome** [extent-framework/extentreports-java#70]
I found this on v3.1.5 and 4.0.9.
time-taken for individual test is not being set. Start time and end time are set correctly.

**Comment by scottatstchome** [comment]
Turns out it was a simple configuration I missed...

to fix my issue just set below to false.
extent.setReportUsesManualConfiguration(false);

**Comment by foursyth** [comment]
@anshooarora please close

**Comment by virenv** [comment]
Closing the issue based on reply by author of the bug.
