### ISSUE TITLE
setCreateOfflineReport method is missing.

### ISSUE THREAD

**Issue by pavankumarmt** [extent-framework/extentreports-java#72]
I am not able to locate setCreateOfflineReport in extent reports 4.0.0 dependency. Could you please help me locate this implementation.

http://extentreports.com/docs/javadoc/com/aventstack/extentreports/reporter/configuration/ExtentHtmlReporterConfiguration.html

**Comment by virenv** [comment]
@pavankumarmt : Are you looking for this method: enableOfflineMode ?

**Comment by pavankumarmt** [comment]
@virenv Yes looking for the same. Thanks!

**Comment by virenv** [comment]
@anshooarora : We can close this issue.

**Comment by pavankumarmt** [comment]
@virenv Any updates when would be 4.1.0 available as it has enableOfflineMode changes.

**Comment by virenv** [comment]
@pavankumarmt : I think I misread your last response. What version are you on? and do you have the enableOfflineMode in it?

**Comment by pavankumarmt** [comment]
@virenv : Was looking for timeline release of v4.1.0 as mentioned by anshu. More details in this issue.
https://github.com/extent-framework/extentreports-java/issues/41

**Comment by virenv** [comment]
@pavankumarmt : Okey. You are not blocked on your work right? I am  not sure about when the release will happen.

**Comment by pavankumarmt** [comment]
@virenv : Actually we had difficulty in viewing the reports on jenkins as the reports are distorted with css not rendering properly, so thought we can go with offline reporting.

**Comment by foursyth** [comment]
@anshooarora please release the latest changes to nexus, thx!

**Comment by virenv** [comment]
@pavankumarmt : Can we go ahead and close the issue? given we have enableOfflineMode method?

**Comment by pavankumarmt** [comment]
Thanks! you can close this ticket, as waiting for v4.1.0 for the availability of enableOfflineMode method.

**Comment by foursyth** [comment]
fyi - As per @anshooarora, latest will be released today
