### ISSUE TITLE
Status hierarchy

### ISSUE THREAD

**Issue by mmajcherczyk** [extent-framework/extentreports-java#79]
![unnamed](https://user-images.githubusercontent.com/6592592/56786858-a9d05b00-67fa-11e9-97c4-49db86890343.png)

Why is it Pass, not Skip. Is it possible to change it?

**Comment by virenv** [comment]
@mmajcherczyk : Skip is not because of a faliure. Skip is usually done intentionally and is an informed decesion before you run a test. That is why we cannot chang the status of the Test run to skip because there are skip tests in it.

**Comment by virenv** [comment]
Closing the issue as it is by Design.
