### ISSUE TITLE
Skipped test count are not shown in Dashboard

### ISSUE THREAD

**Issue by sebinjqburst** [extent-framework/extentreports-java#8]
Some of my tests have been skipped due to the failure of some dependent tests. The same has been recorded correctly as test skipped in the logger html, but skipped tests in dashboard still shows ZERO.

![screen shot 2018-11-19 at 1 17 36 pm](https://user-images.githubusercontent.com/20396517/48693084-4cf2c800-ebfe-11e8-94be-fc928eb9992a.png)
![screen shot 2018-11-19 at 1 18 08 pm](https://user-images.githubusercontent.com/20396517/48693085-4cf2c800-ebfe-11e8-87e4-5a2138db76a7.png)

Do I need to do some additional code to mark the test as skipped instead of 
_test.skip(MarkupHelper.createLabel(iTestResult.getName() + " - Test Case Skipped", ExtentColor.YELLOW));_ in _onTestSkipped(ITestResult)_ function?

Thanks in advance.

**Comment by anshooarora** [comment]
@sebinjqburst @foursyth in version 4, events are no longer considered as steps.  To increment the child/step/method count, `test.createNode(args)` must be used.

**Comment by lucasn580** [comment]
@anshooarora how will I set status test just without passing him at createNode() function ?

**Comment by chetanJTH** [comment]
@sebinjqburst did you resolved issue?

**Comment by sebinjqburst** [comment]
@chetanJTH Nope :|

**Comment by sebinjqburst** [comment]
@chetanJTH What I assume is like when the tests are skipped due to dependency on a failed test, the test will not be considered for execution and hence extent declaration of creating the test(extent.createTest(<name>)) won't be run and this could be why the same is not shown as a test in the report. 
So, I don't actually have an idea of forcing the extent test creation for a skipped case.

**Comment by chetanJTH** [comment]
@anshooarora please look into this matter if you have solution.

**Comment by anshooarora** [comment]
Can you share a small snippet (only the relevant code) to explain this scenario in detail?

**Comment by chetanJTH** [comment]
@anshooarora : https://stackoverflow.com/questions/59529867/why-only-second-test-suite-print-in-extent-report

can you please look into this matter?

**Comment by chetanJTH** [comment]
@anshooarora : https://github.com/chetanJTH/MutiDeviceDemo 

is git repository for skip test. 
i have added one test case.

**Comment by anshooarora** [comment]
As per your code, only the 2nd (or the last) suite is available in the report because you are instantiating the report before each suite starts, see the `@BeforeSuite`.

I would recommend maintaining a single instance of ExtentReports for all the available suites and this behavior will be as expected.

**Comment by chetanJTH** [comment]
@anshooarora : will you please help me to code for single instance and v4?

**Comment by marcinzdral** [comment]
I got similar problem recently. Found working workaround
https://stackoverflow.com/questions/59500703/skipped-test-is-not-logged-as-skipped-in-extentreport4/59544916#59544916

**Comment by sebinjqburst** [comment]
@marcinzdral Thanks for the workaround. But I believe a better workaround for the same with minimum steps would be just to re-initialise the test inside the on skipped method as below.

```
public void onTestSkipped(ITestResult iTestResult) {
   test = extent.createTest(iTestResult.getName());
   test.log(Status.SKIP, iTestResult.getThrowable().getLocalizedMessage());
   test.skip(MarkupHelper.createLabel(iTestResult.getName() + " - Test Case Skipped", ExtentColor.YELLOW));
}

```
@chetanJTH Hope this helps you too.

**Comment by ninpop25** [comment]
Guys I also faced this issue and below code worked for me
Defined the testListener like this and then call this testListener class in your Baseclass by using @Listeners(TestListeners.class) before Baseclass starts

public class TestListeners implements ITestListener {

@Override
	public void onTestSkipped(ITestResult result) {

		Baseclass.extenttest = Baseclass.extent.createTest(result.getMethod().getDescription()).assignCategory("SkipedTest");
		Baseclass.extenttest .log(Status.SKIP, result.getThrowable());
		Baseclass.extenttest .log(Status.SKIP, result.getMethod().getDescription());
		Baseclass.extenttest .log(Status.SKIP,	MarkupHelper.createLabel(result.getName(), ExtentColor.YELLOW));
		Baseclass.extent.flush();
	}
}
