### ISSUE TITLE
Logging timestamp with step in BDD reporter

### ISSUE THREAD

**Issue by sivaram-vu** [extent-framework/extentreports-java#83]
I am using the BDD reporter for logging the report.
With the current configuration, I can not see the time of the operation or logging at each step level.
Sample reports is as below.
![image](https://user-images.githubusercontent.com/20595959/58031559-f0c31f00-7b20-11e9-898a-17ca1c65600c.png)

Is there a way to log the timestamp at each step level?

**Comment by virenv** [comment]
@sivaram-vu : Please read the[ contribution guidelines](https://github.com/extent-framework/extentreports-java/blob/master/Contributing.md) and update the bug details accordingly.
