### ISSUE TITLE
I hava a question ,, when i run the extentreports-testng-adapter-example ,,come up  a ioException

### ISSUE THREAD

**Issue by huyifei2016** [extent-framework/extentreports-java#91]
use maven command: clean test ,,  listener:com.aventstack.extentreports.testng.listener.ExtentIReporterSuiteListenerAdapter
<img width="797" alt="11111" src="https://user-images.githubusercontent.com/19725517/62419093-2fda2880-b6ab-11e9-9555-da3e2fa7aad7.png">
<img width="960" alt="微信截图_20190804112748" src="https://user-images.githubusercontent.com/19725517/62419095-3799cd00-b6ab-11e9-91c6-c4662d5d936d.png">

**Comment by anshooarora** [comment]
Please share the stack trace if you are still experiencing this issue.
