### ISSUE TITLE
ExtentTest node doesn't update pass/fail info

### ISSUE THREAD

**Issue by hfontanez1968** [extent-framework/extentreports-java#93]
I am running into the following problem:
![2019-08-28 11_59_04-ExtentReports](https://user-images.githubusercontent.com/37338867/63876591-73167700-c98b-11e9-85e9-781fbe4a357c.png)

Notice how the Extent report is indicating that two steps passed, when in reality only one passed and one failed. Moreover, the failed step shows as passed in the test step node pane (center). However, when I examine the collapsible view, it shows the correct pass/fail information
![2019-08-28 12_05_03-ExtentReports](https://user-images.githubusercontent.com/37338867/63876990-41ea7680-c98c-11e9-9d57-7a9a25520804.png)

I noticed that in the extent report HTML file, the log status only updates the elements in the collapsible-body section but not in node list. The following is the section of the Extent Report with the wrong pass/fail info:

```
<li class='node level-2 leaf pass' status='pass' test-id='4'>
	<div class='collapsible-header'>
		<div class='node-name'>I hover over tile(Marketing)</div>
		<span class='node-time'>Aug 28, 2019 10:51:03 AM</span>
		&middot; <span class='node-duration'>0h 0m 0s+0ms</span>
		<span class='test-status right pass'>pass</span>
	</div>
</li>

```
In my code, I create a "Test" and a "ScenarioDef" nodes as follows:

```
@Before
public void beforeScenario(Scenario scenario)throws Exception {
	String title = "";
	for (String tagName : scenario.getSourceTagNames()) {
		String temp = tagName.substring(1);
		if (scenario.getName().substring(0, scenario.getName().indexOf(":")).equals(temp)) {
			title = temp;
			break;
		}
	}
	TestUtils.test = TestUtils.report.createTest(Feature.class, title);
	TestUtils.scenarioDef = test.createNode(scenario.getName());
}

```
Then, on the step definition itself, I create the test node. However, at the end of the execution, I do not know (or there is no interface method) to update the status of the test node with the correct pass/fail.

```
@When("(I hover)/Hover over {string}")
public void hover(String arg) throws Exception {
	String message = "I hover over " + arg;
	TestUtils.scenarioDef.createNode(new GherkinKeyword("When"), message);

	if (validate(arg)) {
		try {
			WebDriver driver = GenericAbstract.driver;
			By by = LocatorStrategyHelper.getElementBy(locatorType, identifier);
			WebElement element = new WebDriverWait(driver, waitTime)
					.until(ExpectedConditions.elementToBeClickable(by));

			Actions hover = new Actions(driver);
			hover.moveToElement(element).perform();
			TestUtils.scenarioDef.log(Status.PASS, message +" passed."); 
		} catch (Exception e) {
			TestUtils.scenarioDef.log(Status.ERROR, "Test failed" + e.getLocalizedMessage()); // This updates the collapsible element in HTML, not the test node. 
			takeFullScreenShot();
			Assert.fail();
		}

	} else {
		TestUtils.scenarioDef.log(Status.ERROR, arg + " does not conform to String pattern " + REGEX);
		}
}

```

There should be a method I could call to change the value list element's class from pass to failed so that the Extent Reports renders the test node with the correct information.

**Comment by hfontanez1968** [comment]
Whether there's activity or not, the issue is still there. What do I need to do to get someone to acknowledge it?

**Comment by anshooarora** [comment]
@hfontanez1968 what version of Cucumber are you using?

**Comment by hfontanez1968** [comment]
> 
> 
> @hfontanez1968 what version of Cucumber are you using?

3.0.2

**Comment by anshooarora** [comment]
Are you using the adapter? 

https://github.com/extent-framework/extentreports-cucumber3-adapter

**Comment by hfontanez1968** [comment]
@anshooarora 
I am not. I will try adding the adapter to the Test Runner Cucumber Options.
