### ISSUE TITLE
In BDD style ExtentHTMLReport, Tags and Exception pages display the test cases details in a hierarchical way. 

### ISSUE THREAD

**Issue by ManiR02** [extent-framework/extentreports-java#94]
In BDD style ExtentHTMLReport, Tags and Exception pages display the test cases details in a hierarchical way. 

**Sample Feature file:**
@StandardSettings
Feature: ISU Standard settings IDS disabled.

@Config01_210302
Scenario Outline: To verify the Standard setting persistence with CoolingOnly, SingleStage, Electric, None and Non-Variable configuration.

    Given User in Home screen
      And User navigating from Menu to Standard settings edit screen
    When  User chosen the OD Type as 'Cooling Only' "<ImageFilename>" and click Next
      And User chosen the OD stage as 'Single stage' "<ImageFilename>" and click Next
      And User chosen the ID unit type as 'Electric' "<ImageFilename>" and click Next
      And User chosen the ID heat stages as 'None' "<ImageFilename>" and click Next
      And User chosen the ID blower type as 'Non-Variable' "<ImageFilename>" and click Apply
      And Rebooting the Thermostat
    And User navigating from Menu to Standard settings edit screen
    Then Verify the OD unit type in 'Cooling Only' "<ImageFilename>" and click Next
      And Verify the OD unit stage in 'Single Stage' "<ImageFilename>" and click Next
      And Verify the ID unit type in 'Electric' "<ImageFilename>" and click Next
      And Verify the ID heat stage in 'None' "<ImageFilename>" and click Next
      And Verify the ID blower type in 'Non-Variable' "<ImageFilename>" and click cancel
      And User navigating from Installer screen to Home screen
    Examples:
      | ImageFilename   |
      | Config01_210302 |

In the Tags page, the test case details are displaying like below:

**Feature..ScenarioOutline..ScenarioOutline**

**For Example**
![image](https://user-images.githubusercontent.com/26895195/64328451-151d0b80-cfeb-11e9-82e7-41149ed12acd.png)

In the Exception page, the test case details are displaying like below:
**Feature..ScenarioOutline..ScenarioOutline..FailureTestStep**

**For Example**
![image](https://user-images.githubusercontent.com/26895195/64328724-9aa0bb80-cfeb-11e9-8df3-1aced459e039.png)

**In both cases, ScenarioOutline is repeated twice. Could you please make a change like below**

_**We expecting the below display**_

**For Tag page,     Feature..ScenarioOutline**
**For Exception page, Feature..ScenarioOutline..FailureTestStep**

Also, the Scenario Outline is displayed twice in the test report and need the collapse/Expand feature in test details description.
![Extent_Reporter_Issue](https://user-images.githubusercontent.com/26895195/64328099-7db7b880-cfea-11e9-84b1-491d25dda2f6.png)

**Comment by ManiR02** [comment]
@anshooarora @virenv @foursyth Please help us to resolve this issue @

**Comment by ManiR02** [comment]
@anshooarora @virenv @foursyth 

Kindly update the provide the solution for the reported issue.

**Comment by anshooarora** [comment]
@ManiR02 looking into this..  I am going to remove the hierarchy (although it will be available using a tooltip).

**Comment by anshooarora** [comment]
Closing as this being included in milestone release 4.10.0.
