### ISSUE TITLE
Screenshots are not getting attached to Klov

### ISSUE THREAD

**Issue by PratibhaRamteke** [extent-framework/extentreports-java#95]
Please merge changes from 3.1.6-SNAPSHOT to latest master or 4.0.9 #48

**Comment by anshooarora** [comment]
I am unable to reproduce this, I do see screenshots (both file/base64) in Klov.  Would like to see any behavior that can replicate this, can you share a snippet?

**Comment by PratibhaRamteke** [comment]
- Sure.. The f/w I am using is cucumber. And I am trying to integrate klov reports with cucumber using testng.
- I have used TestNGCucumberRunner runner class with accepts the cucumber options like below and runs the scenario from the specified location.
 @CucumberOptions(
 			features= {"src/test/resources/com/sas/dvt/automation/features/visualanalyticsnext"},
 			glue= {"com.sas.dvt.automation.stepdefinitions.visualanalyticsnext"},
 			plugin = {"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:",
 		              "pretty", "json:target/cucumber-reports/Cucumber.json"
 		              },
 			monochrome = true
 		)
- I have used    	    
`<dependency>extentcucumberadapter 4 (pom.xml)
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports-cucumber4-adapter</artifactId>
            <version>1.0.7</version>






        </dependency>`

- Find attached feature and stepdefinition files
![Feature_file](https://user-images.githubusercontent.com/43991476/71462235-ac93ad80-27d8-11ea-985d-aabc66276309.png)

![stepDefinition](https://user-images.githubusercontent.com/43991476/71462238-b3222500-27d8-11ea-9a8b-e90e297dea12.png)

- Images are getting generated properly. And also getting attached to logger report. But when it comes to klov report. I am getting a warning

> WARNING: Unable to upload file to server <path>\GraphAutomationReporting\test-output\embedded2.png

- The responsecode from storeMedia() method of HttpMediaManagerImplKlov is coming as 500
![Error](https://user-images.githubusercontent.com/43991476/71464909-144df680-27e1-11ea-8936-baaf0fc4d812.png)

- Logger report is having images
![Images_LoggerReport](https://user-images.githubusercontent.com/43991476/71464947-35164c00-27e1-11ea-81be-4a04de3488af.png)

-klov doesnt have
![NoImages_KlovReport](https://user-images.githubusercontent.com/43991476/71464954-3c3d5a00-27e1-11ea-8620-6ba3868844f0.png)

Let me know if you need more information on this

**Comment by anshooarora** [comment]
Appreciate the detailed info.  Can you also share `extent.properties` and `klov.properties`?

**Comment by PratibhaRamteke** [comment]
Thanks for the quick reply. Here are the files:

- extent.properties
extent.reporter.avent.start=false
extent.reporter.bdd.start=false
extent.reporter.cards.start=false
extent.reporter.email.start=false
extent.reporter.html.start=true
extent.reporter.klov.start=true
extent.reporter.logger.start=true
extent.reporter.tabular.start=false

extent.reporter.avent.config=
extent.reporter.bdd.config=
extent.reporter.cards.config=
extent.reporter.email.config=
extent.reporter.html.config=
extent.reporter.klov.config=src/test/resources/klov.properties
extent.reporter.logger.config=
extent.reporter.tabular.config=

extent.reporter.avent.out=test-output/AventReport/
extent.reporter.bdd.out=test-output/BddReport/
extent.reporter.cards.out=test-output/CardsReport/
extent.reporter.email.out=test-output/EmailReport/ExtentEmail.html
extent.reporter.html.out=test-output/HtmlReport/ExtentHtml.html
extent.reporter.logger.out=test-output/LoggerReport/
extent.reporter.tabular.out=test-output/TabularReport/

-klov.properties
klov.port=8585
klov.host=http\://localhost
klov.report.name=
mongodb.port=27017
klov.project.name=
mongodb.uri=
mongodb.host=localhost

**Comment by anshooarora** [comment]
You are missing the `screenshot.dir` in `extent.properties`.  Add:

```
screenshot.dir=test-output/
```

**Comment by PratibhaRamteke** [comment]
Tried setting screenshot.dir. Still the same issue persists. Screenshots are not attaching to klov reports.

**Comment by PratibhaRamteke** [comment]
Any updates on this?

**Comment by anshooarora** [comment]
Everything I have seen from your screenshots looks valid,  but I haven't been able to reproduce this with the exact same steps as yours.  Can you debug `HttpMediaManagerImplKlov` as in this screenshot https://user-images.githubusercontent.com/43991476/71464909-144df680-27e1-11ea-8936-baaf0fc4d812.png and see if any of the parts (lines 57-62, 65) are empty?

**Comment by PratibhaRamteke** [comment]
Yes, i checked the lines mentioned by you. 

- Line 52-62 and 65 are not empty. They are having values. Find below screenshot for client values.

- Line 67:  HttpClient client = HttpClientBuilder.create().build();

![image](https://user-images.githubusercontent.com/43991476/71881151-c4afe900-3157-11ea-8042-7a2eea29ca0a.png)

- Line 68: this is the response generated
`HttpResponseProxy{HTTP/1.1 500  [X-Content-Type-Options: nosniff, X-XSS-Protection: 1; mode=block, Cache-Control: no-cache, no-store, max-age=0, must-revalidate, Pragma: no-cache, Expires: 0, X-Frame-Options: DENY, Content-Type: application/json;charset=UTF-8, Transfer-Encoding: chunked, Date: Tue, 07 Jan 2020 08:38:42 GMT, Connection: close] ResponseEntityProxy{[Content-Type: application/json;charset=UTF-8,Chunked: true]}}`

line 70: responseCode is coming as 500 which  is Internal Server Error, Here is the issue. As per This method responseCode should be between 200 to 399.

` private boolean isResponseValid(int responseCode) {
        return 200 <= responseCode && responseCode <= 399;
    }
`


- If the response comes correct then the images will get attach to the klov. 
Could you please check on this?

**Comment by anshooarora** [comment]
I did and no issues on my local, cloud or our internal prod instances.  Not exactly sure what is going on without looking at what's going on.

Can you shoot me an email?  My gmail is anshooarora.

**Comment by anshooarora** [comment]
@PratibhaRamteke Klov v1.0 is now available to be ised with ExtentReports 5 release. This issue ans many others have been resolved with this upgrade.
